// Farm-to-Grocer MVP - NextAuth.js API Route Handler
// Path: app/api/auth/[...nextauth]/route.ts
// Generated by RJBot Orchestrator
//
// This file handles all authentication requests via NextAuth.js
// Using Next.js 14 App Router with Route Handlers

import NextAuth from "next-auth";
import { authOptions } from "@/lib/auth";

// ============================================
// NEXTAUTH ROUTE HANDLER
// ============================================

/**
 * NextAuth.js Route Handler
 * 
 * Handles all authentication routes:
 * - GET /api/auth/signin - Sign in page
 * - POST /api/auth/signin/:provider - Sign in with provider
 * - GET /api/auth/signout - Sign out page
 * - POST /api/auth/signout - Sign out action
 * - GET /api/auth/session - Get session
 * - GET /api/auth/csrf - Get CSRF token
 * - GET /api/auth/providers - Get available providers
 * - GET /api/auth/callback/:provider - OAuth callback
 * - POST /api/auth/callback/credentials - Credentials callback
 */
const handler = NextAuth(authOptions);

// Export handlers for App Router
export { handler as GET, handler as POST };

// ============================================
// ADDITIONAL EXPORTS (Optional)
// ============================================

/**
 * Export auth options for use in other files
 * This allows importing authOptions from this file if needed
 * 
 * Usage:
 * import { authOptions } from "@/app/api/auth/[...nextauth]/route";
 * const session = await getServerSession(authOptions);
 */
export { authOptions };
