// Farm-to-Grocer MVP - Grocer Dashboard Page
// Path: app/(dashboard)/grocer/page.tsx
// Generated by RJBot Orchestrator
//
// A comprehensive grocer dashboard with:
// - Key metrics/stats cards (spending, orders, savings)
// - Recent orders with status tracking
// - Favorite/frequent suppliers
// - Recommended products
// - Quick actions for common tasks
// - Spending analytics chart

import { Suspense } from "react";
import { redirect } from "next/navigation";
import Link from "next/link";
import {
  ShoppingCart,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Package,
  Store,
  Star,
  Clock,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  Search,
  Heart,
  Truck,
  CheckCircle2,
  AlertCircle,
  Leaf,
  MapPin,
  Plus,
  RefreshCw,
} from "lucide-react";

import { requireGrocer } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { formatCurrency, formatDate, formatRelativeTime } from "@/lib/utils";
import { OrderStatus, OrderStatusLabels } from "@/types";

// Components
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { Skeleton } from "@/components/ui/Skeleton";
import { OrderStatusBadge } from "@/components/orders/OrderStatusBadge";

// ============================================
// METADATA
// ============================================

export const metadata = {
  title: "Grocer Dashboard",
  description: "Manage your orders, browse local farmers, and track your spending.",
};

// ============================================
// DATA FETCHING FUNCTIONS
// ============================================

/**
 * Fetch grocer dashboard statistics
 */
async function getGrocerStats(grocerId: string) {
  const now = new Date();
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  const startOfLastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const endOfLastMonth = new Date(now.getFullYear(), now.getMonth(), 0);

  // Execute all queries in parallel
  const [
    totalOrders,
    activeOrders,
    thisMonthOrders,
    lastMonthOrders,
    thisMonthSpending,
    lastMonthSpending,
    favoriteFarmers,
    grocer,
  ] = await Promise.all([
    // Total orders
    prisma.order.count({
      where: { grocerId },
    }),

    // Active orders (not delivered or cancelled)
    prisma.order.count({
      where: {
        grocerId,
        status: { notIn: ["DELIVERED", "CANCELLED", "REFUNDED"] },
      },
    }),

    // This month orders
    prisma.order.count({
      where: { grocerId, createdAt: { gte: startOfMonth } },
    }),

    // Last month orders
    prisma.order.count({
      where: {
        grocerId,
        createdAt: { gte: startOfLastMonth, lte: endOfLastMonth },
      },
    }),

    // This month spending
    prisma.order.aggregate({
      where: {
        grocerId,
        status: { notIn: ["CANCELLED", "REFUNDED"] },
        createdAt: { gte: startOfMonth },
      },
      _sum: { total: true },
    }),

    // Last month spending
    prisma.order.aggregate({
      where: {
        grocerId,
        status: { notIn: ["CANCELLED", "REFUNDED"] },
        createdAt: { gte: startOfLastMonth, lte: endOfLastMonth },
      },
      _sum: { total: true },
    }),

    // Favorite farmers count
    prisma.favoriteFarmer.count({
      where: { grocerId },
    }),

    // Grocer profile
    prisma.grocer.findUnique({
      where: { id: grocerId },
      select: { businessName: true },
    }),
  ]);

  // Calculate percentage changes
  const thisMonthSpendingValue = thisMonthSpending._sum.total || 0;
  const lastMonthSpendingValue = lastMonthSpending._sum.total || 0;
  const spendingChange = lastMonthSpendingValue > 0
    ? ((thisMonthSpendingValue - lastMonthSpendingValue) / lastMonthSpendingValue) * 100
    : 0;

  const ordersChange = lastMonthOrders > 0
    ? ((thisMonthOrders - lastMonthOrders) / lastMonthOrders) * 100
    : 0;

  return {
    totalOrders,
    activeOrders,
    thisMonthOrders,
    thisMonthSpending: thisMonthSpendingValue,
    spendingChange,
    ordersChange,
    favoriteFarmers,
    businessName: grocer?.businessName || "Your Business",
  };
}

/**
 * Fetch recent orders for the grocer
 */
async function getRecentOrders(grocerId: string, limit: number = 5) {
  return prisma.order.findMany({
    where: { grocerId },
    orderBy: { createdAt: "desc" },
    take: limit,
    include: {
      farmer: {
        include: {
          user: {
            select: { name: true },
          },
        },
      },
      items: {
        select: { id: true },
      },
    },
  });
}

/**
 * Fetch favorite/frequent suppliers
 */
async function getFavoriteSuppliers(grocerId: string, limit: number = 4) {
  // Get farmers the grocer has ordered from most frequently
  const frequentFarmers = await prisma.order.groupBy({
    by: ["farmerId"],
    where: {
      grocerId,
      status: "DELIVERED",
    },
    _count: true,
    _sum: { total: true },
    orderBy: {
      _count: {
        farmerId: "desc",
      },
    },
    take: limit,
  });

  // Fetch farmer details
  const farmerIds = frequentFarmers.map((f) => f.farmerId);
  const farmers = await prisma.farmer.findMany({
    where: { id: { in: farmerIds } },
    include: {
      user: {
        select: { name: true },
      },
      _count: {
        select: { products: { where: { status: "ACTIVE" } } },
      },
    },
  });

  return frequentFarmers.map((ff) => {
    const farmer = farmers.find((f) => f.id === ff.farmerId);
    return {
      id: ff.farmerId,
      farmName: farmer?.farmName || "Unknown Farm",
      ownerName: farmer?.user.name || "Unknown",
      city: farmer?.city || "",
      state: farmer?.state || "",
      rating: farmer?.rating || 0,
      isVerified: farmer?.isVerified || false,
      productCount: farmer?._count.products || 0,
      orderCount: ff._count,
      totalSpent: ff._sum.total || 0,
    };
  });
}

/**
 * Fetch recommended products
 */
async function getRecommendedProducts(grocerId: string, limit: number = 6) {
  // Get products from farmers the grocer has ordered from before
  // or highly rated products
  const products = await prisma.product.findMany({
    where: {
      status: "ACTIVE",
      availableQty: { gt: 0 },
    },
    orderBy: [
      { farmer: { rating: "desc" } },
      { createdAt: "desc" },
    ],
    take: limit,
    include: {
      farmer: {
        select: {
          farmName: true,
          city: true,
          state: true,
          rating: true,
          isVerified: true,
        },
      },
    },
  });

  return products;
}

/**
 * Fetch spending data for chart (last 7 days)
 */
async function getSpendingChartData(grocerId: string) {
  const days = 7;
  const data = [];

  for (let i = days - 1; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    date.setHours(0, 0, 0, 0);

    const nextDate = new Date(date);
    nextDate.setDate(nextDate.getDate() + 1);

    const daySpending = await prisma.order.aggregate({
      where: {
        grocerId,
        status: { notIn: ["CANCELLED", "REFUNDED"] },
        createdAt: {
          gte: date,
          lt: nextDate,
        },
      },
      _sum: { total: true },
      _count: true,
    });

    data.push({
      date: date.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" }),
      spending: daySpending._sum.total || 0,
      orders: daySpending._count || 0,
    });
  }

  return data;
}

// ============================================
// COMPONENT: STATS CARD
// ============================================

interface StatsCardProps {
  title: string;
  value: string | number;
  description?: string;
  icon: React.ReactNode;
  trend?: {
    value: number;
    isPositive: boolean;
    invertColors?: boolean; // For spending, down is good
  };
  variant?: "default" | "warning" | "success" | "info";
}

function StatsCard({ title, value, description, icon, trend, variant = "default" }: StatsCardProps) {
  const variantStyles = {
    default: "bg-card",
    warning: "bg-amber-50 border-amber-200 dark:bg-amber-950/20 dark:border-amber-800",
    success: "bg-green-50 border-green-200 dark:bg-green-950/20 dark:border-green-800",
    info: "bg-blue-50 border-blue-200 dark:bg-blue-950/20 dark:border-blue-800",
  };

  return (
    <Card className={variantStyles[variant]}>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium text-muted-foreground">
          {title}
        </CardTitle>
        <div className="h-8 w-8 rounded-md bg-primary/10 flex items-center justify-center text-primary">
          {icon}
        </div>
      </CardHeader>
      <CardContent>
        <div className="text-2xl font-bold">{value}</div>
        {(description || trend) && (
          <div className="flex items-center gap-2 mt-1">
            {trend && (
              <span
                className={`inline-flex items-center text-xs font-medium ${
                  trend.invertColors
                    ? trend.isPositive
                      ? "text-red-600"
                      : "text-green-600"
                    : trend.isPositive
                    ? "text-green-600"
                    : "text-red-600"
                }`}
              >
                {trend.isPositive ? (
                  <ArrowUpRight className="h-3 w-3 mr-0.5" />
                ) : (
                  <ArrowDownRight className="h-3 w-3 mr-0.5" />
                )}
                {Math.abs(trend.value).toFixed(1)}%
              </span>
            )}
            {description && (
              <p className="text-xs text-muted-foreground">{description}</p>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// ============================================
// COMPONENT: RECENT ORDERS
// ============================================

function RecentOrdersTable({ orders }: { orders: Awaited<ReturnType<typeof getRecentOrders>> }) {
  if (orders.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <ShoppingCart className="h-12 w-12 text-muted-foreground/50 mb-4" />
        <h3 className="text-lg font-medium">No orders yet</h3>
        <p className="text-sm text-muted-foreground mt-1">
          Start browsing products from local farmers.
        </p>
        <Button className="mt-4" asChild>
          <Link href="/grocer/browse">
            <Search className="h-4 w-4 mr-2" />
            Browse Products
          </Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {orders.map((order) => (
        <Link
          key={order.id}
          href={`/grocer/orders/${order.id}`}
          className="flex items-center justify-between p-4 rounded-lg border bg-card hover:bg-accent/50 transition-colors"
        >
          <div className="flex items-center gap-4">
            <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
              <Package className="h-5 w-5 text-primary" />
            </div>
            <div>
              <p className="font-medium">{order.orderNumber}</p>
              <p className="text-sm text-muted-foreground">
                {order.farmer.farmName} • {order.items.length} items
              </p>
            </div>
          </div>
          <div className="text-right">
            <p className="font-medium">{formatCurrency(order.total)}</p>
            <OrderStatusBadge status={order.status} size="sm" />
          </div>
        </Link>
      ))}
    </div>
  );
}

// ============================================
// COMPONENT: FAVORITE SUPPLIERS
// ============================================

function FavoriteSuppliersList({ suppliers }: { suppliers: Awaited<ReturnType<typeof getFavoriteSuppliers>> }) {
  if (suppliers.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <Heart className="h-12 w-12 text-muted-foreground/50 mb-4" />
        <h3 className="text-lg font-medium">No favorite suppliers yet</h3>
        <p className="text-sm text-muted-foreground mt-1">
          Order from farmers to build your supplier network.
        </p>
      </div>
    );
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2">
      {suppliers.map((supplier) => (
        <Link
          key={supplier.id}
          href={`/grocer/farmers/${supplier.id}`}
          className="flex items-start gap-4 p-4 rounded-lg border bg-card hover:bg-accent/50 transition-colors"
        >
          <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
            <Store className="h-6 w-6 text-primary" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2">
              <h4 className="font-medium truncate">{supplier.farmName}</h4>
              {supplier.isVerified && (
                <CheckCircle2 className="h-4 w-4 text-primary flex-shrink-0" />
              )}
            </div>
            <p className="text-sm text-muted-foreground flex items-center gap-1">
              <MapPin className="h-3 w-3" />
              {supplier.city}, {supplier.state}
            </p>
            <div className="flex items-center gap-3 mt-2 text-xs text-muted-foreground">
              <span className="flex items-center gap-1">
                <Star className="h-3 w-3 fill-amber-400 text-amber-400" />
                {supplier.rating.toFixed(1)}
              </span>
              <span>{supplier.productCount} products</span>
              <span>{supplier.orderCount} orders</span>
            </div>
          </div>
        </Link>
      ))}
    </div>
  );
}

// ============================================
// COMPONENT: RECOMMENDED PRODUCTS
// ============================================

function RecommendedProducts({ products }: { products: Awaited<ReturnType<typeof getRecommendedProducts>> }) {
  if (products.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <Leaf className="h-12 w-12 text-muted-foreground/50 mb-4" />
        <h3 className="text-lg font-medium">No products available</h3>
        <p className="text-sm text-muted-foreground mt-1">
          Check back later for fresh produce.
        </p>
      </div>
    );
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {products.map((product) => (
        <Link
          key={product.id}
          href={`/grocer/products/${product.id}`}
          className="group rounded-lg border bg-card overflow-hidden hover:shadow-md transition-all"
        >
          {/* Image */}
          <div className="relative aspect-[4/3] overflow-hidden bg-muted">
            <img
              src={product.images?.[0] || "/images/placeholder-product.jpg"}
              alt={product.name}
              className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
            />
            {product.isOrganic && (
              <span className="absolute top-2 left-2 inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                <Leaf className="h-3 w-3" />
                Organic
              </span>
            )}
          </div>

          {/* Info */}
          <div className="p-4">
            <p className="text-xs text-muted-foreground mb-1">
              {product.farmer.farmName}
            </p>
            <h4 className="font-medium line-clamp-1 group-hover:text-primary transition-colors">
              {product.name}
            </h4>
            <div className="flex items-center justify-between mt-2">
              <div>
                <span className="text-lg font-bold text-primary">
                  {formatCurrency(product.pricePerUnit)}
                </span>
                <span className="text-sm text-muted-foreground">
                  /{product.unit.toLowerCase()}
                </span>
              </div>
              <div className="flex items-center gap-1 text-sm text-muted-foreground">
                <Star className="h-3.5 w-3.5 fill-amber-400 text-amber-400" />
                {product.farmer.rating?.toFixed(1) || "New"}
              </div>
            </div>
          </div>
        </Link>
      ))}
    </div>
  );
}

// ============================================
// LOADING SKELETONS
// ============================================

function StatsCardSkeleton() {
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <Skeleton className="h-4 w-24" />
        <Skeleton className="h-8 w-8 rounded-md" />
      </CardHeader>
      <CardContent>
        <Skeleton className="h-8 w-20 mb-2" />
        <Skeleton className="h-3 w-32" />
      </CardContent>
    </Card>
  );
}

function RecentOrdersSkeleton() {
  return (
    <div className="space-y-4">
      {[...Array(5)].map((_, i) => (
        <div key={i} className="flex items-center justify-between p-4 rounded-lg border">
          <div className="flex items-center gap-4">
            <Skeleton className="h-10 w-10 rounded-full" />
            <div>
              <Skeleton className="h-4 w-32 mb-2" />
              <Skeleton className="h-3 w-24" />
            </div>
          </div>
          <div className="text-right">
            <Skeleton className="h-4 w-16 mb-2" />
            <Skeleton className="h-5 w-20" />
          </div>
        </div>
      ))}
    </div>
  );
}

// ============================================
// MAIN PAGE COMPONENT
// ============================================

export default async function GrocerDashboardPage() {
  // Authenticate and get grocer data
  let grocer;
  try {
    grocer = await requireGrocer();
  } catch (error) {
    redirect("/login?callbackUrl=/grocer");
  }

  // Fetch all dashboard data in parallel
  const [stats, recentOrders, favoriteSuppliers, recommendedProducts] = await Promise.all([
    getGrocerStats(grocer.grocerId),
    getRecentOrders(grocer.grocerId),
    getFavoriteSuppliers(grocer.grocerId),
    getRecommendedProducts(grocer.grocerId),
  ]);

  return (
    <div className="flex-1 space-y-6 p-6 md:p-8">
      {/* Header */}
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">
            Welcome back! 👋
          </h1>
          <p className="text-muted-foreground">
            Here's what's happening with {stats.businessName} today.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" asChild>
            <Link href="/grocer/orders">
              <Package className="h-4 w-4 mr-2" />
              View Orders
            </Link>
          </Button>
          <Button asChild>
            <Link href="/grocer/browse">
              <Search className="h-4 w-4 mr-2" />
              Browse Products
            </Link>
          </Button>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatsCard
          title="Monthly Spending"
          value={formatCurrency(stats.thisMonthSpending)}
          icon={<DollarSign className="h-4 w-4" />}
          trend={{
            value: stats.spendingChange,
            isPositive: stats.spendingChange >= 0,
            invertColors: true, // Lower spending = green
          }}
          description="vs last month"
        />
        <StatsCard
          title="Orders This Month"
          value={stats.thisMonthOrders}
          icon={<ShoppingCart className="h-4 w-4" />}
          trend={{
            value: stats.ordersChange,
            isPositive: stats.ordersChange >= 0,
          }}
          description="vs last month"
        />
        <StatsCard
          title="Active Orders"
          value={stats.activeOrders}
          icon={<Truck className="h-4 w-4" />}
          description="in progress"
          variant={stats.activeOrders > 0 ? "info" : "default"}
        />
        <StatsCard
          title="Favorite Suppliers"
          value={stats.favoriteFarmers}
          icon={<Heart className="h-4 w-4" />}
          description="local farmers"
          variant="success"
        />
      </div>

      {/* Active Orders Alert */}
      {stats.activeOrders > 0 && (
        <Card className="border-blue-200 bg-blue-50 dark:bg-blue-950/20 dark:border-blue-800">
          <CardContent className="flex items-center gap-4 py-4">
            <div className="h-10 w-10 rounded-full bg-blue-100 dark:bg-blue-900 flex items-center justify-center">
              <Truck className="h-5 w-5 text-blue-600" />
            </div>
            <div className="flex-1">
              <p className="font-medium text-blue-800 dark:text-blue-200">
                You have {stats.activeOrders} active order{stats.activeOrders > 1 ? "s" : ""}
              </p>
              <p className="text-sm text-blue-600 dark:text-blue-400">
                Track your deliveries and manage your orders.
              </p>
            </div>
            <Button variant="outline" size="sm" asChild className="border-blue-300 hover:bg-blue-100">
              <Link href="/grocer/orders?status=active">
                Track Orders
                <ArrowRight className="h-4 w-4 ml-2" />
              </Link>
            </Button>
          </CardContent>
        </Card>
      )}

      {/* Main Content Grid */}
      <div className="grid gap-6 lg:grid-cols-7">
        {/* Recent Orders */}
        <Card className="lg:col-span-4">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle>Recent Orders</CardTitle>
              <CardDescription>Your latest orders from local farmers</CardDescription>
            </div>
            <Button variant="ghost" size="sm" asChild>
              <Link href="/grocer/orders">
                View All
                <ArrowRight className="h-4 w-4 ml-1" />
              </Link>
            </Button>
          </CardHeader>
          <CardContent>
            <Suspense fallback={<RecentOrdersSkeleton />}>
              <RecentOrdersTable orders={recentOrders} />
            </Suspense>
          </CardContent>
        </Card>

        {/* Favorite Suppliers */}
        <Card className="lg:col-span-3">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle>Your Suppliers</CardTitle>
              <CardDescription>Farmers you order from frequently</CardDescription>
            </div>
            <Button variant="ghost" size="sm" asChild>
              <Link href="/grocer/farmers">
                View All
                <ArrowRight className="h-4 w-4 ml-1" />
              </Link>
            </Button>
          </CardHeader>
          <CardContent>
            <FavoriteSuppliersList suppliers={favoriteSuppliers} />
          </CardContent>
        </Card>
      </div>

      {/* Recommended Products */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle>Recommended For You</CardTitle>
            <CardDescription>Fresh products from top-rated local farmers</CardDescription>
          </div>
          <Button variant="ghost" size="sm" asChild>
            <Link href="/grocer/browse">
              Browse All
              <ArrowRight className="h-4 w-4 ml-1" />
            </Link>
          </Button>
        </CardHeader>
        <CardContent>
          <RecommendedProducts products={recommendedProducts} />
        </CardContent>
      </Card>

      {/* Quick Actions */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card className="hover:border-primary/50 transition-colors cursor-pointer group">
          <Link href="/grocer/browse">
            <CardContent className="flex items-center gap-4 py-6">
              <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                <Search className="h-6 w-6 text-primary" />
              </div>
              <div>
                <p className="font-medium">Browse Products</p>
                <p className="text-sm text-muted-foreground">Find fresh local produce</p>
              </div>
            </CardContent>
          </Link>
        </Card>

        <Card className="hover:border-primary/50 transition-colors cursor-pointer group">
          <Link href="/grocer/orders">
            <CardContent className="flex items-center gap-4 py-6">
              <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                <Package className="h-6 w-6 text-primary" />
              </div>
              <div>
                <p className="font-medium">Manage Orders</p>
                <p className="text-sm text-muted-foreground">Track and manage deliveries</p>
              </div>
            </CardContent>
          </Link>
        </Card>

        <Card className="hover:border-primary/50 transition-colors cursor-pointer group">
          <Link href="/grocer/reorder">
            <CardContent className="flex items-center gap-4 py-6">
              <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                <RefreshCw className="h-6 w-6 text-primary" />
              </div>
              <div>
                <p className="font-medium">Quick Reorder</p>
                <p className="text-sm text-muted-foreground">Repeat previous orders</p>
              </div>
            </CardContent>
          </Link>
        </Card>
      </div>
    </div>
  );
}
