// Farm-to-Grocer MVP - Next.js Configuration
// Path: next.config.js
// Generated by RJBot Orchestrator
//
// This configuration file customizes Next.js behavior including:
// - Image optimization with remote patterns
// - Security headers
// - Redirects and rewrites
// - Environment variables
// - Webpack customization
// - Performance optimizations

/** @type {import('next').NextConfig} */
const nextConfig = {
  // ============================================
  // REACT STRICT MODE
  // ============================================
  reactStrictMode: true,

  // ============================================
  // EXPERIMENTAL FEATURES
  // ============================================
  experimental: {
    // Enable Server Actions (stable in Next.js 14+)
    serverActions: {
      bodySizeLimit: "2mb",
      allowedOrigins: ["localhost:3000"],
    },
    // Optimize package imports
    optimizePackageImports: [
      "lucide-react",
      "@radix-ui/react-icons",
      "date-fns",
      "recharts",
    ],
    // Enable typed routes (optional)
    typedRoutes: true,
  },

  // ============================================
  // IMAGE OPTIMIZATION
  // ============================================
  images: {
    // Enable modern image formats
    formats: ["image/avif", "image/webp"],

    // Remote image patterns (for user-uploaded images)
    remotePatterns: [
      // UploadThing (file uploads)
      {
        protocol: "https",
        hostname: "uploadthing.com",
        pathname: "/f/**",
      },
      {
        protocol: "https",
        hostname: "utfs.io",
        pathname: "/f/**",
      },
      // AWS S3 (if using S3 for storage)
      {
        protocol: "https",
        hostname: "*.s3.amazonaws.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "*.s3.*.amazonaws.com",
        pathname: "/**",
      },
      // Cloudinary (if using Cloudinary)
      {
        protocol: "https",
        hostname: "res.cloudinary.com",
        pathname: "/**",
      },
      // Google user avatars (for OAuth)
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
        pathname: "/**",
      },
      // Placeholder images
      {
        protocol: "https",
        hostname: "images.unsplash.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "via.placeholder.com",
        pathname: "/**",
      },
      // Local development
      {
        protocol: "http",
        hostname: "localhost",
        port: "3000",
        pathname: "/**",
      },
    ],

    // Device sizes for responsive images
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],

    // Image sizes for the `sizes` attribute
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],

    // Minimum cache TTL (in seconds)
    minimumCacheTTL: 60 * 60 * 24, // 24 hours

    // Disable static image imports (optional)
    // disableStaticImages: false,
  },

  // ============================================
  // ENVIRONMENT VARIABLES (Public)
  // ============================================
  env: {
    NEXT_PUBLIC_APP_NAME: "Farm to Grocer",
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
    NEXT_PUBLIC_SUPPORT_EMAIL: "support@farmtogrocer.com",
  },

  // ============================================
  // REDIRECTS
  // ============================================
  async redirects() {
    return [
      // Redirect old routes to new ones
      {
        source: "/dashboard",
        destination: "/farmer",
        permanent: false,
      },
      {
        source: "/dashboard/farmer",
        destination: "/farmer",
        permanent: true,
      },
      {
        source: "/dashboard/grocer",
        destination: "/grocer",
        permanent: true,
      },
      // Redirect /home to /
      {
        source: "/home",
        destination: "/",
        permanent: true,
      },
      // Redirect /signin to /login
      {
        source: "/signin",
        destination: "/login",
        permanent: true,
      },
      {
        source: "/signup",
        destination: "/register",
        permanent: true,
      },
      // Redirect www to non-www (in production)
      ...(process.env.NODE_ENV === "production"
        ? [
            {
              source: "/:path*",
              has: [
                {
                  type: "host",
                  value: "www.farmtogrocer.com",
                },
              ],
              destination: "https://farmtogrocer.com/:path*",
              permanent: true,
            },
          ]
        : []),
    ];
  },

  // ============================================
  // REWRITES
  // ============================================
  async rewrites() {
    return {
      beforeFiles: [
        // Rewrite for API versioning
        {
          source: "/api/v1/:path*",
          destination: "/api/:path*",
        },
      ],
      afterFiles: [
        // Proxy to external services (if needed)
        // {
        //   source: "/external-api/:path*",
        //   destination: "https://external-service.com/:path*",
        // },
      ],
      fallback: [
        // Fallback rewrites
      ],
    };
  },

  // ============================================
  // CUSTOM HEADERS
  // ============================================
  async headers() {
    return [
      {
        // Apply to all routes
        source: "/:path*",
        headers: [
          // Security headers
          {
            key: "X-DNS-Prefetch-Control",
            value: "on",
          },
          {
            key: "X-Frame-Options",
            value: "SAMEORIGIN",
          },
          {
            key: "X-Content-Type-Options",
            value: "nosniff",
          },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(self)",
          },
        ],
      },
      {
        // Cache static assets
        source: "/images/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
      {
        // Cache fonts
        source: "/fonts/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
      {
        // API CORS headers (for public endpoints)
        source: "/api/public/:path*",
        headers: [
          {
            key: "Access-Control-Allow-Origin",
            value: "*",
          },
          {
            key: "Access-Control-Allow-Methods",
            value: "GET, OPTIONS",
          },
          {
            key: "Access-Control-Allow-Headers",
            value: "Content-Type, Authorization",
          },
        ],
      },
    ];
  },

  // ============================================
  // WEBPACK CONFIGURATION
  // ============================================
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // Add custom aliases
    config.resolve.alias = {
      ...config.resolve.alias,
      "@": require("path").resolve(__dirname),
    };

    // Handle SVG imports as React components
    config.module.rules.push({
      test: /\.svg$/,
      use: [
        {
          loader: "@svgr/webpack",
          options: {
            svgoConfig: {
              plugins: [
                {
                  name: "removeViewBox",
                  active: false,
                },
              ],
            },
          },
        },
      ],
    });

    // Ignore specific modules on client-side
    if (!isServer) {
      config.resolve.fallback = {
        ...config.resolve.fallback,
        fs: false,
        net: false,
        tls: false,
        crypto: false,
      };
    }

    // Add bundle analyzer in analyze mode
    if (process.env.ANALYZE === "true") {
      const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");
      config.plugins.push(
        new BundleAnalyzerPlugin({
          analyzerMode: "static",
          reportFilename: isServer
            ? "../analyze/server.html"
            : "./analyze/client.html",
          openAnalyzer: false,
        })
      );
    }

    return config;
  },

  // ============================================
  // TYPESCRIPT
  // ============================================
  typescript: {
    // Dangerously allow production builds to complete even with type errors
    // Set to true only if you have a separate type-checking step
    ignoreBuildErrors: false,
  },

  // ============================================
  // ESLINT
  // ============================================
  eslint: {
    // Run ESLint on these directories during build
    dirs: ["app", "components", "lib", "types"],
    // Dangerously allow production builds to complete even with ESLint errors
    ignoreDuringBuilds: false,
  },

  // ============================================
  // LOGGING
  // ============================================
  logging: {
    fetches: {
      fullUrl: true,
    },
  },

  // ============================================
  // OUTPUT CONFIGURATION
  // ============================================
  // output: "standalone", // Uncomment for Docker deployments

  // ============================================
  // POWERED BY HEADER
  // ============================================
  poweredByHeader: false, // Remove X-Powered-By header for security

  // ============================================
  // COMPRESSION
  // ============================================
  compress: true,

  // ============================================
  // GENERATE ETAGS
  // ============================================
  generateEtags: true,

  // ============================================
  // PAGE EXTENSIONS
  // ============================================
  pageExtensions: ["tsx", "ts", "jsx", "js", "mdx"],

  // ============================================
  // TRAILING SLASH
  // ============================================
  trailingSlash: false,

  // ============================================
  // MODULAR IMPORTS (Tree Shaking)
  // ============================================
  modularizeImports: {
    "lucide-react": {
      transform: "lucide-react/dist/esm/icons/{{kebabCase member}}",
    },
    "@heroicons/react/24/outline": {
      transform: "@heroicons/react/24/outline/{{member}}",
    },
    "@heroicons/react/24/solid": {
      transform: "@heroicons/react/24/solid/{{member}}",
    },
    "date-fns": {
      transform: "date-fns/{{member}}",
    },
  },

  // ============================================
  // PRODUCTION BROWSER SOURCE MAPS
  // ============================================
  productionBrowserSourceMaps: false, // Set to true for debugging production issues

  // ============================================
  // SKIP MIDDLEWARE URL NORMALIZE
  // ============================================
  skipMiddlewareUrlNormalize: false,

  // ============================================
  // SKIP TRAILING SLASH REDIRECT
  // ============================================
  skipTrailingSlashRedirect: false,
};

// ============================================
// BUNDLE ANALYZER WRAPPER (Optional)
// ============================================

// Wrap config with bundle analyzer if ANALYZE env is set
const withBundleAnalyzer =
  process.env.ANALYZE === "true"
    ? require("@next/bundle-analyzer")({ enabled: true })
    : (config) => config;

// ============================================
// EXPORT CONFIGURATION
// ============================================

module.exports = withBundleAnalyzer(nextConfig);
