// Farm-to-Grocer MVP - Onboarding Wizard Component
// Path: app/onboarding/onboarding-wizard.tsx
// Generated by RJBot Orchestrator
//
// A comprehensive multi-step onboarding wizard with:
// - 4 steps: Role Selection → Business Info → Address → Profile
// - Zod validation for each step
// - Progress indicator with step labels
// - Data persistence across steps
// - Server action integration
// - Animated transitions
// - Mobile-responsive design

"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  Leaf,
  Store,
  Building2,
  MapPin,
  User,
  ChevronRight,
  ChevronLeft,
  Check,
  Loader2,
  Upload,
  Phone,
  Globe,
  Camera,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/Button";
import { completeOnboarding } from "./actions";

// ============================================
// TYPES & INTERFACES
// ============================================

interface SessionUser {
  id: string;
  name?: string | null;
  email?: string | null;
  image?: string | null;
  role?: "FARMER" | "GROCER" | "ADMIN";
}

interface OnboardingWizardProps {
  user: SessionUser;
}

type StepId = "role" | "business" | "address" | "profile";

interface Step {
  id: StepId;
  title: string;
  description: string;
  icon: React.ReactNode;
}

// ============================================
// STEP CONFIGURATION
// ============================================

const steps: Step[] = [
  {
    id: "role",
    title: "Choose Your Role",
    description: "Are you a farmer or a grocer?",
    icon: <User className="h-5 w-5" />,
  },
  {
    id: "business",
    title: "Business Information",
    description: "Tell us about your business",
    icon: <Building2 className="h-5 w-5" />,
  },
  {
    id: "address",
    title: "Location",
    description: "Where are you located?",
    icon: <MapPin className="h-5 w-5" />,
  },
  {
    id: "profile",
    title: "Complete Profile",
    description: "Add finishing touches",
    icon: <Check className="h-5 w-5" />,
  },
];

// ============================================
// VALIDATION SCHEMAS
// ============================================

const farmerBusinessSchema = z.object({
  farmName: z.string().min(2, "Farm name must be at least 2 characters"),
  farmDescription: z.string().min(10, "Please provide a brief description (min 10 characters)"),
  farmSize: z.string().min(1, "Please select farm size"),
  farmingType: z.array(z.string()).min(1, "Select at least one farming type"),
  yearsInOperation: z.string().min(1, "Please select years in operation"),
});

const grocerBusinessSchema = z.object({
  businessName: z.string().min(2, "Business name must be at least 2 characters"),
  businessDescription: z.string().min(10, "Please provide a brief description (min 10 characters)"),
  businessType: z.string().min(1, "Please select business type"),
  storeSize: z.string().min(1, "Please select store size"),
  weeklyBudget: z.string().min(1, "Please select weekly produce budget"),
});

const addressSchema = z.object({
  streetAddress: z.string().min(5, "Please enter a valid street address"),
  city: z.string().min(2, "Please enter a valid city"),
  state: z.string().min(2, "Please select a state"),
  zipCode: z.string().regex(/^\d{5}(-\d{4})?$/, "Please enter a valid ZIP code"),
  country: z.string().default("United States"),
  deliveryRadius: z.string().optional(),
  deliveryNotes: z.string().optional(),
});

const profileSchema = z.object({
  phone: z.string().regex(/^\+?[\d\s-()]{10,}$/, "Please enter a valid phone number"),
  website: z.string().url("Please enter a valid URL").optional().or(z.literal("")),
  profileImage: z.string().optional(),
  acceptTerms: z.boolean().refine((val) => val === true, "You must accept the terms"),
  acceptMarketing: z.boolean().optional(),
});

// Combined schema type
type OnboardingData = {
  role?: "FARMER" | "GROCER" | "ADMIN";
  // Farmer fields
  farmName?: string;
  farmDescription?: string;
  farmSize?: string;
  farmingType?: string[];
  yearsInOperation?: string;
  // Grocer fields
  businessName?: string;
  businessDescription?: string;
  businessType?: string;
  storeSize?: string;
  weeklyBudget?: string;
  // Address fields
  streetAddress?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
  deliveryRadius?: string;
  deliveryNotes?: string;
  // Profile fields
  phone?: string;
  website?: string;
  profileImage?: string;
  acceptTerms?: boolean;
  acceptMarketing?: boolean;
};

// ============================================
// ONBOARDING WIZARD COMPONENT
// ============================================

export function OnboardingWizard({ user }: OnboardingWizardProps) {
  const router = useRouter();
  const [currentStep, setCurrentStep] = React.useState(0);
  const [isSubmitting, setIsSubmitting] = React.useState(false);
  const [formData, setFormData] = React.useState<OnboardingData>({
    role: user.role,
  });

  // Get current step info
  const step = steps[currentStep]!;
  const progress = ((currentStep + 1) / steps.length) * 100;

  // Update form data
  const updateFormData = (data: Partial<OnboardingData>) => {
    setFormData((prev) => ({ ...prev, ...data }));
  };

  // Navigate to next step
  const nextStep = () => {
    if (currentStep < steps.length - 1) {
      setCurrentStep((prev) => prev + 1);
    }
  };

  // Navigate to previous step
  const prevStep = () => {
    if (currentStep > 0) {
      setCurrentStep((prev) => prev - 1);
    }
  };

  // Handle final submission
  const handleSubmit = async () => {
    setIsSubmitting(true);
    try {
      const result = await completeOnboarding(formData);
      if (result.success) {
        const redirectPath = formData.role === "FARMER" ? "/farmer" : "/grocer";
        router.push(redirectPath);
      } else {
        console.error("Onboarding failed:", result.error);
      }
    } catch (error) {
      console.error("Submission error:", error);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto">
      {/* ════════════════════════════════════════════════════════════
          PROGRESS INDICATOR
      ════════════════════════════════════════════════════════════ */}
      <div className="mb-8">
        {/* Progress Bar */}
        <div className="relative mb-8">
          <div className="h-2 bg-muted rounded-full overflow-hidden">
            <div
              className="h-full bg-primary transition-all duration-500 ease-out"
              style={{ width: `${progress}%` }}
            />
          </div>
          <p className="text-sm text-muted-foreground mt-2 text-center">
            Step {currentStep + 1} of {steps.length}
          </p>
        </div>

        {/* Step Indicators */}
        <div className="flex justify-between">
          {steps.map((s, index) => {
            const isCompleted = index < currentStep;
            const isCurrent = index === currentStep;

            return (
              <div
                key={s.id}
                className={cn(
                  "flex flex-col items-center",
                  index < steps.length - 1 && "flex-1"
                )}
              >
                {/* Step Circle */}
                <div
                  className={cn(
                    "h-10 w-10 rounded-full flex items-center justify-center border-2 transition-all duration-300",
                    isCompleted && "bg-primary border-primary text-primary-foreground",
                    isCurrent && "border-primary text-primary bg-primary/10",
                    !isCompleted && !isCurrent && "border-muted-foreground/30 text-muted-foreground/50"
                  )}
                >
                  {isCompleted ? (
                    <Check className="h-5 w-5" />
                  ) : (
                    <span className="text-sm font-medium">{index + 1}</span>
                  )}
                </div>

                {/* Step Label (hidden on mobile) */}
                <div className="hidden sm:block mt-2 text-center">
                  <p
                    className={cn(
                      "text-sm font-medium",
                      isCurrent ? "text-primary" : "text-muted-foreground"
                    )}
                  >
                    {s.title}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* ════════════════════════════════════════════════════════════
          STEP CONTENT CARD
      ════════════════════════════════════════════════════════════ */}
      <div className="bg-card border border-border rounded-2xl shadow-lg overflow-hidden">
        {/* Step Header */}
        <div className="bg-muted/30 px-6 py-4 border-b border-border">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center text-primary">
              {step.icon}
            </div>
            <div>
              <h2 className="text-xl font-semibold">{step.title}</h2>
              <p className="text-sm text-muted-foreground">{step.description}</p>
            </div>
          </div>
        </div>

        {/* Step Content */}
        <div className="p-6">
          {step.id === "role" && (
            <RoleStep
              data={formData}
              onUpdate={updateFormData}
              onNext={nextStep}
            />
          )}
          {step.id === "business" && (
            <BusinessStep
              data={formData}
              onUpdate={updateFormData}
              onNext={nextStep}
              onBack={prevStep}
            />
          )}
          {step.id === "address" && (
            <AddressStep
              data={formData}
              onUpdate={updateFormData}
              onNext={nextStep}
              onBack={prevStep}
            />
          )}
          {step.id === "profile" && (
            <ProfileStep
              data={formData}
              onUpdate={updateFormData}
              onSubmit={handleSubmit}
              onBack={prevStep}
              isSubmitting={isSubmitting}
            />
          )}
        </div>
      </div>
    </div>
  );
}

// ============================================
// STEP 1: ROLE SELECTION
// ============================================

interface StepProps {
  data: OnboardingData;
  onUpdate: (data: Partial<OnboardingData>) => void;
  onNext: () => void;
  onBack?: () => void;
}

function RoleStep({ data, onUpdate, onNext }: StepProps) {
  const [selectedRole, setSelectedRole] = React.useState<"FARMER" | "GROCER" | "ADMIN" | undefined>(
    data.role
  );

  const handleSelect = (role: "FARMER" | "GROCER") => {
    setSelectedRole(role);
    onUpdate({ role });
  };

  const handleContinue = () => {
    if (selectedRole) {
      onNext();
    }
  };

  return (
    <div className="space-y-6">
      <p className="text-muted-foreground text-center">
        Select your role to customize your experience on Farm to Grocer.
      </p>

      <div className="grid gap-4 sm:grid-cols-2">
        {/* Farmer Option */}
        <button
          onClick={() => handleSelect("FARMER")}
          className={cn(
            "relative p-6 rounded-xl border-2 text-left transition-all duration-200",
            "hover:border-green-500 hover:bg-green-50 dark:hover:bg-green-950/20",
            selectedRole === "FARMER"
              ? "border-green-500 bg-green-50 dark:bg-green-950/20 ring-2 ring-green-500/20"
              : "border-border"
          )}
        >
          {selectedRole === "FARMER" && (
            <div className="absolute top-3 right-3 h-6 w-6 rounded-full bg-green-500 flex items-center justify-center">
              <Check className="h-4 w-4 text-white" />
            </div>
          )}
          <div className="h-14 w-14 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center mb-4">
            <Leaf className="h-7 w-7 text-green-600" />
          </div>
          <h3 className="text-lg font-semibold mb-2">I'm a Farmer</h3>
          <p className="text-sm text-muted-foreground">
            Sell your fresh produce directly to local grocers and restaurants.
          </p>
          <ul className="mt-4 space-y-2 text-sm text-muted-foreground">
            <li className="flex items-center gap-2">
              <Check className="h-4 w-4 text-green-500" />
              List unlimited products
            </li>
            <li className="flex items-center gap-2">
              <Check className="h-4 w-4 text-green-500" />
              Set your own prices
            </li>
            <li className="flex items-center gap-2">
              <Check className="h-4 w-4 text-green-500" />
              Manage orders easily
            </li>
          </ul>
        </button>

        {/* Grocer Option */}
        <button
          onClick={() => handleSelect("GROCER")}
          className={cn(
            "relative p-6 rounded-xl border-2 text-left transition-all duration-200",
            "hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-blue-950/20",
            selectedRole === "GROCER"
              ? "border-blue-500 bg-blue-50 dark:bg-blue-950/20 ring-2 ring-blue-500/20"
              : "border-border"
          )}
        >
          {selectedRole === "GROCER" && (
            <div className="absolute top-3 right-3 h-6 w-6 rounded-full bg-blue-500 flex items-center justify-center">
              <Check className="h-4 w-4 text-white" />
            </div>
          )}
          <div className="h-14 w-14 rounded-full bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center mb-4">
            <Store className="h-7 w-7 text-blue-600" />
          </div>
          <h3 className="text-lg font-semibold mb-2">I'm a Grocer</h3>
          <p className="text-sm text-muted-foreground">
            Source fresh, local produce directly from farmers in your area.
          </p>
          <ul className="mt-4 space-y-2 text-sm text-muted-foreground">
            <li className="flex items-center gap-2">
              <Check className="h-4 w-4 text-blue-500" />
              Browse local farms
            </li>
            <li className="flex items-center gap-2">
              <Check className="h-4 w-4 text-blue-500" />
              Wholesale pricing
            </li>
            <li className="flex items-center gap-2">
              <Check className="h-4 w-4 text-blue-500" />
              Scheduled deliveries
            </li>
          </ul>
        </button>
      </div>

      {/* Continue Button */}
      <div className="flex justify-end pt-4">
        <Button
          onClick={handleContinue}
          disabled={!selectedRole}
          size="lg"
          className="min-w-[140px]"
        >
          Continue
          <ChevronRight className="h-4 w-4 ml-2" />
        </Button>
      </div>
    </div>
  );
}

// ============================================
// STEP 2: BUSINESS INFORMATION
// ============================================

function BusinessStep({ data, onUpdate, onNext, onBack }: StepProps) {
  const isFarmer = data.role === "FARMER";

  const schema = isFarmer ? farmerBusinessSchema : grocerBusinessSchema;

  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
    setValue,
  } = useForm({
    resolver: zodResolver(schema),
    defaultValues: isFarmer
      ? {
        farmName: data.farmName || "",
        farmDescription: data.farmDescription || "",
        farmSize: data.farmSize || "",
        farmingType: data.farmingType || [],
        yearsInOperation: data.yearsInOperation || "",
      }
      : {
        businessName: data.businessName || "",
        businessDescription: data.businessDescription || "",
        businessType: data.businessType || "",
        storeSize: data.storeSize || "",
        weeklyBudget: data.weeklyBudget || "",
      },
  });

  const farmingTypes = [
    "Vegetables",
    "Fruits",
    "Herbs",
    "Dairy",
    "Eggs",
    "Meat",
    "Grains",
    "Organic",
    "Hydroponic",
  ];

  const selectedFarmingTypes = watch("farmingType") || [];

  const toggleFarmingType = (type: string) => {
    const current = selectedFarmingTypes as string[];
    const updated = current.includes(type)
      ? current.filter((t) => t !== type)
      : [...current, type];
    setValue("farmingType", updated);
  };

  const onSubmit = (formData: any) => {
    onUpdate(formData);
    onNext();
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
      {isFarmer ? (
        // Farmer Business Form
        <>
          {/* Farm Name */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Farm Name <span className="text-destructive">*</span>
            </label>
            <input
              {...register("farmName")}
              type="text"
              placeholder="e.g., Green Valley Farm"
              className={cn(
                "w-full px-4 py-3 rounded-lg border bg-background",
                "focus:outline-none focus:ring-2 focus:ring-ring",
                errors.farmName && "border-destructive"
              )}
            />
            {errors.farmName && (
              <p className="text-sm text-destructive mt-1">{errors.farmName.message as string}</p>
            )}
          </div>

          {/* Farm Description */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Farm Description <span className="text-destructive">*</span>
            </label>
            <textarea
              {...register("farmDescription")}
              rows={3}
              placeholder="Tell grocers about your farm, growing practices, and what makes your produce special..."
              className={cn(
                "w-full px-4 py-3 rounded-lg border bg-background resize-none",
                "focus:outline-none focus:ring-2 focus:ring-ring",
                errors.farmDescription && "border-destructive"
              )}
            />
            {errors.farmDescription && (
              <p className="text-sm text-destructive mt-1">{errors.farmDescription.message as string}</p>
            )}
          </div>

          {/* Farm Size */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Farm Size <span className="text-destructive">*</span>
            </label>
            <select
              {...register("farmSize")}
              className={cn(
                "w-full px-4 py-3 rounded-lg border bg-background",
                "focus:outline-none focus:ring-2 focus:ring-ring",
                errors.farmSize && "border-destructive"
              )}
            >
              <option value="">Select farm size</option>
              <option value="small">Small (under 10 acres)</option>
              <option value="medium">Medium (10-50 acres)</option>
              <option value="large">Large (50-200 acres)</option>
              <option value="xlarge">Very Large (200+ acres)</option>
            </select>
            {errors.farmSize && (
              <p className="text-sm text-destructive mt-1">{errors.farmSize.message as string}</p>
            )}
          </div>

          {/* Farming Types */}
          <div>
            <label className="block text-sm font-medium mb-2">
              What do you grow? <span className="text-destructive">*</span>
            </label>
            <div className="flex flex-wrap gap-2">
              {farmingTypes.map((type) => (
                <button
                  key={type}
                  type="button"
                  onClick={() => toggleFarmingType(type)}
                  className={cn(
                    "px-3 py-1.5 rounded-full text-sm font-medium border transition-colors",
                    selectedFarmingTypes.includes(type)
                      ? "bg-primary text-primary-foreground border-primary"
                      : "bg-background border-border hover:border-primary"
                  )}
                >
                  {type}
                </button>
              ))}
            </div>
            {errors.farmingType && (
              <p className="text-sm text-destructive mt-1">{errors.farmingType.message as string}</p>
            )}
          </div>

          {/* Years in Operation */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Years in Operation <span className="text-destructive">*</span>
            </label>
            <select
              {...register("yearsInOperation")}
              className={cn(
                "w-full px-4 py-3 rounded-lg border bg-background",
                "focus:outline-none focus:ring-2 focus:ring-ring",
                errors.yearsInOperation && "border-destructive"
              )}
            >
              <option value="">Select years</option>
              <option value="new">Just starting</option>
              <option value="1-3">1-3 years</option>
              <option value="4-10">4-10 years</option>
              <option value="10+">10+ years</option>
            </select>
            {errors.yearsInOperation && (
              <p className="text-sm text-destructive mt-1">{errors.yearsInOperation.message as string}</p>
            )}
          </div>
        </>
      ) : (
        // Grocer Business Form
        <>
          {/* Business Name */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Business Name <span className="text-destructive">*</span>
            </label>
            <input
              {...register("businessName")}
              type="text"
              placeholder="e.g., Fresh Market Grocery"
              className={cn(
                "w-full px-4 py-3 rounded-lg border bg-background",
                "focus:outline-none focus:ring-2 focus:ring-ring",
                errors.businessName && "border-destructive"
              )}
            />
            {errors.businessName && (
              <p className="text-sm text-destructive mt-1">{errors.businessName.message as string}</p>
            )}
          </div>

          {/* Business Description */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Business Description <span className="text-destructive">*</span>
            </label>
            <textarea
              {...register("businessDescription")}
              rows={3}
              placeholder="Tell farmers about your business, what you're looking for, and your produce needs..."
              className={cn(
                "w-full px-4 py-3 rounded-lg border bg-background resize-none",
                "focus:outline-none focus:ring-2 focus:ring-ring",
                errors.businessDescription && "border-destructive"
              )}
            />
            {errors.businessDescription && (
              <p className="text-sm text-destructive mt-1">{errors.businessDescription.message as string}</p>
            )}
          </div>

          {/* Business Type */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Business Type <span className="text-destructive">*</span>
            </label>
            <select
              {...register("businessType")}
              className={cn(
                "w-full px-4 py-3 rounded-lg border bg-background",
                "focus:outline-none focus:ring-2 focus:ring-ring",
                errors.businessType && "border-destructive"
              )}
            >
              <option value="">Select business type</option>
              <option value="grocery">Grocery Store</option>
              <option value="supermarket">Supermarket</option>
              <option value="restaurant">Restaurant</option>
              <option value="cafe">Café/Coffee Shop</option>
              <option value="coop">Food Co-op</option>
              <option value="catering">Catering Company</option>
              <option value="other">Other</option>
            </select>
            {errors.businessType && (
              <p className="text-sm text-destructive mt-1">{errors.businessType.message as string}</p>
            )}
          </div>

          {/* Store Size */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Store Size <span className="text-destructive">*</span>
            </label>
            <select
              {...register("storeSize")}
              className={cn(
                "w-full px-4 py-3 rounded-lg border bg-background",
                "focus:outline-none focus:ring-2 focus:ring-ring",
                errors.storeSize && "border-destructive"
              )}
            >
              <option value="">Select store size</option>
              <option value="small">Small (under 2,000 sq ft)</option>
              <option value="medium">Medium (2,000-10,000 sq ft)</option>
              <option value="large">Large (10,000-50,000 sq ft)</option>
              <option value="xlarge">Very Large (50,000+ sq ft)</option>
            </select>
            {errors.storeSize && (
              <p className="text-sm text-destructive mt-1">{errors.storeSize.message as string}</p>
            )}
          </div>

          {/* Weekly Budget */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Weekly Produce Budget <span className="text-destructive">*</span>
            </label>
            <select
              {...register("weeklyBudget")}
              className={cn(
                "w-full px-4 py-3 rounded-lg border bg-background",
                "focus:outline-none focus:ring-2 focus:ring-ring",
                errors.weeklyBudget && "border-destructive"
              )}
            >
              <option value="">Select budget range</option>
              <option value="under500">Under $500</option>
              <option value="500-1000">$500 - $1,000</option>
              <option value="1000-5000">$1,000 - $5,000</option>
              <option value="5000-10000">$5,000 - $10,000</option>
              <option value="10000+">$10,000+</option>
            </select>
            {errors.weeklyBudget && (
              <p className="text-sm text-destructive mt-1">{errors.weeklyBudget.message as string}</p>
            )}
          </div>
        </>
      )}

      {/* Navigation Buttons */}
      <div className="flex justify-between pt-4">
        <Button type="button" variant="outline" onClick={onBack} size="lg">
          <ChevronLeft className="h-4 w-4 mr-2" />
          Back
        </Button>
        <Button type="submit" size="lg" className="min-w-[140px]">
          Continue
          <ChevronRight className="h-4 w-4 ml-2" />
        </Button>
      </div>
    </form>
  );
}

// ============================================
// STEP 3: ADDRESS
// ============================================

function AddressStep({ data, onUpdate, onNext, onBack }: StepProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(addressSchema),
    defaultValues: {
      streetAddress: data.streetAddress || "",
      city: data.city || "",
      state: data.state || "",
      zipCode: data.zipCode || "",
      country: data.country || "United States",
      deliveryRadius: data.deliveryRadius || "",
      deliveryNotes: data.deliveryNotes || "",
    },
  });

  const states = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
    "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
    "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York",
    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming",
  ];

  const onSubmit = (formData: any) => {
    onUpdate(formData);
    onNext();
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
      {/* Street Address */}
      <div>
        <label className="block text-sm font-medium mb-2">
          Street Address <span className="text-destructive">*</span>
        </label>
        <input
          {...register("streetAddress")}
          type="text"
          placeholder="123 Farm Road"
          className={cn(
            "w-full px-4 py-3 rounded-lg border bg-background",
            "focus:outline-none focus:ring-2 focus:ring-ring",
            errors.streetAddress && "border-destructive"
          )}
        />
        {errors.streetAddress && (
          <p className="text-sm text-destructive mt-1">{errors.streetAddress.message as string}</p>
        )}
      </div>

      {/* City & State */}
      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="block text-sm font-medium mb-2">
            City <span className="text-destructive">*</span>
          </label>
          <input
            {...register("city")}
            type="text"
            placeholder="Springfield"
            className={cn(
              "w-full px-4 py-3 rounded-lg border bg-background",
              "focus:outline-none focus:ring-2 focus:ring-ring",
              errors.city && "border-destructive"
            )}
          />
          {errors.city && (
            <p className="text-sm text-destructive mt-1">{errors.city.message as string}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium mb-2">
            State <span className="text-destructive">*</span>
          </label>
          <select
            {...register("state")}
            className={cn(
              "w-full px-4 py-3 rounded-lg border bg-background",
              "focus:outline-none focus:ring-2 focus:ring-ring",
              errors.state && "border-destructive"
            )}
          >
            <option value="">Select state</option>
            {states.map((state) => (
              <option key={state} value={state}>
                {state}
              </option>
            ))}
          </select>
          {errors.state && (
            <p className="text-sm text-destructive mt-1">{errors.state.message as string}</p>
          )}
        </div>
      </div>

      {/* ZIP Code */}
      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="block text-sm font-medium mb-2">
            ZIP Code <span className="text-destructive">*</span>
          </label>
          <input
            {...register("zipCode")}
            type="text"
            placeholder="12345"
            className={cn(
              "w-full px-4 py-3 rounded-lg border bg-background",
              "focus:outline-none focus:ring-2 focus:ring-ring",
              errors.zipCode && "border-destructive"
            )}
          />
          {errors.zipCode && (
            <p className="text-sm text-destructive mt-1">{errors.zipCode.message as string}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium mb-2">
            Delivery Radius
          </label>
          <select
            {...register("deliveryRadius")}
            className="w-full px-4 py-3 rounded-lg border bg-background focus:outline-none focus:ring-2 focus:ring-ring"
          >
            <option value="">Select radius</option>
            <option value="10">Within 10 miles</option>
            <option value="25">Within 25 miles</option>
            <option value="50">Within 50 miles</option>
            <option value="100">Within 100 miles</option>
            <option value="unlimited">No limit</option>
          </select>
        </div>
      </div>

      {/* Delivery Notes */}
      <div>
        <label className="block text-sm font-medium mb-2">
          Delivery Notes (Optional)
        </label>
        <textarea
          {...register("deliveryNotes")}
          rows={2}
          placeholder="Any special instructions for deliveries..."
          className="w-full px-4 py-3 rounded-lg border bg-background resize-none focus:outline-none focus:ring-2 focus:ring-ring"
        />
      </div>

      {/* Navigation Buttons */}
      <div className="flex justify-between pt-4">
        <Button type="button" variant="outline" onClick={onBack} size="lg">
          <ChevronLeft className="h-4 w-4 mr-2" />
          Back
        </Button>
        <Button type="submit" size="lg" className="min-w-[140px]">
          Continue
          <ChevronRight className="h-4 w-4 ml-2" />
        </Button>
      </div>
    </form>
  );
}

// ============================================
// STEP 4: PROFILE COMPLETION
// ============================================

interface ProfileStepProps extends Omit<StepProps, "onNext"> {
  onSubmit: () => void;
  isSubmitting: boolean;
}

function ProfileStep({ data, onUpdate, onSubmit, onBack, isSubmitting }: ProfileStepProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(profileSchema),
    defaultValues: {
      phone: data.phone || "",
      website: data.website || "",
      profileImage: data.profileImage || "",
      acceptTerms: data.acceptTerms || false,
      acceptMarketing: data.acceptMarketing || false,
    },
  });

  const handleFormSubmit = (formData: any) => {
    onUpdate(formData);
    onSubmit();
  };

  return (
    <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-6">
      {/* Phone Number */}
      <div>
        <label className="block text-sm font-medium mb-2">
          Phone Number <span className="text-destructive">*</span>
        </label>
        <div className="relative">
          <Phone className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
          <input
            {...register("phone")}
            type="tel"
            placeholder="(555) 123-4567"
            className={cn(
              "w-full pl-10 pr-4 py-3 rounded-lg border bg-background",
              "focus:outline-none focus:ring-2 focus:ring-ring",
              errors.phone && "border-destructive"
            )}
          />
        </div>
        {errors.phone && (
          <p className="text-sm text-destructive mt-1">{errors.phone.message as string}</p>
        )}
      </div>

      {/* Website */}
      <div>
        <label className="block text-sm font-medium mb-2">
          Website (Optional)
        </label>
        <div className="relative">
          <Globe className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
          <input
            {...register("website")}
            type="url"
            placeholder="https://www.yourfarm.com"
            className={cn(
              "w-full pl-10 pr-4 py-3 rounded-lg border bg-background",
              "focus:outline-none focus:ring-2 focus:ring-ring",
              errors.website && "border-destructive"
            )}
          />
        </div>
        {errors.website && (
          <p className="text-sm text-destructive mt-1">{errors.website.message as string}</p>
        )}
      </div>

      {/* Profile Image Upload Placeholder */}
      <div>
        <label className="block text-sm font-medium mb-2">
          Profile Photo (Optional)
        </label>
        <div className="flex items-center gap-4">
          <div className="h-20 w-20 rounded-full bg-muted flex items-center justify-center border-2 border-dashed border-border">
            <Camera className="h-8 w-8 text-muted-foreground" />
          </div>
          <div>
            <Button type="button" variant="outline" size="sm">
              <Upload className="h-4 w-4 mr-2" />
              Upload Photo
            </Button>
            <p className="text-xs text-muted-foreground mt-1">
              JPG, PNG or GIF. Max 2MB.
            </p>
          </div>
        </div>
      </div>

      {/* Terms & Conditions */}
      <div className="space-y-4 pt-4 border-t border-border">
        <div className="flex items-start gap-3">
          <input
            {...register("acceptTerms")}
            type="checkbox"
            id="acceptTerms"
            className="mt-1 h-4 w-4 rounded border-border text-primary focus:ring-primary"
          />
          <label htmlFor="acceptTerms" className="text-sm">
            I agree to the{" "}
            <a href="/terms" className="text-primary hover:underline" target="_blank">
              Terms of Service
            </a>{" "}
            and{" "}
            <a href="/privacy" className="text-primary hover:underline" target="_blank">
              Privacy Policy
            </a>{" "}
            <span className="text-destructive">*</span>
          </label>
        </div>
        {errors.acceptTerms && (
          <p className="text-sm text-destructive">{errors.acceptTerms.message as string}</p>
        )}

        <div className="flex items-start gap-3">
          <input
            {...register("acceptMarketing")}
            type="checkbox"
            id="acceptMarketing"
            className="mt-1 h-4 w-4 rounded border-border text-primary focus:ring-primary"
          />
          <label htmlFor="acceptMarketing" className="text-sm text-muted-foreground">
            I'd like to receive updates, tips, and promotional emails from Farm to Grocer.
          </label>
        </div>
      </div>

      {/* Navigation Buttons */}
      <div className="flex justify-between pt-4">
        <Button type="button" variant="outline" onClick={onBack} size="lg" disabled={isSubmitting}>
          <ChevronLeft className="h-4 w-4 mr-2" />
          Back
        </Button>
        <Button type="submit" size="lg" className="min-w-[180px]" disabled={isSubmitting}>
          {isSubmitting ? (
            <>
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              Completing...
            </>
          ) : (
            <>
              Complete Setup
              <Check className="h-4 w-4 ml-2" />
            </>
          )}
        </Button>
      </div>
    </form>
  );
}

// ============================================
// EXPORTS
// ============================================

export default OnboardingWizard;
