// Farm-to-Grocer MVP - Single Order API Route
// Path: app/api/orders/[id]/route.ts
// Generated by RJBot Orchestrator
//
// RESTful API for single order operations:
// GET: Fetch single order by ID (authenticated, role-based access)
// PUT: Update order details (grocer only, limited fields)
// PATCH: Update order status (farmer/grocer based on status)
// DELETE: Cancel order (grocer only, limited window)

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import prisma, {
  isPrismaError,
  getPrismaErrorMessage,
  withTransaction,
} from "@/lib/prisma";
import { getSession, requireAuth } from "@/lib/auth";
import {
  OrderStatus,
  PaymentStatus,
  DeliveryMethod,
  NotificationType,
  type ApiResponse,
  type OrderWithDetails,
} from "@/types";

// ============================================
// ROUTE CONTEXT TYPE
// ============================================

interface RouteContext {
  params: {
    id: string;
  };
}

// ============================================
// CONSTANTS
// ============================================

/**
 * Valid status transitions per role
 * Key: current status, Value: allowed next statuses
 */
const FARMER_STATUS_TRANSITIONS: Record<OrderStatus, OrderStatus[]> = {
  [OrderStatus.PENDING]: [OrderStatus.CONFIRMED, OrderStatus.CANCELLED],
  [OrderStatus.CONFIRMED]: [OrderStatus.PROCESSING],
  [OrderStatus.PROCESSING]: [OrderStatus.READY_FOR_PICKUP, OrderStatus.OUT_FOR_DELIVERY],
  [OrderStatus.READY_FOR_PICKUP]: [OrderStatus.DELIVERED],
  [OrderStatus.OUT_FOR_DELIVERY]: [OrderStatus.DELIVERED],
  [OrderStatus.DELIVERED]: [],
  [OrderStatus.CANCELLED]: [],
  [OrderStatus.REFUNDED]: [],
};

const GROCER_STATUS_TRANSITIONS: Record<OrderStatus, OrderStatus[]> = {
  [OrderStatus.PENDING]: [OrderStatus.CANCELLED],
  [OrderStatus.CONFIRMED]: [OrderStatus.CANCELLED],
  [OrderStatus.PROCESSING]: [],
  [OrderStatus.READY_FOR_PICKUP]: [OrderStatus.DELIVERED],
  [OrderStatus.OUT_FOR_DELIVERY]: [],
  [OrderStatus.DELIVERED]: [],
  [OrderStatus.CANCELLED]: [],
  [OrderStatus.REFUNDED]: [],
};

const ADMIN_STATUS_TRANSITIONS: Record<OrderStatus, OrderStatus[]> = {
  [OrderStatus.PENDING]: [OrderStatus.CONFIRMED, OrderStatus.CANCELLED, OrderStatus.REFUNDED],
  [OrderStatus.CONFIRMED]: [OrderStatus.PROCESSING, OrderStatus.CANCELLED, OrderStatus.REFUNDED],
  [OrderStatus.PROCESSING]: [OrderStatus.READY_FOR_PICKUP, OrderStatus.OUT_FOR_DELIVERY, OrderStatus.CANCELLED, OrderStatus.REFUNDED],
  [OrderStatus.READY_FOR_PICKUP]: [OrderStatus.DELIVERED, OrderStatus.CANCELLED, OrderStatus.REFUNDED],
  [OrderStatus.OUT_FOR_DELIVERY]: [OrderStatus.DELIVERED, OrderStatus.CANCELLED, OrderStatus.REFUNDED],
  [OrderStatus.DELIVERED]: [OrderStatus.REFUNDED],
  [OrderStatus.CANCELLED]: [OrderStatus.REFUNDED],
  [OrderStatus.REFUNDED]: [],
};

/**
 * Cancellation window in hours
 */
const CANCELLATION_WINDOW_HOURS = 24;

// ============================================
// VALIDATION SCHEMAS
// ============================================

/**
 * Schema for updating order (grocer only)
 */
const updateOrderSchema = z.object({
  deliveryAddress: z
    .string()
    .max(500, "Delivery address must be less than 500 characters")
    .optional(),
  deliveryDate: z
    .string()
    .datetime()
    .optional()
    .nullable()
    .transform((val) => (val ? new Date(val) : null)),
  notes: z
    .string()
    .max(1000, "Notes must be less than 1000 characters")
    .optional()
    .nullable(),
});

/**
 * Schema for status update (PATCH)
 */
const statusUpdateSchema = z.object({
  status: z.nativeEnum(OrderStatus, {
    errorMap: () => ({ message: "Invalid order status" }),
  }),
  reason: z
    .string()
    .max(500, "Reason must be less than 500 characters")
    .optional(),
  trackingNumber: z
    .string()
    .max(100, "Tracking number must be less than 100 characters")
    .optional(),
  estimatedDelivery: z
    .string()
    .datetime()
    .optional()
    .nullable()
    .transform((val) => (val ? new Date(val) : null)),
});

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Validate order ID format
 */
function isValidOrderId(id: string): boolean {
  return /^c[a-z0-9]{24}$/.test(id) || /^[a-z0-9]{25}$/.test(id);
}

/**
 * Check if user has access to order
 */
function hasOrderAccess(
  order: { farmerId: string; grocerId: string },
  user: { role: string; farmerId?: string; grocerId?: string }
): boolean {
  if (user.role === "ADMIN") return true;
  if (user.role === "FARMER" && user.farmerId === order.farmerId) return true;
  if (user.role === "GROCER" && user.grocerId === order.grocerId) return true;
  return false;
}

/**
 * Get allowed status transitions for user role
 */
function getAllowedTransitions(
  currentStatus: OrderStatus,
  role: string
): OrderStatus[] {
  switch (role) {
    case "ADMIN":
      return ADMIN_STATUS_TRANSITIONS[currentStatus] || [];
    case "FARMER":
      return FARMER_STATUS_TRANSITIONS[currentStatus] || [];
    case "GROCER":
      return GROCER_STATUS_TRANSITIONS[currentStatus] || [];
    default:
      return [];
  }
}

/**
 * Check if order can be cancelled
 */
function canCancelOrder(order: { createdAt: Date; status: OrderStatus }): {
  canCancel: boolean;
  reason?: string;
} {
  // Check status
  const cancellableStatuses = [OrderStatus.PENDING, OrderStatus.CONFIRMED];
  if (!cancellableStatuses.includes(order.status)) {
    return {
      canCancel: false,
      reason: `Orders with status "${order.status}" cannot be cancelled`,
    };
  }

  // Check time window
  const hoursSinceCreation =
    (Date.now() - new Date(order.createdAt).getTime()) / (1000 * 60 * 60);
  if (hoursSinceCreation > CANCELLATION_WINDOW_HOURS) {
    return {
      canCancel: false,
      reason: `Cancellation window of ${CANCELLATION_WINDOW_HOURS} hours has passed`,
    };
  }

  return { canCancel: true };
}

/**
 * Create standardized API response
 */
function createResponse<T>(
  data: T,
  status: number = 200
): NextResponse<ApiResponse<T>> {
  return NextResponse.json(
    {
      success: true,
      data,
    },
    { status }
  );
}

/**
 * Create error response
 */
function createErrorResponse(
  message: string,
  code: string,
  status: number = 400,
  details?: Record<string, string[]>
): NextResponse<ApiResponse<never>> {
  return NextResponse.json(
    {
      success: false,
      error: {
        code,
        message,
        details,
      },
    },
    { status }
  );
}

// ============================================
// GET /api/orders/[id]
// Fetch single order by ID (authenticated)
// ============================================

export async function GET(
  request: NextRequest,
  { params }: RouteContext
): Promise<NextResponse<ApiResponse<OrderWithDetails>>> {
  try {
    const { id } = params;

    // Validate ID format
    if (!id || !isValidOrderId(id)) {
      return createErrorResponse(
        "Invalid order ID format",
        "INVALID_ID",
        400
      );
    }

    // Authenticate user
    const session = await getSession();
    if (!session?.user) {
      return createErrorResponse(
        "Authentication required",
        "UNAUTHORIZED",
        401
      );
    }

    const { user } = session;

    // Fetch order with all details
    const order = await prisma.order.findUnique({
      where: { id },
      include: {
        items: {
          include: {
            product: {
              select: {
                id: true,
                name: true,
                images: true,
                unit: true,
                category: true,
              },
            },
          },
        },
        farmer: {
          include: {
            user: {
              select: {
                id: true,
                name: true,
                email: true,
                phone: true,
                image: true,
              },
            },
          },
        },
        grocer: {
          include: {
            user: {
              select: {
                id: true,
                name: true,
                email: true,
                phone: true,
                image: true,
              },
            },
          },
        },
        payment: true,
        statusHistory: {
          orderBy: { createdAt: "desc" },
          take: 10,
        },
      },
    });

    // Check if order exists
    if (!order) {
      return createErrorResponse(
        "Order not found",
        "NOT_FOUND",
        404
      );
    }

    // Check access permission
    if (!hasOrderAccess(order, user)) {
      return createErrorResponse(
        "You don't have permission to view this order",
        "FORBIDDEN",
        403
      );
    }

    // Add computed fields
    const enrichedOrder = {
      ...order,
      canCancel: canCancelOrder(order).canCancel,
      allowedStatusTransitions: getAllowedTransitions(order.status, user.role),
    };

    return createResponse(enrichedOrder as OrderWithDetails);
  } catch (error) {
    console.error("GET /api/orders/[id] error:", error);

    if (isPrismaError(error)) {
      return createErrorResponse(
        getPrismaErrorMessage(error),
        "DATABASE_ERROR",
        500
      );
    }

    return createErrorResponse(
      "An unexpected error occurred",
      "INTERNAL_ERROR",
      500
    );
  }
}

// ============================================
// PUT /api/orders/[id]
// Update order details (grocer only)
// ============================================

export async function PUT(
  request: NextRequest,
  { params }: RouteContext
): Promise<NextResponse<ApiResponse<OrderWithDetails>>> {
  try {
    const { id } = params;

    // Validate ID format
    if (!id || !isValidOrderId(id)) {
      return createErrorResponse(
        "Invalid order ID format",
        "INVALID_ID",
        400
      );
    }

    // Authenticate user
    const session = await getSession();
    if (!session?.user) {
      return createErrorResponse(
        "Authentication required",
        "UNAUTHORIZED",
        401
      );
    }

    const { user } = session;

    // Only grocers can update order details
    if (user.role !== "GROCER" && user.role !== "ADMIN") {
      return createErrorResponse(
        "Only grocers can update order details",
        "FORBIDDEN",
        403
      );
    }

    // Fetch existing order
    const existingOrder = await prisma.order.findUnique({
      where: { id },
      select: {
        id: true,
        grocerId: true,
        status: true,
      },
    });

    if (!existingOrder) {
      return createErrorResponse(
        "Order not found",
        "NOT_FOUND",
        404
      );
    }

    // Check ownership (grocer only)
    if (user.role === "GROCER" && existingOrder.grocerId !== user.grocerId) {
      return createErrorResponse(
        "You don't have permission to update this order",
        "FORBIDDEN",
        403
      );
    }

    // Check if order can be modified
    const nonModifiableStatuses = [
      OrderStatus.DELIVERED,
      OrderStatus.CANCELLED,
      OrderStatus.REFUNDED,
    ];
    if (nonModifiableStatuses.includes(existingOrder.status)) {
      return createErrorResponse(
        `Orders with status "${existingOrder.status}" cannot be modified`,
        "ORDER_NOT_MODIFIABLE",
        400
      );
    }

    // Parse request body
    let body;
    try {
      body = await request.json();
    } catch (error) {
      return createErrorResponse(
        "Invalid JSON in request body",
        "INVALID_INPUT",
        400
      );
    }

    // Validate input
    const validationResult = updateOrderSchema.safeParse(body);

    if (!validationResult.success) {
      return createErrorResponse(
        "Validation failed",
        "VALIDATION_ERROR",
        400,
        validationResult.error.flatten().fieldErrors as Record<string, string[]>
      );
    }

    const data = validationResult.data;

    // Update order
    const updatedOrder = await prisma.order.update({
      where: { id },
      data: {
        ...data,
        updatedAt: new Date(),
      },
      include: {
        items: {
          include: {
            product: {
              select: {
                id: true,
                name: true,
                images: true,
                unit: true,
              },
            },
          },
        },
        farmer: {
          include: {
            user: {
              select: {
                name: true,
                email: true,
                phone: true,
              },
            },
          },
        },
        grocer: {
          include: {
            user: {
              select: {
                name: true,
                email: true,
                phone: true,
              },
            },
          },
        },
      },
    });

    console.log(`✅ Order updated: ${id} by ${user.role} ${user.id}`);

    return createResponse(updatedOrder as OrderWithDetails);
  } catch (error) {
    console.error("PUT /api/orders/[id] error:", error);

    if (isPrismaError(error)) {
      return createErrorResponse(
        getPrismaErrorMessage(error),
        "DATABASE_ERROR",
        500
      );
    }

    return createErrorResponse(
      "An unexpected error occurred",
      "INTERNAL_ERROR",
      500
    );
  }
}

// ============================================
// PATCH /api/orders/[id]
// Update order status (role-based)
// ============================================

export async function PATCH(
  request: NextRequest,
  { params }: RouteContext
): Promise<NextResponse<ApiResponse<OrderWithDetails>>> {
  try {
    const { id } = params;

    // Validate ID format
    if (!id || !isValidOrderId(id)) {
      return createErrorResponse(
        "Invalid order ID format",
        "INVALID_ID",
        400
      );
    }

    // Authenticate user
    const session = await getSession();
    if (!session?.user) {
      return createErrorResponse(
        "Authentication required",
        "UNAUTHORIZED",
        401
      );
    }

    const { user } = session;

    // Fetch existing order
    const existingOrder = await prisma.order.findUnique({
      where: { id },
      include: {
        farmer: {
          include: {
            user: {
              select: { id: true, name: true },
            },
          },
        },
        grocer: {
          include: {
            user: {
              select: { id: true, name: true },
            },
          },
        },
        items: true,
      },
    });

    if (!existingOrder) {
      return createErrorResponse(
        "Order not found",
        "NOT_FOUND",
        404
      );
    }

    // Check access permission
    if (!hasOrderAccess(existingOrder, user)) {
      return createErrorResponse(
        "You don't have permission to update this order",
        "FORBIDDEN",
        403
      );
    }

    // Parse request body
    let body;
    try {
      body = await request.json();
    } catch (error) {
      return createErrorResponse(
        "Invalid JSON in request body",
        "INVALID_INPUT",
        400
      );
    }

    // Validate input
    const validationResult = statusUpdateSchema.safeParse(body);

    if (!validationResult.success) {
      return createErrorResponse(
        "Validation failed",
        "VALIDATION_ERROR",
        400,
        validationResult.error.flatten().fieldErrors as Record<string, string[]>
      );
    }

    const { status: newStatus, reason, trackingNumber, estimatedDelivery } = validationResult.data;

    // Check if status transition is allowed
    const allowedTransitions = getAllowedTransitions(existingOrder.status, user.role);
    if (!allowedTransitions.includes(newStatus)) {
      return createErrorResponse(
        `Cannot transition from "${existingOrder.status}" to "${newStatus}" with your role`,
        "INVALID_STATUS_TRANSITION",
        400
      );
    }

    // Special handling for cancellation
    if (newStatus === OrderStatus.CANCELLED) {
      const cancelCheck = canCancelOrder(existingOrder);
      if (!cancelCheck.canCancel) {
        return createErrorResponse(
          cancelCheck.reason || "Order cannot be cancelled",
          "CANCELLATION_NOT_ALLOWED",
          400
        );
      }
    }

    // Update order with transaction
    const updatedOrder = await withTransaction(async (tx) => {
      // Update order status
      const order = await tx.order.update({
        where: { id },
        data: {
          status: newStatus,
          trackingNumber: trackingNumber || undefined,
          estimatedDelivery: estimatedDelivery || undefined,
          updatedAt: new Date(),
          // Set delivery date if delivered
          ...(newStatus === OrderStatus.DELIVERED && {
            deliveredAt: new Date(),
          }),
          // Set cancellation date if cancelled
          ...(newStatus === OrderStatus.CANCELLED && {
            cancelledAt: new Date(),
            cancellationReason: reason,
          }),
        },
        include: {
          items: {
            include: {
              product: {
                select: {
                  id: true,
                  name: true,
                  images: true,
                  unit: true,
                },
              },
            },
          },
          farmer: {
            include: {
              user: {
                select: {
                  id: true,
                  name: true,
                  email: true,
                  phone: true,
                },
              },
            },
          },
          grocer: {
            include: {
              user: {
                select: {
                  id: true,
                  name: true,
                  email: true,
                  phone: true,
                },
              },
            },
          },
        },
      });

      // Create status history entry
      await tx.orderStatusHistory.create({
        data: {
          orderId: id,
          status: newStatus,
          previousStatus: existingOrder.status,
          changedBy: user.id,
          reason: reason,
        },
      });

      // Handle inventory restoration on cancellation
      if (newStatus === OrderStatus.CANCELLED) {
        for (const item of existingOrder.items) {
          await tx.product.update({
            where: { id: item.productId },
            data: {
              availableQty: {
                increment: item.quantity,
              },
            },
          });
        }
      }

      // Create notifications
      const notificationUserId =
        user.role === "FARMER"
          ? order.grocer.user.id
          : order.farmer.user.id;

      const statusMessages: Record<OrderStatus, string> = {
        [OrderStatus.CONFIRMED]: `Your order #${order.orderNumber} has been confirmed!`,
        [OrderStatus.PROCESSING]: `Your order #${order.orderNumber} is being prepared.`,
        [OrderStatus.READY_FOR_PICKUP]: `Your order #${order.orderNumber} is ready for pickup!`,
        [OrderStatus.OUT_FOR_DELIVERY]: `Your order #${order.orderNumber} is out for delivery!`,
        [OrderStatus.DELIVERED]: `Your order #${order.orderNumber} has been delivered!`,
        [OrderStatus.CANCELLED]: `Your order #${order.orderNumber} has been cancelled.`,
        [OrderStatus.REFUNDED]: `Your order #${order.orderNumber} has been refunded.`,
        [OrderStatus.PENDING]: "",
      };

      if (statusMessages[newStatus]) {
        await tx.notification.create({
          data: {
            userId: notificationUserId,
            type: NotificationType.ORDER_STATUS_CHANGED,
            title: `Order ${newStatus.replace("_", " ")}`,
            message: statusMessages[newStatus],
            link: `/orders/${order.id}`,
          },
        });
      }

      return order;
    });

    console.log(
      `✅ Order status updated: ${id} from ${existingOrder.status} to ${newStatus} by ${user.role} ${user.id}`
    );

    return createResponse(updatedOrder as OrderWithDetails);
  } catch (error) {
    console.error("PATCH /api/orders/[id] error:", error);

    if (isPrismaError(error)) {
      return createErrorResponse(
        getPrismaErrorMessage(error),
        "DATABASE_ERROR",
        500
      );
    }

    return createErrorResponse(
      "An unexpected error occurred",
      "INTERNAL_ERROR",
      500
    );
  }
}

// ============================================
// DELETE /api/orders/[id]
// Cancel order (grocer only, limited window)
// ============================================

export async function DELETE(
  request: NextRequest,
  { params }: RouteContext
): Promise<NextResponse<ApiResponse<{ cancelled: boolean; id: string }>>> {
  try {
    const { id } = params;

    // Validate ID format
    if (!id || !isValidOrderId(id)) {
      return createErrorResponse(
        "Invalid order ID format",
        "INVALID_ID",
        400
      );
    }

    // Authenticate user
    const session = await getSession();
    if (!session?.user) {
      return createErrorResponse(
        "Authentication required",
        "UNAUTHORIZED",
        401
      );
    }

    const { user } = session;

    // Only grocers and admins can cancel via DELETE
    if (user.role !== "GROCER" && user.role !== "ADMIN") {
      return createErrorResponse(
        "Only grocers can cancel orders",
        "FORBIDDEN",
        403
      );
    }

    // Fetch existing order
    const existingOrder = await prisma.order.findUnique({
      where: { id },
      include: {
        items: true,
        farmer: {
          include: {
            user: {
              select: { id: true },
            },
          },
        },
      },
    });

    if (!existingOrder) {
      return createErrorResponse(
        "Order not found",
        "NOT_FOUND",
        404
      );
    }

    // Check ownership
    if (user.role === "GROCER" && existingOrder.grocerId !== user.grocerId) {
      return createErrorResponse(
        "You don't have permission to cancel this order",
        "FORBIDDEN",
        403
      );
    }

    // Check if order can be cancelled
    const cancelCheck = canCancelOrder(existingOrder);
    if (!cancelCheck.canCancel) {
      return createErrorResponse(
        cancelCheck.reason || "Order cannot be cancelled",
        "CANCELLATION_NOT_ALLOWED",
        400
      );
    }

    // Get cancellation reason from query params
    const { searchParams } = new URL(request.url);
    const reason = searchParams.get("reason") || "Cancelled by customer";

    // Cancel order with transaction
    await withTransaction(async (tx) => {
      // Update order status
      await tx.order.update({
        where: { id },
        data: {
          status: OrderStatus.CANCELLED,
          cancelledAt: new Date(),
          cancellationReason: reason,
          updatedAt: new Date(),
        },
      });

      // Create status history entry
      await tx.orderStatusHistory.create({
        data: {
          orderId: id,
          status: OrderStatus.CANCELLED,
          previousStatus: existingOrder.status,
          changedBy: user.id,
          reason: reason,
        },
      });

      // Restore inventory
      for (const item of existingOrder.items) {
        await tx.product.update({
          where: { id: item.productId },
          data: {
            availableQty: {
              increment: item.quantity,
            },
          },
        });
      }

      // Notify farmer
      await tx.notification.create({
        data: {
          userId: existingOrder.farmer.user.id,
          type: NotificationType.ORDER_CANCELLED,
          title: "Order Cancelled",
          message: `Order #${existingOrder.orderNumber} has been cancelled. Reason: ${reason}`,
          link: `/farmer/orders/${id}`,
        },
      });
    });

    console.log(`🚫 Order cancelled: ${id} by ${user.role} ${user.id}`);

    return createResponse({
      cancelled: true,
      id,
    });
  } catch (error) {
    console.error("DELETE /api/orders/[id] error:", error);

    if (isPrismaError(error)) {
      return createErrorResponse(
        getPrismaErrorMessage(error),
        "DATABASE_ERROR",
        500
      );
    }

    return createErrorResponse(
      "An unexpected error occurred",
      "INTERNAL_ERROR",
      500
    );
  }
}

// ============================================
// OPTIONS /api/orders/[id]
// CORS preflight handler
// ============================================

export async function OPTIONS(request: NextRequest) {
  return new NextResponse(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, PUT, PATCH, DELETE, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
      "Access-Control-Max-Age": "86400",
    },
  });
}

// ============================================
// ROUTE SEGMENT CONFIG
// ============================================

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const maxDuration = 60;
