// Farm-to-Grocer MVP - Product Card Component
// Path: components/ProductCard.tsx
// Generated by RJBot Orchestrator
//
// A versatile product card component for displaying farm products with:
// - Multiple layout variants (grid, list, compact)
// - Add to cart functionality
// - Quantity selector
// - Organic/certification badges
// - Farmer info display
// - Responsive design
// - Loading skeleton state

"use client";

import * as React from "react";
import Link from "next/link";
import Image from "next/image";
import { cva, type VariantProps } from "class-variance-authority";
import {
  ShoppingCart,
  Plus,
  Minus,
  Heart,
  Leaf,
  MapPin,
  Star,
  Package,
  Clock,
  Check,
  AlertCircle,
} from "lucide-react";
import { cn, formatCurrency } from "@/lib/utils";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardFooter } from "@/components/ui/Card";
import {
  Product,
  ProductCategory,
  ProductUnit,
  ProductCategoryLabels,
  ProductUnitLabels,
} from "@/types";

// ============================================
// PRODUCT CARD VARIANTS
// ============================================

const productCardVariants = cva(
  "group relative overflow-hidden transition-all duration-300",
  {
    variants: {
      variant: {
        grid: "flex flex-col",
        list: "flex flex-row gap-4",
        compact: "flex flex-row gap-3 p-3",
      },
      interactive: {
        true: "cursor-pointer hover:shadow-lg hover:-translate-y-1 hover:border-primary/30",
        false: "",
      },
    },
    defaultVariants: {
      variant: "grid",
      interactive: true,
    },
  }
);

// ============================================
// TYPES & INTERFACES
// ============================================

export interface ProductCardProduct {
  id: string;
  name: string;
  description?: string | null;
  category: ProductCategory;
  unit: ProductUnit;
  pricePerUnit: number;
  minOrderQty: number;
  maxOrderQty?: number | null;
  availableQty: number;
  images: string[];
  isOrganic: boolean;
  harvestDate?: Date | null;
  tags?: string[];
  farmer?: {
    id: string;
    farmName: string;
    city: string;
    state: string;
    rating?: number;
    isVerified?: boolean;
  };
}

export interface ProductCardProps
  extends VariantProps<typeof productCardVariants> {
  /**
   * Product data to display
   */
  product: ProductCardProduct;

  /**
   * Callback when add to cart is clicked
   */
  onAddToCart?: (product: ProductCardProduct, quantity: number) => void;

  /**
   * Callback when favorite is toggled
   */
  onToggleFavorite?: (productId: string) => void;

  /**
   * Whether product is in favorites
   */
  isFavorite?: boolean;

  /**
   * Show quantity selector
   */
  showQuantitySelector?: boolean;

  /**
   * Show farmer info
   */
  showFarmerInfo?: boolean;

  /**
   * Show quick add button (single click add)
   */
  showQuickAdd?: boolean;

  /**
   * Custom className
   */
  className?: string;

  /**
   * Loading state
   */
  isLoading?: boolean;

  /**
   * Disable interactions
   */
  disabled?: boolean;
}

// ============================================
// PRODUCT CARD COMPONENT
// ============================================

export function ProductCard({
  product,
  variant = "grid",
  interactive = true,
  onAddToCart,
  onToggleFavorite,
  isFavorite = false,
  showQuantitySelector = true,
  showFarmerInfo = true,
  showQuickAdd = false,
  className,
  isLoading = false,
  disabled = false,
}: ProductCardProps) {
  const [quantity, setQuantity] = React.useState(product.minOrderQty || 1);
  const [isAdding, setIsAdding] = React.useState(false);
  const [justAdded, setJustAdded] = React.useState(false);

  // Calculate stock status
  const isOutOfStock = product.availableQty <= 0;
  const isLowStock = product.availableQty > 0 && product.availableQty < 10;

  // Get primary image
  const primaryImage = product.images?.[0] || "/images/placeholder-product.jpg";

  // Handle quantity change
  const handleQuantityChange = (delta: number) => {
    const newQty = quantity + delta;
    const minQty = product.minOrderQty || 1;
    const maxQty = product.maxOrderQty || product.availableQty;

    if (newQty >= minQty && newQty <= maxQty) {
      setQuantity(newQty);
    }
  };

  // Handle add to cart
  const handleAddToCart = async (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();

    if (isOutOfStock || disabled || isAdding) return;

    setIsAdding(true);
    try {
      await onAddToCart?.(product, quantity);
      setJustAdded(true);
      setTimeout(() => setJustAdded(false), 2000);
    } finally {
      setIsAdding(false);
    }
  };

  // Handle quick add (single click, minimum quantity)
  const handleQuickAdd = async (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();

    if (isOutOfStock || disabled || isAdding) return;

    setIsAdding(true);
    try {
      await onAddToCart?.(product, product.minOrderQty || 1);
      setJustAdded(true);
      setTimeout(() => setJustAdded(false), 2000);
    } finally {
      setIsAdding(false);
    }
  };

  // Handle favorite toggle
  const handleToggleFavorite = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    onToggleFavorite?.(product.id);
  };

  // Loading skeleton
  if (isLoading) {
    return <ProductCardSkeleton variant={variant} className={className} />;
  }

  // Render based on variant
  if (variant === "compact") {
    return (
      <CompactProductCard
        product={product}
        quantity={quantity}
        onQuantityChange={handleQuantityChange}
        onAddToCart={handleAddToCart}
        isAdding={isAdding}
        justAdded={justAdded}
        isOutOfStock={isOutOfStock}
        disabled={disabled}
        className={className}
      />
    );
  }

  if (variant === "list") {
    return (
      <ListProductCard
        product={product}
        quantity={quantity}
        onQuantityChange={handleQuantityChange}
        onAddToCart={handleAddToCart}
        onToggleFavorite={handleToggleFavorite}
        isFavorite={isFavorite}
        isAdding={isAdding}
        justAdded={justAdded}
        isOutOfStock={isOutOfStock}
        isLowStock={isLowStock}
        showFarmerInfo={showFarmerInfo}
        showQuantitySelector={showQuantitySelector}
        disabled={disabled}
        interactive={interactive}
        className={className}
      />
    );
  }

  // Default: Grid variant
  return (
    <Card
      className={cn(
        productCardVariants({ variant, interactive: interactive && !disabled }),
        isOutOfStock && "opacity-75",
        className
      )}
    >
      {/* Product Image */}
      <Link href={`/products/${product.id}`} className="block">
        <div className="relative aspect-square overflow-hidden rounded-t-lg bg-muted">
          <Image
            src={primaryImage}
            alt={product.name}
            fill
            className="object-cover transition-transform duration-300 group-hover:scale-105"
            sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw"
          />

          {/* Badges */}
          <div className="absolute top-2 left-2 flex flex-col gap-1">
            {product.isOrganic && (
              <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/80 dark:text-green-200">
                <Leaf className="h-3 w-3" />
                Organic
              </span>
            )}
            {isLowStock && !isOutOfStock && (
              <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-amber-100 text-amber-800 dark:bg-amber-900/80 dark:text-amber-200">
                <Clock className="h-3 w-3" />
                Low Stock
              </span>
            )}
            {isOutOfStock && (
              <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-red-100 text-red-800 dark:bg-red-900/80 dark:text-red-200">
                <AlertCircle className="h-3 w-3" />
                Out of Stock
              </span>
            )}
          </div>

          {/* Favorite Button */}
          {onToggleFavorite && (
            <button
              onClick={handleToggleFavorite}
              className={cn(
                "absolute top-2 right-2 p-2 rounded-full",
                "bg-white/90 dark:bg-gray-900/90 backdrop-blur-sm",
                "transition-all duration-200",
                "hover:scale-110",
                "focus:outline-none focus:ring-2 focus:ring-primary",
                isFavorite && "text-red-500"
              )}
              aria-label={isFavorite ? "Remove from favorites" : "Add to favorites"}
            >
              <Heart
                className={cn("h-5 w-5", isFavorite && "fill-current")}
              />
            </button>
          )}

          {/* Quick Add Button (on hover) */}
          {showQuickAdd && !isOutOfStock && (
            <button
              onClick={handleQuickAdd}
              disabled={isAdding || disabled}
              className={cn(
                "absolute bottom-2 right-2",
                "p-2 rounded-full",
                "bg-primary text-primary-foreground",
                "opacity-0 group-hover:opacity-100",
                "transition-all duration-200",
                "hover:scale-110",
                "disabled:opacity-50",
                justAdded && "bg-green-500"
              )}
              aria-label="Quick add to cart"
            >
              {justAdded ? (
                <Check className="h-5 w-5" />
              ) : (
                <Plus className="h-5 w-5" />
              )}
            </button>
          )}
        </div>
      </Link>

      {/* Product Info */}
      <CardContent className="flex-1 p-4">
        {/* Category */}
        <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">
          {ProductCategoryLabels[product.category]}
        </p>

        {/* Name */}
        <Link href={`/products/${product.id}`}>
          <h3 className="font-semibold text-foreground line-clamp-2 hover:text-primary transition-colors">
            {product.name}
          </h3>
        </Link>

        {/* Description */}
        {product.description && (
          <p className="text-sm text-muted-foreground line-clamp-2 mt-1">
            {product.description}
          </p>
        )}

        {/* Farmer Info */}
        {showFarmerInfo && product.farmer && (
          <div className="flex items-center gap-2 mt-3 text-sm text-muted-foreground">
            <MapPin className="h-3.5 w-3.5" />
            <span className="truncate">
              {product.farmer.farmName} • {product.farmer.city}, {product.farmer.state}
            </span>
            {product.farmer.isVerified && (
              <Check className="h-3.5 w-3.5 text-primary flex-shrink-0" />
            )}
          </div>
        )}

        {/* Rating */}
        {product.farmer?.rating && (
          <div className="flex items-center gap-1 mt-2">
            <Star className="h-4 w-4 fill-amber-400 text-amber-400" />
            <span className="text-sm font-medium">{product.farmer.rating.toFixed(1)}</span>
          </div>
        )}

        {/* Price */}
        <div className="mt-3">
          <span className="text-xl font-bold text-primary">
            {formatCurrency(product.pricePerUnit)}
          </span>
          <span className="text-sm text-muted-foreground ml-1">
            / {ProductUnitLabels[product.unit]}
          </span>
        </div>

        {/* Min Order */}
        {product.minOrderQty > 1 && (
          <p className="text-xs text-muted-foreground mt-1">
            Min. order: {product.minOrderQty} {ProductUnitLabels[product.unit]}
          </p>
        )}
      </CardContent>

      {/* Add to Cart Section */}
      <CardFooter className="p-4 pt-0">
        {showQuantitySelector && !isOutOfStock ? (
          <div className="flex items-center gap-2 w-full">
            {/* Quantity Selector */}
            <div className="flex items-center border border-input rounded-md">
              <button
                onClick={(e) => {
                  e.preventDefault();
                  handleQuantityChange(-1);
                }}
                disabled={quantity <= (product.minOrderQty || 1) || disabled}
                className="p-2 hover:bg-accent disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                aria-label="Decrease quantity"
              >
                <Minus className="h-4 w-4" />
              </button>
              <span className="px-3 py-1 min-w-[3rem] text-center font-medium">
                {quantity}
              </span>
              <button
                onClick={(e) => {
                  e.preventDefault();
                  handleQuantityChange(1);
                }}
                disabled={
                  quantity >= (product.maxOrderQty || product.availableQty) ||
                  disabled
                }
                className="p-2 hover:bg-accent disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                aria-label="Increase quantity"
              >
                <Plus className="h-4 w-4" />
              </button>
            </div>

            {/* Add to Cart Button */}
            <Button
              onClick={handleAddToCart}
              disabled={isOutOfStock || disabled || isAdding}
              isLoading={isAdding}
              className="flex-1"
              variant={justAdded ? "success" : "default"}
            >
              {justAdded ? (
                <>
                  <Check className="h-4 w-4 mr-2" />
                  Added!
                </>
              ) : (
                <>
                  <ShoppingCart className="h-4 w-4 mr-2" />
                  Add
                </>
              )}
            </Button>
          </div>
        ) : (
          <Button
            onClick={handleAddToCart}
            disabled={isOutOfStock || disabled || isAdding}
            isLoading={isAdding}
            className="w-full"
            variant={isOutOfStock ? "outline" : justAdded ? "success" : "default"}
          >
            {isOutOfStock ? (
              "Out of Stock"
            ) : justAdded ? (
              <>
                <Check className="h-4 w-4 mr-2" />
                Added to Cart!
              </>
            ) : (
              <>
                <ShoppingCart className="h-4 w-4 mr-2" />
                Add to Cart
              </>
            )}
          </Button>
        )}
      </CardFooter>
    </Card>
  );
}

// ============================================
// LIST VARIANT COMPONENT
// ============================================

interface ListProductCardProps {
  product: ProductCardProduct;
  quantity: number;
  onQuantityChange: (delta: number) => void;
  onAddToCart: (e: React.MouseEvent) => void;
  onToggleFavorite: (e: React.MouseEvent) => void;
  isFavorite: boolean;
  isAdding: boolean;
  justAdded: boolean;
  isOutOfStock: boolean;
  isLowStock: boolean;
  showFarmerInfo: boolean;
  showQuantitySelector: boolean;
  disabled: boolean;
  interactive?: boolean | null;
  className?: string;
}

function ListProductCard({
  product,
  quantity,
  onQuantityChange,
  onAddToCart,
  onToggleFavorite,
  isFavorite,
  isAdding,
  justAdded,
  isOutOfStock,
  isLowStock,
  showFarmerInfo,
  showQuantitySelector,
  disabled,
  interactive,
  className,
}: ListProductCardProps) {
  const primaryImage = product.images?.[0] || "/images/placeholder-product.jpg";

  return (
    <Card
      className={cn(
        productCardVariants({ variant: "list", interactive: interactive && !disabled }),
        isOutOfStock && "opacity-75",
        className
      )}
    >
      {/* Image */}
      <Link href={`/products/${product.id}`} className="flex-shrink-0">
        <div className="relative w-40 h-40 sm:w-48 sm:h-48 overflow-hidden rounded-l-lg bg-muted">
          <Image
            src={primaryImage}
            alt={product.name}
            fill
            className="object-cover"
            sizes="200px"
          />

          {/* Badges */}
          <div className="absolute top-2 left-2 flex flex-col gap-1">
            {product.isOrganic && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                <Leaf className="h-3 w-3" />
                Organic
              </span>
            )}
          </div>
        </div>
      </Link>

      {/* Content */}
      <div className="flex-1 p-4 flex flex-col justify-between">
        <div>
          {/* Header */}
          <div className="flex items-start justify-between gap-2">
            <div>
              <p className="text-xs text-muted-foreground uppercase tracking-wide">
                {ProductCategoryLabels[product.category]}
              </p>
              <Link href={`/products/${product.id}`}>
                <h3 className="font-semibold text-lg hover:text-primary transition-colors">
                  {product.name}
                </h3>
              </Link>
            </div>

            {/* Favorite */}
            <button
              onClick={onToggleFavorite}
              className={cn(
                "p-2 rounded-full hover:bg-accent transition-colors",
                isFavorite && "text-red-500"
              )}
              aria-label={isFavorite ? "Remove from favorites" : "Add to favorites"}
            >
              <Heart className={cn("h-5 w-5", isFavorite && "fill-current")} />
            </button>
          </div>

          {/* Description */}
          {product.description && (
            <p className="text-sm text-muted-foreground line-clamp-2 mt-1">
              {product.description}
            </p>
          )}

          {/* Farmer Info */}
          {showFarmerInfo && product.farmer && (
            <div className="flex items-center gap-4 mt-2 text-sm text-muted-foreground">
              <span className="flex items-center gap-1">
                <MapPin className="h-3.5 w-3.5" />
                {product.farmer.farmName}
              </span>
              {product.farmer.rating && (
                <span className="flex items-center gap-1">
                  <Star className="h-3.5 w-3.5 fill-amber-400 text-amber-400" />
                  {product.farmer.rating.toFixed(1)}
                </span>
              )}
            </div>
          )}

          {/* Stock Status */}
          {isLowStock && !isOutOfStock && (
            <p className="text-xs text-amber-600 mt-2 flex items-center gap-1">
              <Clock className="h-3 w-3" />
              Only {product.availableQty} left
            </p>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between mt-4 gap-4">
          {/* Price */}
          <div>
            <span className="text-2xl font-bold text-primary">
              {formatCurrency(product.pricePerUnit)}
            </span>
            <span className="text-sm text-muted-foreground ml-1">
              / {ProductUnitLabels[product.unit]}
            </span>
          </div>

          {/* Add to Cart */}
          <div className="flex items-center gap-2">
            {showQuantitySelector && !isOutOfStock && (
              <div className="flex items-center border border-input rounded-md">
                <button
                  onClick={(e) => {
                    e.preventDefault();
                    onQuantityChange(-1);
                  }}
                  disabled={quantity <= (product.minOrderQty || 1) || disabled}
                  className="p-1.5 hover:bg-accent disabled:opacity-50 transition-colors"
                >
                  <Minus className="h-4 w-4" />
                </button>
                <span className="px-2 min-w-[2.5rem] text-center text-sm font-medium">
                  {quantity}
                </span>
                <button
                  onClick={(e) => {
                    e.preventDefault();
                    onQuantityChange(1);
                  }}
                  disabled={quantity >= product.availableQty || disabled}
                  className="p-1.5 hover:bg-accent disabled:opacity-50 transition-colors"
                >
                  <Plus className="h-4 w-4" />
                </button>
              </div>
            )}

            <Button
              onClick={onAddToCart}
              disabled={isOutOfStock || disabled || isAdding}
              isLoading={isAdding}
              variant={justAdded ? "success" : "default"}
            >
              {justAdded ? (
                <Check className="h-4 w-4" />
              ) : (
                <ShoppingCart className="h-4 w-4" />
              )}
              <span className="ml-2 hidden sm:inline">
                {isOutOfStock ? "Out of Stock" : justAdded ? "Added!" : "Add"}
              </span>
            </Button>
          </div>
        </div>
      </div>
    </Card>
  );
}

// ============================================
// COMPACT VARIANT COMPONENT
// ============================================

interface CompactProductCardProps {
  product: ProductCardProduct;
  quantity: number;
  onQuantityChange: (delta: number) => void;
  onAddToCart: (e: React.MouseEvent) => void;
  isAdding: boolean;
  justAdded: boolean;
  isOutOfStock: boolean;
  disabled: boolean;
  className?: string;
}

function CompactProductCard({
  product,
  quantity,
  onQuantityChange,
  onAddToCart,
  isAdding,
  justAdded,
  isOutOfStock,
  disabled,
  className,
}: CompactProductCardProps) {
  const primaryImage = product.images?.[0] || "/images/placeholder-product.jpg";

  return (
    <div
      className={cn(
        "flex items-center gap-3 p-3 rounded-lg border bg-card hover:bg-accent/50 transition-colors",
        isOutOfStock && "opacity-75",
        className
      )}
    >
      {/* Image */}
      <div className="relative w-16 h-16 flex-shrink-0 rounded-md overflow-hidden bg-muted">
        <Image
          src={primaryImage}
          alt={product.name}
          fill
          className="object-cover"
          sizes="64px"
        />
        {product.isOrganic && (
          <div className="absolute bottom-0 left-0 right-0 bg-green-500 text-white text-[10px] text-center py-0.5">
            Organic
          </div>
        )}
      </div>

      {/* Info */}
      <div className="flex-1 min-w-0">
        <Link href={`/products/${product.id}`}>
          <h4 className="font-medium text-sm truncate hover:text-primary transition-colors">
            {product.name}
          </h4>
        </Link>
        <p className="text-xs text-muted-foreground">
          {product.farmer?.farmName}
        </p>
        <p className="text-sm font-semibold text-primary mt-0.5">
          {formatCurrency(product.pricePerUnit)}/{ProductUnitLabels[product.unit]}
        </p>
      </div>

      {/* Actions */}
      <div className="flex items-center gap-1">
        <button
          onClick={(e) => {
            e.preventDefault();
            onQuantityChange(-1);
          }}
          disabled={quantity <= (product.minOrderQty || 1) || disabled}
          className="p-1 rounded hover:bg-accent disabled:opacity-50 transition-colors"
        >
          <Minus className="h-3.5 w-3.5" />
        </button>
        <span className="w-6 text-center text-sm font-medium">{quantity}</span>
        <button
          onClick={(e) => {
            e.preventDefault();
            onQuantityChange(1);
          }}
          disabled={quantity >= product.availableQty || disabled}
          className="p-1 rounded hover:bg-accent disabled:opacity-50 transition-colors"
        >
          <Plus className="h-3.5 w-3.5" />
        </button>
        <Button
          size="sm"
          onClick={onAddToCart}
          disabled={isOutOfStock || disabled || isAdding}
          isLoading={isAdding}
          variant={justAdded ? "success" : "default"}
          className="ml-1"
        >
          {justAdded ? <Check className="h-4 w-4" /> : <Plus className="h-4 w-4" />}
        </Button>
      </div>
    </div>
  );
}

// ============================================
// SKELETON COMPONENT
// ============================================

interface ProductCardSkeletonProps {
  variant?: "grid" | "list" | "compact" | null;
  className?: string;
}

export function ProductCardSkeleton({
  variant = "grid",
  className,
}: ProductCardSkeletonProps) {
  if (variant === "compact") {
    return (
      <div className={cn("flex items-center gap-3 p-3 rounded-lg border", className)}>
        <div className="w-16 h-16 rounded-md bg-muted animate-pulse" />
        <div className="flex-1 space-y-2">
          <div className="h-4 w-3/4 bg-muted animate-pulse rounded" />
          <div className="h-3 w-1/2 bg-muted animate-pulse rounded" />
          <div className="h-4 w-1/3 bg-muted animate-pulse rounded" />
        </div>
        <div className="h-8 w-20 bg-muted animate-pulse rounded" />
      </div>
    );
  }

  if (variant === "list") {
    return (
      <Card className={cn("flex flex-row gap-4", className)}>
        <div className="w-40 h-40 sm:w-48 sm:h-48 rounded-l-lg bg-muted animate-pulse" />
        <div className="flex-1 p-4 space-y-3">
          <div className="h-3 w-20 bg-muted animate-pulse rounded" />
          <div className="h-5 w-3/4 bg-muted animate-pulse rounded" />
          <div className="h-4 w-full bg-muted animate-pulse rounded" />
          <div className="h-4 w-2/3 bg-muted animate-pulse rounded" />
          <div className="flex justify-between items-center mt-4">
            <div className="h-6 w-24 bg-muted animate-pulse rounded" />
            <div className="h-10 w-32 bg-muted animate-pulse rounded" />
          </div>
        </div>
      </Card>
    );
  }

  // Grid variant
  return (
    <Card className={cn("overflow-hidden", className)}>
      <div className="aspect-square bg-muted animate-pulse" />
      <CardContent className="p-4 space-y-3">
        <div className="h-3 w-16 bg-muted animate-pulse rounded" />
        <div className="h-5 w-3/4 bg-muted animate-pulse rounded" />
        <div className="h-4 w-full bg-muted animate-pulse rounded" />
        <div className="h-4 w-2/3 bg-muted animate-pulse rounded" />
        <div className="h-6 w-24 bg-muted animate-pulse rounded mt-2" />
      </CardContent>
      <CardFooter className="p-4 pt-0">
        <div className="h-10 w-full bg-muted animate-pulse rounded" />
      </CardFooter>
    </Card>
  );
}

// ============================================
// PRODUCT GRID COMPONENT
// ============================================

export interface ProductGridProps {
  products: ProductCardProduct[];
  variant?: "grid" | "list";
  columns?: 2 | 3 | 4;
  onAddToCart?: (product: ProductCardProduct, quantity: number) => void;
  onToggleFavorite?: (productId: string) => void;
  favorites?: string[];
  isLoading?: boolean;
  emptyMessage?: string;
}

export function ProductGrid({
  products,
  variant = "grid",
  columns = 4,
  onAddToCart,
  onToggleFavorite,
  favorites = [],
  isLoading = false,
  emptyMessage = "No products found",
}: ProductGridProps) {
  const columnClasses = {
    2: "grid-cols-1 sm:grid-cols-2",
    3: "grid-cols-1 sm:grid-cols-2 lg:grid-cols-3",
    4: "grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4",
  };

  if (isLoading) {
    return (
      <div className={cn("grid gap-4 md:gap-6", columnClasses[columns])}>
        {Array.from({ length: 8 }).map((_, i) => (
          <ProductCardSkeleton key={i} variant={variant} />
        ))}
      </div>
    );
  }

  if (products.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <Package className="h-12 w-12 text-muted-foreground/50 mb-4" />
        <h3 className="text-lg font-medium">{emptyMessage}</h3>
        <p className="text-sm text-muted-foreground mt-1">
          Try adjusting your filters or search terms.
        </p>
      </div>
    );
  }

  return (
    <div
      className={cn(
        variant === "grid" ? `grid gap-4 md:gap-6 ${columnClasses[columns]}` : "space-y-4"
      )}
    >
      {products.map((product) => (
        <ProductCard
          key={product.id}
          product={product}
          variant={variant}
          onAddToCart={onAddToCart}
          onToggleFavorite={onToggleFavorite}
          isFavorite={favorites.includes(product.id)}
        />
      ))}
    </div>
  );
}

// ============================================
// EXPORTS
// ============================================

export default ProductCard;
