// Farm-to-Grocer MVP - Reusable Button Component
// Path: components/ui/Button.tsx
// Generated by RJBot Orchestrator
//
// A fully customizable button component with multiple variants,
// sizes, states, and accessibility features built with
// React, TypeScript, Tailwind CSS, and class-variance-authority (CVA)

import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";

// ============================================
// BUTTON VARIANTS CONFIGURATION
// ============================================

/**
 * Button variants using class-variance-authority (CVA)
 * Provides type-safe variant props with Tailwind CSS classes
 */
const buttonVariants = cva(
  // Base styles applied to all buttons
  [
    "inline-flex",
    "items-center",
    "justify-center",
    "gap-2",
    "whitespace-nowrap",
    "rounded-md",
    "text-sm",
    "font-medium",
    "transition-all",
    "duration-200",
    "focus-visible:outline-none",
    "focus-visible:ring-2",
    "focus-visible:ring-ring",
    "focus-visible:ring-offset-2",
    "disabled:pointer-events-none",
    "disabled:opacity-50",
    "active:scale-[0.98]",
    "[&_svg]:pointer-events-none",
    "[&_svg]:size-4",
    "[&_svg]:shrink-0",
  ],
  {
    variants: {
      // ─────────────────────────────────────────
      // VARIANT STYLES
      // ─────────────────────────────────────────
      variant: {
        // Primary - Main CTA button
        default: [
          "bg-primary",
          "text-primary-foreground",
          "shadow",
          "hover:bg-primary/90",
          "hover:shadow-md",
        ],

        // Destructive - Delete, cancel actions
        destructive: [
          "bg-destructive",
          "text-destructive-foreground",
          "shadow-sm",
          "hover:bg-destructive/90",
        ],

        // Outline - Secondary actions
        outline: [
          "border",
          "border-input",
          "bg-background",
          "text-foreground",
          "shadow-sm",
          "hover:bg-accent",
          "hover:text-accent-foreground",
          "hover:border-accent",
        ],

        // Secondary - Less prominent actions
        secondary: [
          "bg-secondary",
          "text-secondary-foreground",
          "shadow-sm",
          "hover:bg-secondary/80",
        ],

        // Ghost - Minimal visual presence
        ghost: [
          "text-foreground",
          "hover:bg-accent",
          "hover:text-accent-foreground",
        ],

        // Link - Text-only button styled as link
        link: [
          "text-primary",
          "underline-offset-4",
          "hover:underline",
        ],

        // Success - Positive actions
        success: [
          "bg-green-600",
          "text-white",
          "shadow-sm",
          "hover:bg-green-700",
        ],

        // Warning - Caution actions
        warning: [
          "bg-amber-500",
          "text-white",
          "shadow-sm",
          "hover:bg-amber-600",
        ],

        // Info - Informational actions
        info: [
          "bg-blue-500",
          "text-white",
          "shadow-sm",
          "hover:bg-blue-600",
        ],
      },

      // ─────────────────────────────────────────
      // SIZE STYLES
      // ─────────────────────────────────────────
      size: {
        default: "h-10 px-4 py-2",
        xs: "h-7 px-2 text-xs rounded",
        sm: "h-9 px-3 rounded-md",
        lg: "h-11 px-8 rounded-md text-base",
        xl: "h-12 px-10 rounded-lg text-base",
        icon: "h-10 w-10",
        "icon-sm": "h-8 w-8",
        "icon-lg": "h-12 w-12",
      },

      // ─────────────────────────────────────────
      // FULL WIDTH OPTION
      // ─────────────────────────────────────────
      fullWidth: {
        true: "w-full",
        false: "",
      },

      // ─────────────────────────────────────────
      // ROUNDED OPTION
      // ─────────────────────────────────────────
      rounded: {
        default: "",
        full: "rounded-full",
        none: "rounded-none",
      },
    },

    // Default variant values
    defaultVariants: {
      variant: "default",
      size: "default",
      fullWidth: false,
      rounded: "default",
    },
  }
);

// ============================================
// BUTTON COMPONENT TYPES
// ============================================

/**
 * Button component props
 * Extends native button attributes with custom variant props
 */
export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
  VariantProps<typeof buttonVariants> {
  /**
   * If true, renders as child component (Slot)
   * Useful for wrapping links or other elements
   */
  asChild?: boolean;

  /**
   * Shows loading spinner and disables button
   */
  isLoading?: boolean;

  /**
   * Text to show while loading (replaces children)
   */
  loadingText?: string;

  /**
   * Icon to display before button text
   */
  leftIcon?: React.ReactNode;

  /**
   * Icon to display after button text
   */
  rightIcon?: React.ReactNode;
}

// ============================================
// BUTTON COMPONENT
// ============================================

/**
 * Button Component
 *
 * A versatile, accessible button component with multiple variants,
 * sizes, and states. Supports loading states, icons, and can be
 * rendered as different elements using the asChild prop.
 *
 * @example
 * // Basic usage
 * <Button>Click me</Button>
 *
 * @example
 * // With variant and size
 * <Button variant="destructive" size="lg">Delete</Button>
 *
 * @example
 * // With loading state
 * <Button isLoading loadingText="Saving...">Save</Button>
 *
 * @example
 * // With icons
 * <Button leftIcon={<PlusIcon />}>Add Item</Button>
 *
 * @example
 * // As a link (using asChild)
 * <Button asChild>
 *   <Link href="/dashboard">Go to Dashboard</Link>
 * </Button>
 */
const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      className,
      variant,
      size,
      fullWidth,
      rounded,
      asChild = false,
      isLoading = false,
      loadingText,
      leftIcon,
      rightIcon,
      disabled,
      children,
      ...props
    },
    ref
  ) => {
    // Use Slot component if asChild is true
    const Comp = asChild ? Slot : "button";

    // Determine if button should be disabled
    const isDisabled = disabled || isLoading;

    if (asChild) {
      return (
        <Comp
          className={cn(
            buttonVariants({ variant, size, fullWidth, rounded }),
            className
          )}
          ref={ref}
          disabled={isDisabled}
          aria-disabled={isDisabled}
          aria-busy={isLoading}
          {...props}
        >
          {children}
        </Comp>
      );
    }

    return (
      <Comp
        className={cn(
          buttonVariants({ variant, size, fullWidth, rounded }),
          className
        )}
        ref={ref}
        disabled={isDisabled}
        aria-disabled={isDisabled}
        aria-busy={isLoading}
        {...props}
      >
        {/* Loading spinner */}
        {isLoading && (
          <Loader2
            className="animate-spin"
            aria-hidden="true"
          />
        )}

        {/* Left icon (hidden when loading) */}
        {!isLoading && leftIcon && (
          <span className="inline-flex shrink-0" aria-hidden="true">
            {leftIcon}
          </span>
        )}

        {/* Button content */}
        {isLoading && loadingText ? loadingText : children}

        {/* Right icon (hidden when loading) */}
        {!isLoading && rightIcon && (
          <span className="inline-flex shrink-0" aria-hidden="true">
            {rightIcon}
          </span>
        )}
      </Comp>
    );
  }
);

Button.displayName = "Button";

// ============================================
// BUTTON GROUP COMPONENT
// ============================================

/**
 * ButtonGroup props
 */
export interface ButtonGroupProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Orientation of the button group
   */
  orientation?: "horizontal" | "vertical";

  /**
   * Spacing between buttons
   */
  spacing?: "none" | "sm" | "md" | "lg";

  /**
   * Whether buttons should be attached (no gap, shared borders)
   */
  attached?: boolean;
}

/**
 * ButtonGroup Component
 *
 * Groups multiple buttons together with consistent spacing
 *
 * @example
 * <ButtonGroup>
 *   <Button>One</Button>
 *   <Button>Two</Button>
 *   <Button>Three</Button>
 * </ButtonGroup>
 */
const ButtonGroup = React.forwardRef<HTMLDivElement, ButtonGroupProps>(
  (
    {
      className,
      orientation = "horizontal",
      spacing = "sm",
      attached = false,
      children,
      ...props
    },
    ref
  ) => {
    const spacingClasses = {
      none: "gap-0",
      sm: "gap-1",
      md: "gap-2",
      lg: "gap-4",
    };

    const orientationClasses = {
      horizontal: "flex-row",
      vertical: "flex-col",
    };

    const attachedClasses = attached
      ? orientation === "horizontal"
        ? "[&>*:not(:first-child):not(:last-child)]:rounded-none [&>*:first-child]:rounded-r-none [&>*:last-child]:rounded-l-none [&>*:not(:first-child)]:-ml-px"
        : "[&>*:not(:first-child):not(:last-child)]:rounded-none [&>*:first-child]:rounded-b-none [&>*:last-child]:rounded-t-none [&>*:not(:first-child)]:-mt-px"
      : "";

    return (
      <div
        ref={ref}
        role="group"
        className={cn(
          "inline-flex",
          orientationClasses[orientation],
          !attached && spacingClasses[spacing],
          attachedClasses,
          className
        )}
        {...props}
      >
        {children}
      </div>
    );
  }
);

ButtonGroup.displayName = "ButtonGroup";

// ============================================
// ICON BUTTON COMPONENT
// ============================================

/**
 * IconButton props
 */
export interface IconButtonProps extends Omit<ButtonProps, "leftIcon" | "rightIcon"> {
  /**
   * Accessible label for the icon button
   * Required for accessibility
   */
  "aria-label": string;

  /**
   * The icon to display
   */
  icon: React.ReactNode;
}

/**
 * IconButton Component
 *
 * A button that only displays an icon with proper accessibility
 *
 * @example
 * <IconButton
 *   aria-label="Delete item"
 *   icon={<TrashIcon />}
 *   variant="destructive"
 * />
 */
const IconButton = React.forwardRef<HTMLButtonElement, IconButtonProps>(
  ({ icon, size = "icon", className, ...props }, ref) => {
    return (
      <Button
        ref={ref}
        size={size}
        className={cn("p-0", className)}
        {...props}
      >
        {icon}
      </Button>
    );
  }
);

IconButton.displayName = "IconButton";

// ============================================
// EXPORTS
// ============================================

export { Button, ButtonGroup, IconButton, buttonVariants };
export default Button;
