// Farm-to-Grocer MVP - Reusable Card Component
// Path: components/ui/Card.tsx
// Generated by RJBot Orchestrator
//
// A composable card component system with:
// - Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter
// - Multiple variants (default, outline, ghost, elevated, interactive)
// - Hover effects and animations
// - Full TypeScript support with forwardRef

import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

// ============================================
// CARD VARIANTS CONFIGURATION
// ============================================

const cardVariants = cva(
  // Base styles
  [
    "rounded-lg",
    "border",
    "text-card-foreground",
    "transition-all",
    "duration-200",
  ],
  {
    variants: {
      variant: {
        // Default card with subtle background
        default: [
          "bg-card",
          "border-border",
          "shadow-sm",
        ],

        // Outline only, no background
        outline: [
          "bg-transparent",
          "border-border",
        ],

        // Ghost - minimal styling
        ghost: [
          "bg-transparent",
          "border-transparent",
          "shadow-none",
        ],

        // Elevated with stronger shadow
        elevated: [
          "bg-card",
          "border-border/50",
          "shadow-md",
        ],

        // Interactive - for clickable cards
        interactive: [
          "bg-card",
          "border-border",
          "shadow-sm",
          "cursor-pointer",
          "hover:shadow-md",
          "hover:border-primary/30",
          "hover:-translate-y-0.5",
          "active:scale-[0.99]",
          "active:shadow-sm",
        ],

        // Destructive - for warning/error cards
        destructive: [
          "bg-destructive/5",
          "border-destructive/30",
          "text-destructive-foreground",
        ],

        // Success - for success states
        success: [
          "bg-green-50",
          "border-green-200",
          "dark:bg-green-950/20",
          "dark:border-green-800",
        ],

        // Warning - for warning states
        warning: [
          "bg-amber-50",
          "border-amber-200",
          "dark:bg-amber-950/20",
          "dark:border-amber-800",
        ],

        // Info - for informational cards
        info: [
          "bg-blue-50",
          "border-blue-200",
          "dark:bg-blue-950/20",
          "dark:border-blue-800",
        ],
      },

      size: {
        default: "p-0",
        sm: "p-3",
        md: "p-4",
        lg: "p-6",
      },

      // Full width option
      fullWidth: {
        true: "w-full",
        false: "",
      },
    },

    defaultVariants: {
      variant: "default",
      size: "default",
      fullWidth: false,
    },
  }
);

// ============================================
// CARD COMPONENT
// ============================================

export interface CardProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof cardVariants> {
  /**
   * Render as a different element (e.g., 'article', 'section')
   */
  as?: React.ElementType;
}

/**
 * Card Component
 *
 * A versatile container component for grouping related content.
 * Supports multiple variants, sizes, and can be composed with
 * CardHeader, CardTitle, CardDescription, CardContent, and CardFooter.
 *
 * @example
 * // Basic usage
 * <Card>
 *   <CardHeader>
 *     <CardTitle>Title</CardTitle>
 *     <CardDescription>Description</CardDescription>
 *   </CardHeader>
 *   <CardContent>Content here</CardContent>
 *   <CardFooter>Footer actions</CardFooter>
 * </Card>
 *
 * @example
 * // Interactive card
 * <Card variant="interactive" onClick={handleClick}>
 *   <CardContent>Click me!</CardContent>
 * </Card>
 */
const Card = React.forwardRef<HTMLDivElement, CardProps>(
  ({ className, variant, size, fullWidth, as: Component = "div", ...props }, ref) => {
    return (
      <Component
        ref={ref}
        className={cn(cardVariants({ variant, size, fullWidth }), className)}
        {...props}
      />
    );
  }
);
Card.displayName = "Card";

// ============================================
// CARD HEADER COMPONENT
// ============================================

export interface CardHeaderProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Add a border below the header
   */
  bordered?: boolean;
}

/**
 * CardHeader Component
 *
 * Container for card title and description.
 * Typically placed at the top of a Card.
 */
const CardHeader = React.forwardRef<HTMLDivElement, CardHeaderProps>(
  ({ className, bordered = false, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        "flex flex-col space-y-1.5 p-6",
        bordered && "border-b border-border pb-4",
        className
      )}
      {...props}
    />
  )
);
CardHeader.displayName = "CardHeader";

// ============================================
// CARD TITLE COMPONENT
// ============================================

export interface CardTitleProps extends React.HTMLAttributes<HTMLHeadingElement> {
  /**
   * Heading level (h1-h6)
   */
  as?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
}

/**
 * CardTitle Component
 *
 * The main heading for a card.
 * Renders as h3 by default but can be changed with the `as` prop.
 */
const CardTitle = React.forwardRef<HTMLHeadingElement, CardTitleProps>(
  ({ className, as: Component = "h3", ...props }, ref) => (
    <Component
      ref={ref}
      className={cn(
        "text-xl font-semibold leading-none tracking-tight",
        className
      )}
      {...props}
    />
  )
);
CardTitle.displayName = "CardTitle";

// ============================================
// CARD DESCRIPTION COMPONENT
// ============================================

export interface CardDescriptionProps
  extends React.HTMLAttributes<HTMLParagraphElement> {}

/**
 * CardDescription Component
 *
 * Secondary text that provides additional context.
 * Typically placed below CardTitle.
 */
const CardDescription = React.forwardRef<
  HTMLParagraphElement,
  CardDescriptionProps
>(({ className, ...props }, ref) => (
  <p
    ref={ref}
    className={cn("text-sm text-muted-foreground", className)}
    {...props}
  />
));
CardDescription.displayName = "CardDescription";

// ============================================
// CARD CONTENT COMPONENT
// ============================================

export interface CardContentProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Remove default padding
   */
  noPadding?: boolean;
}

/**
 * CardContent Component
 *
 * Main content area of the card.
 * Has default padding that can be removed with noPadding prop.
 */
const CardContent = React.forwardRef<HTMLDivElement, CardContentProps>(
  ({ className, noPadding = false, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(!noPadding && "p-6 pt-0", className)}
      {...props}
    />
  )
);
CardContent.displayName = "CardContent";

// ============================================
// CARD FOOTER COMPONENT
// ============================================

export interface CardFooterProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Add a border above the footer
   */
  bordered?: boolean;

  /**
   * Alignment of footer content
   */
  align?: "start" | "center" | "end" | "between";
}

/**
 * CardFooter Component
 *
 * Container for card actions and secondary information.
 * Typically placed at the bottom of a Card.
 */
const CardFooter = React.forwardRef<HTMLDivElement, CardFooterProps>(
  ({ className, bordered = false, align = "start", ...props }, ref) => {
    const alignmentClasses = {
      start: "justify-start",
      center: "justify-center",
      end: "justify-end",
      between: "justify-between",
    };

    return (
      <div
        ref={ref}
        className={cn(
          "flex items-center p-6 pt-0",
          bordered && "border-t border-border pt-4 mt-4",
          alignmentClasses[align],
          className
        )}
        {...props}
      />
    );
  }
);
CardFooter.displayName = "CardFooter";

// ============================================
// CARD IMAGE COMPONENT
// ============================================

export interface CardImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  /**
   * Position of the image
   */
  position?: "top" | "bottom";

  /**
   * Aspect ratio of the image container
   */
  aspectRatio?: "auto" | "square" | "video" | "wide";

  /**
   * Fallback content when image fails to load
   */
  fallback?: React.ReactNode;
}

/**
 * CardImage Component
 *
 * Image container for cards with built-in aspect ratio support.
 */
const CardImage = React.forwardRef<HTMLImageElement, CardImageProps>(
  (
    {
      className,
      position = "top",
      aspectRatio = "video",
      fallback,
      alt = "",
      onError,
      ...props
    },
    ref
  ) => {
    const [hasError, setHasError] = React.useState(false);

    const aspectRatioClasses = {
      auto: "",
      square: "aspect-square",
      video: "aspect-video",
      wide: "aspect-[21/9]",
    };

    const positionClasses = {
      top: "rounded-t-lg",
      bottom: "rounded-b-lg",
    };

    const handleError = (e: React.SyntheticEvent<HTMLImageElement, Event>) => {
      setHasError(true);
      onError?.(e);
    };

    if (hasError && fallback) {
      return (
        <div
          className={cn(
            "flex items-center justify-center bg-muted",
            aspectRatioClasses[aspectRatio],
            positionClasses[position],
            className
          )}
        >
          {fallback}
        </div>
      );
    }

    return (
      <div
        className={cn(
          "overflow-hidden",
          aspectRatioClasses[aspectRatio],
          positionClasses[position]
        )}
      >
        <img
          ref={ref}
          alt={alt}
          onError={handleError}
          className={cn(
            "h-full w-full object-cover",
            className
          )}
          {...props}
        />
      </div>
    );
  }
);
CardImage.displayName = "CardImage";

// ============================================
// CARD ACTION AREA COMPONENT
// ============================================

export interface CardActionAreaProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  /**
   * Render as a link instead of button
   */
  asChild?: boolean;
}

/**
 * CardActionArea Component
 *
 * Makes the entire card clickable with proper focus states.
 * Wrap card content in this component for interactive cards.
 */
const CardActionArea = React.forwardRef<HTMLButtonElement, CardActionAreaProps>(
  ({ className, children, ...props }, ref) => (
    <button
      ref={ref}
      className={cn(
        "w-full text-left",
        "rounded-lg",
        "transition-all duration-200",
        "hover:bg-accent/50",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
        "active:scale-[0.99]",
        className
      )}
      {...props}
    >
      {children}
    </button>
  )
);
CardActionArea.displayName = "CardActionArea";

// ============================================
// CARD BADGE COMPONENT
// ============================================

export interface CardBadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  /**
   * Position of the badge
   */
  position?: "top-left" | "top-right" | "bottom-left" | "bottom-right";
}

/**
 * CardBadge Component
 *
 * A badge that can be positioned absolutely within a card.
 * Useful for status indicators, labels, etc.
 */
const CardBadge = React.forwardRef<HTMLSpanElement, CardBadgeProps>(
  ({ className, position = "top-right", ...props }, ref) => {
    const positionClasses = {
      "top-left": "top-2 left-2",
      "top-right": "top-2 right-2",
      "bottom-left": "bottom-2 left-2",
      "bottom-right": "bottom-2 right-2",
    };

    return (
      <span
        ref={ref}
        className={cn(
          "absolute z-10",
          "inline-flex items-center",
          "rounded-full px-2.5 py-0.5",
          "text-xs font-medium",
          "bg-primary text-primary-foreground",
          positionClasses[position],
          className
        )}
        {...props}
      />
    );
  }
);
CardBadge.displayName = "CardBadge";

// ============================================
// CARD SKELETON COMPONENT
// ============================================

export interface CardSkeletonProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Show image skeleton
   */
  hasImage?: boolean;

  /**
   * Number of content lines
   */
  lines?: number;

  /**
   * Show footer skeleton
   */
  hasFooter?: boolean;
}

/**
 * CardSkeleton Component
 *
 * Loading placeholder for cards.
 */
const CardSkeleton = React.forwardRef<HTMLDivElement, CardSkeletonProps>(
  ({ className, hasImage = true, lines = 3, hasFooter = true, ...props }, ref) => (
    <Card ref={ref} className={cn("overflow-hidden", className)} {...props}>
      {/* Image skeleton */}
      {hasImage && (
        <div className="aspect-video w-full animate-pulse bg-muted" />
      )}

      {/* Header skeleton */}
      <CardHeader>
        <div className="h-5 w-3/4 animate-pulse rounded bg-muted" />
        <div className="h-4 w-1/2 animate-pulse rounded bg-muted" />
      </CardHeader>

      {/* Content skeleton */}
      <CardContent>
        <div className="space-y-2">
          {Array.from({ length: lines }).map((_, i) => (
            <div
              key={i}
              className={cn(
                "h-4 animate-pulse rounded bg-muted",
                i === lines - 1 && "w-4/5"
              )}
            />
          ))}
        </div>
      </CardContent>

      {/* Footer skeleton */}
      {hasFooter && (
        <CardFooter>
          <div className="h-9 w-24 animate-pulse rounded bg-muted" />
        </CardFooter>
      )}
    </Card>
  )
);
CardSkeleton.displayName = "CardSkeleton";

// ============================================
// CARD GROUP COMPONENT
// ============================================

export interface CardGroupProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Layout direction
   */
  direction?: "row" | "column";

  /**
   * Gap between cards
   */
  gap?: "none" | "sm" | "md" | "lg";

  /**
   * Number of columns (for grid layout)
   */
  columns?: 1 | 2 | 3 | 4;
}

/**
 * CardGroup Component
 *
 * Container for grouping multiple cards with consistent spacing.
 */
const CardGroup = React.forwardRef<HTMLDivElement, CardGroupProps>(
  (
    { className, direction = "row", gap = "md", columns, children, ...props },
    ref
  ) => {
    const gapClasses = {
      none: "gap-0",
      sm: "gap-2",
      md: "gap-4",
      lg: "gap-6",
    };

    const columnClasses = {
      1: "grid-cols-1",
      2: "grid-cols-1 sm:grid-cols-2",
      3: "grid-cols-1 sm:grid-cols-2 lg:grid-cols-3",
      4: "grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4",
    };

    // Use grid if columns specified, otherwise flex
    if (columns) {
      return (
        <div
          ref={ref}
          className={cn("grid", columnClasses[columns], gapClasses[gap], className)}
          {...props}
        >
          {children}
        </div>
      );
    }

    return (
      <div
        ref={ref}
        className={cn(
          "flex",
          direction === "row" ? "flex-row flex-wrap" : "flex-col",
          gapClasses[gap],
          className
        )}
        {...props}
      >
        {children}
      </div>
    );
  }
);
CardGroup.displayName = "CardGroup";

// ============================================
// EXPORTS
// ============================================

export {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  CardImage,
  CardActionArea,
  CardBadge,
  CardSkeleton,
  CardGroup,
  cardVariants,
};

export default Card;
