// Farm-to-Grocer MVP - Reusable Input Component
// Path: components/ui/Input.tsx
// Generated by RJBot Orchestrator
//
// A comprehensive input component system with:
// - Input, InputGroup, InputAddon, InputIcon
// - Multiple variants and sizes
// - Error, success, and disabled states
// - Full TypeScript support with forwardRef
// - Accessibility features (ARIA labels, descriptions)

import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { AlertCircle, CheckCircle2, Eye, EyeOff, Search, X } from "lucide-react";
import { cn } from "@/lib/utils";

// ============================================
// INPUT VARIANTS CONFIGURATION
// ============================================

const inputVariants = cva(
  // Base styles
  [
    "flex",
    "w-full",
    "rounded-md",
    "border",
    "bg-background",
    "text-foreground",
    "transition-all",
    "duration-200",
    "file:border-0",
    "file:bg-transparent",
    "file:text-sm",
    "file:font-medium",
    "file:text-foreground",
    "placeholder:text-muted-foreground",
    "focus-visible:outline-none",
    "focus-visible:ring-2",
    "focus-visible:ring-ring",
    "focus-visible:ring-offset-2",
    "focus-visible:ring-offset-background",
    "disabled:cursor-not-allowed",
    "disabled:opacity-50",
    "disabled:bg-muted",
  ],
  {
    variants: {
      variant: {
        // Default input
        default: [
          "border-input",
          "hover:border-primary/50",
          "focus-visible:border-primary",
        ],

        // Filled input (subtle background)
        filled: [
          "border-transparent",
          "bg-muted",
          "hover:bg-muted/80",
          "focus-visible:bg-background",
          "focus-visible:border-primary",
        ],

        // Outline only
        outline: [
          "border-input",
          "bg-transparent",
          "hover:border-primary/50",
          "focus-visible:border-primary",
        ],

        // Ghost (minimal)
        ghost: [
          "border-transparent",
          "bg-transparent",
          "hover:bg-accent",
          "focus-visible:bg-accent",
        ],

        // Underline only
        underline: [
          "border-0",
          "border-b-2",
          "border-input",
          "rounded-none",
          "px-0",
          "hover:border-primary/50",
          "focus-visible:border-primary",
          "focus-visible:ring-0",
          "focus-visible:ring-offset-0",
        ],
      },

      inputSize: {
        xs: "h-7 px-2 text-xs",
        sm: "h-8 px-3 text-sm",
        default: "h-10 px-3 text-sm",
        lg: "h-11 px-4 text-base",
        xl: "h-12 px-4 text-base",
      },

      // State variants
      state: {
        default: "",
        error: [
          "border-destructive",
          "text-destructive",
          "placeholder:text-destructive/60",
          "focus-visible:ring-destructive",
          "hover:border-destructive",
        ],
        success: [
          "border-green-500",
          "text-green-700",
          "dark:text-green-400",
          "focus-visible:ring-green-500",
          "hover:border-green-500",
        ],
        warning: [
          "border-amber-500",
          "text-amber-700",
          "dark:text-amber-400",
          "focus-visible:ring-amber-500",
          "hover:border-amber-500",
        ],
      },
    },

    defaultVariants: {
      variant: "default",
      inputSize: "default",
      state: "default",
    },
  }
);

// ============================================
// INPUT COMPONENT
// ============================================

export interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "size">,
    VariantProps<typeof inputVariants> {
  /**
   * Error message to display
   */
  error?: string;

  /**
   * Success message to display
   */
  success?: string;

  /**
   * Helper text below input
   */
  helperText?: string;

  /**
   * Icon to display on the left
   */
  leftIcon?: React.ReactNode;

  /**
   * Icon to display on the right
   */
  rightIcon?: React.ReactNode;

  /**
   * Show clear button when input has value
   */
  clearable?: boolean;

  /**
   * Callback when clear button is clicked
   */
  onClear?: () => void;

  /**
   * Full width input
   */
  fullWidth?: boolean;

  /**
   * Container className
   */
  containerClassName?: string;
}

/**
 * Input Component
 *
 * A versatile input component with multiple variants, sizes, and states.
 * Supports icons, clearable functionality, and accessibility features.
 *
 * @example
 * // Basic usage
 * <Input placeholder="Enter your name" />
 *
 * @example
 * // With error state
 * <Input error="This field is required" />
 *
 * @example
 * // With icons
 * <Input leftIcon={<SearchIcon />} placeholder="Search..." />
 *
 * @example
 * // Clearable input
 * <Input clearable value={value} onClear={() => setValue("")} />
 */
const Input = React.forwardRef<HTMLInputElement, InputProps>(
  (
    {
      className,
      containerClassName,
      variant,
      inputSize,
      state,
      type = "text",
      error,
      success,
      helperText,
      leftIcon,
      rightIcon,
      clearable,
      onClear,
      fullWidth = true,
      disabled,
      id,
      "aria-describedby": ariaDescribedBy,
      ...props
    },
    ref
  ) => {
    // Generate unique IDs for accessibility
    const inputId = id || React.useId();
    const errorId = `${inputId}-error`;
    const helperId = `${inputId}-helper`;
    const successId = `${inputId}-success`;

    // Determine current state
    const currentState = error ? "error" : success ? "success" : state;

    // Build aria-describedby
    const describedBy = [
      ariaDescribedBy,
      error && errorId,
      success && successId,
      helperText && helperId,
    ]
      .filter(Boolean)
      .join(" ") || undefined;

    // Check if input has addons
    const hasLeftAddon = !!leftIcon;
    const hasRightAddon = !!rightIcon || clearable || error || success;

    return (
      <div className={cn("relative", fullWidth && "w-full", containerClassName)}>
        {/* Input wrapper for icons */}
        <div className="relative">
          {/* Left icon */}
          {hasLeftAddon && (
            <div className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
              {leftIcon}
            </div>
          )}

          {/* Input element */}
          <input
            ref={ref}
            id={inputId}
            type={type}
            disabled={disabled}
            aria-invalid={!!error}
            aria-describedby={describedBy}
            className={cn(
              inputVariants({ variant, inputSize, state: currentState }),
              hasLeftAddon && "pl-10",
              hasRightAddon && "pr-10",
              className
            )}
            {...props}
          />

          {/* Right side icons */}
          {hasRightAddon && (
            <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center gap-1">
              {/* Clear button */}
              {clearable && props.value && !disabled && (
                <button
                  type="button"
                  onClick={onClear}
                  className="text-muted-foreground hover:text-foreground transition-colors p-0.5 rounded-sm hover:bg-accent"
                  aria-label="Clear input"
                >
                  <X className="h-4 w-4" />
                </button>
              )}

              {/* State icons */}
              {error && !rightIcon && (
                <AlertCircle className="h-4 w-4 text-destructive" aria-hidden="true" />
              )}
              {success && !error && !rightIcon && (
                <CheckCircle2 className="h-4 w-4 text-green-500" aria-hidden="true" />
              )}

              {/* Custom right icon */}
              {rightIcon && (
                <span className="text-muted-foreground">{rightIcon}</span>
              )}
            </div>
          )}
        </div>

        {/* Helper text / Error / Success messages */}
        {(error || success || helperText) && (
          <div className="mt-1.5">
            {error && (
              <p
                id={errorId}
                className="text-sm text-destructive flex items-center gap-1"
                role="alert"
              >
                {error}
              </p>
            )}
            {success && !error && (
              <p
                id={successId}
                className="text-sm text-green-600 dark:text-green-400 flex items-center gap-1"
              >
                {success}
              </p>
            )}
            {helperText && !error && !success && (
              <p id={helperId} className="text-sm text-muted-foreground">
                {helperText}
              </p>
            )}
          </div>
        )}
      </div>
    );
  }
);
Input.displayName = "Input";

// ============================================
// PASSWORD INPUT COMPONENT
// ============================================

export interface PasswordInputProps extends Omit<InputProps, "type" | "rightIcon"> {
  /**
   * Show password strength indicator
   */
  showStrength?: boolean;
}

/**
 * PasswordInput Component
 *
 * Input with toggle visibility button for password fields.
 */
const PasswordInput = React.forwardRef<HTMLInputElement, PasswordInputProps>(
  ({ showStrength, ...props }, ref) => {
    const [showPassword, setShowPassword] = React.useState(false);

    const toggleVisibility = () => setShowPassword((prev) => !prev);

    return (
      <div className="relative">
        <Input
          ref={ref}
          type={showPassword ? "text" : "password"}
          rightIcon={
            <button
              type="button"
              onClick={toggleVisibility}
              className="text-muted-foreground hover:text-foreground transition-colors"
              aria-label={showPassword ? "Hide password" : "Show password"}
            >
              {showPassword ? (
                <EyeOff className="h-4 w-4" />
              ) : (
                <Eye className="h-4 w-4" />
              )}
            </button>
          }
          {...props}
        />
      </div>
    );
  }
);
PasswordInput.displayName = "PasswordInput";

// ============================================
// SEARCH INPUT COMPONENT
// ============================================

export interface SearchInputProps extends Omit<InputProps, "leftIcon" | "type"> {
  /**
   * Callback when search is submitted
   */
  onSearch?: (value: string) => void;
}

/**
 * SearchInput Component
 *
 * Pre-configured input for search functionality.
 */
const SearchInput = React.forwardRef<HTMLInputElement, SearchInputProps>(
  ({ onSearch, onKeyDown, clearable = true, ...props }, ref) => {
    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === "Enter" && onSearch) {
        onSearch((e.target as HTMLInputElement).value);
      }
      onKeyDown?.(e);
    };

    return (
      <Input
        ref={ref}
        type="search"
        leftIcon={<Search className="h-4 w-4" />}
        clearable={clearable}
        onKeyDown={handleKeyDown}
        {...props}
      />
    );
  }
);
SearchInput.displayName = "SearchInput";

// ============================================
// INPUT GROUP COMPONENT
// ============================================

export interface InputGroupProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Size of all inputs in the group
   */
  size?: "xs" | "sm" | "default" | "lg" | "xl";
}

/**
 * InputGroup Component
 *
 * Groups input with addons (prefix/suffix elements).
 */
const InputGroup = React.forwardRef<HTMLDivElement, InputGroupProps>(
  ({ className, children, size, ...props }, ref) => {
    // Clone children to pass size prop
    const childrenWithProps = React.Children.map(children, (child) => {
      if (React.isValidElement(child)) {
        return React.cloneElement(child, { inputSize: size } as any);
      }
      return child;
    });

    return (
      <div
        ref={ref}
        className={cn("flex items-stretch", className)}
        {...props}
      >
        {childrenWithProps}
      </div>
    );
  }
);
InputGroup.displayName = "InputGroup";

// ============================================
// INPUT ADDON COMPONENT
// ============================================

export interface InputAddonProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Position of the addon
   */
  position?: "left" | "right";

  /**
   * Size variant
   */
  inputSize?: "xs" | "sm" | "default" | "lg" | "xl";
}

/**
 * InputAddon Component
 *
 * Static addon element for InputGroup (e.g., "$", "https://").
 */
const InputAddon = React.forwardRef<HTMLDivElement, InputAddonProps>(
  ({ className, position = "left", inputSize = "default", children, ...props }, ref) => {
    const sizeClasses = {
      xs: "px-2 text-xs",
      sm: "px-2.5 text-sm",
      default: "px-3 text-sm",
      lg: "px-4 text-base",
      xl: "px-4 text-base",
    };

    return (
      <div
        ref={ref}
        className={cn(
          "flex items-center",
          "bg-muted",
          "border border-input",
          "text-muted-foreground",
          sizeClasses[inputSize],
          position === "left" && "rounded-l-md border-r-0",
          position === "right" && "rounded-r-md border-l-0",
          className
        )}
        {...props}
      >
        {children}
      </div>
    );
  }
);
InputAddon.displayName = "InputAddon";

// ============================================
// INPUT WITH LABEL COMPONENT
// ============================================

export interface LabeledInputProps extends InputProps {
  /**
   * Label text
   */
  label: string;

  /**
   * Mark as required
   */
  required?: boolean;

  /**
   * Optional label (shows "optional" text)
   */
  optional?: boolean;

  /**
   * Label className
   */
  labelClassName?: string;
}

/**
 * LabeledInput Component
 *
 * Input with integrated label for form fields.
 */
const LabeledInput = React.forwardRef<HTMLInputElement, LabeledInputProps>(
  (
    {
      label,
      required,
      optional,
      labelClassName,
      id,
      className,
      ...props
    },
    ref
  ) => {
    const inputId = id || React.useId();

    return (
      <div className="space-y-1.5">
        <label
          htmlFor={inputId}
          className={cn(
            "text-sm font-medium leading-none",
            "peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
            labelClassName
          )}
        >
          {label}
          {required && (
            <span className="text-destructive ml-1" aria-hidden="true">
              *
            </span>
          )}
          {optional && (
            <span className="text-muted-foreground ml-1 font-normal">
              (optional)
            </span>
          )}
        </label>
        <Input
          ref={ref}
          id={inputId}
          required={required}
          className={className}
          {...props}
        />
      </div>
    );
  }
);
LabeledInput.displayName = "LabeledInput";

// ============================================
// TEXTAREA COMPONENT
// ============================================

export interface TextareaProps
  extends Omit<React.TextareaHTMLAttributes<HTMLTextAreaElement>, "size">,
    VariantProps<typeof inputVariants> {
  /**
   * Error message
   */
  error?: string;

  /**
   * Helper text
   */
  helperText?: string;

  /**
   * Auto-resize based on content
   */
  autoResize?: boolean;

  /**
   * Show character count
   */
  showCount?: boolean;

  /**
   * Maximum character count
   */
  maxLength?: number;
}

/**
 * Textarea Component
 *
 * Multi-line text input with auto-resize and character count.
 */
const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    {
      className,
      variant,
      state,
      error,
      helperText,
      autoResize,
      showCount,
      maxLength,
      onChange,
      value,
      id,
      ...props
    },
    ref
  ) => {
    const textareaRef = React.useRef<HTMLTextAreaElement | null>(null);
    const inputId = id || React.useId();
    const errorId = `${inputId}-error`;
    const helperId = `${inputId}-helper`;

    const currentState = error ? "error" : state;
    const charCount = typeof value === "string" ? value.length : 0;

    // Auto-resize functionality
    const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      if (autoResize && textareaRef.current) {
        textareaRef.current.style.height = "auto";
        textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
      }
      onChange?.(e);
    };

    // Combine refs
    const setRefs = React.useCallback(
      (node: HTMLTextAreaElement | null) => {
        textareaRef.current = node;
        if (typeof ref === "function") {
          ref(node);
        } else if (ref) {
          ref.current = node;
        }
      },
      [ref]
    );

    return (
      <div className="relative w-full">
        <textarea
          ref={setRefs}
          id={inputId}
          value={value}
          maxLength={maxLength}
          onChange={handleChange}
          aria-invalid={!!error}
          aria-describedby={
            [error && errorId, helperText && helperId].filter(Boolean).join(" ") ||
            undefined
          }
          className={cn(
            inputVariants({ variant, state: currentState }),
            "min-h-[80px] py-2 resize-y",
            autoResize && "resize-none overflow-hidden",
            className
          )}
          {...props}
        />

        {/* Character count */}
        {showCount && (
          <div className="absolute bottom-2 right-3 text-xs text-muted-foreground">
            {charCount}
            {maxLength && `/${maxLength}`}
          </div>
        )}

        {/* Error / Helper text */}
        {(error || helperText) && (
          <div className="mt-1.5">
            {error && (
              <p id={errorId} className="text-sm text-destructive" role="alert">
                {error}
              </p>
            )}
            {helperText && !error && (
              <p id={helperId} className="text-sm text-muted-foreground">
                {helperText}
              </p>
            )}
          </div>
        )}
      </div>
    );
  }
);
Textarea.displayName = "Textarea";

// ============================================
// INPUT SKELETON COMPONENT
// ============================================

export interface InputSkeletonProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Show label skeleton
   */
  hasLabel?: boolean;

  /**
   * Show helper text skeleton
   */
  hasHelper?: boolean;
}

/**
 * InputSkeleton Component
 *
 * Loading placeholder for input fields.
 */
const InputSkeleton = React.forwardRef<HTMLDivElement, InputSkeletonProps>(
  ({ className, hasLabel = true, hasHelper = false, ...props }, ref) => (
    <div ref={ref} className={cn("space-y-1.5", className)} {...props}>
      {hasLabel && (
        <div className="h-4 w-20 animate-pulse rounded bg-muted" />
      )}
      <div className="h-10 w-full animate-pulse rounded-md bg-muted" />
      {hasHelper && (
        <div className="h-3 w-32 animate-pulse rounded bg-muted" />
      )}
    </div>
  )
);
InputSkeleton.displayName = "InputSkeleton";

// ============================================
// EXPORTS
// ============================================

export {
  Input,
  PasswordInput,
  SearchInput,
  InputGroup,
  InputAddon,
  LabeledInput,
  Textarea,
  InputSkeleton,
  inputVariants,
};

export default Input;
