// Farm-to-Grocer MVP - Reusable Modal Component
// Path: components/ui/Modal.tsx
// Generated by RJBot Orchestrator
//
// A comprehensive modal/dialog component system with:
// - Modal, ModalHeader, ModalTitle, ModalDescription, ModalBody, ModalFooter
// - Multiple sizes and variants
// - Focus trapping and keyboard navigation
// - Animations and transitions
// - Full accessibility support (ARIA)
// - Built on Radix UI Dialog primitive

"use client";

import * as React from "react";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import { cva, type VariantProps } from "class-variance-authority";
import { X, AlertTriangle, CheckCircle, Info, AlertCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/Button";

// ============================================
// MODAL VARIANTS CONFIGURATION
// ============================================

const modalOverlayVariants = cva(
  [
    "fixed",
    "inset-0",
    "z-50",
    "transition-all",
    "duration-200",
  ],
  {
    variants: {
      variant: {
        default: "bg-black/50 backdrop-blur-sm",
        dark: "bg-black/70 backdrop-blur-md",
        light: "bg-white/50 backdrop-blur-sm",
        transparent: "bg-transparent",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
);

const modalContentVariants = cva(
  [
    "fixed",
    "left-[50%]",
    "top-[50%]",
    "z-50",
    "translate-x-[-50%]",
    "translate-y-[-50%]",
    "bg-background",
    "shadow-lg",
    "border",
    "border-border",
    "rounded-lg",
    "w-full",
    "max-h-[90vh]",
    "overflow-hidden",
    "flex",
    "flex-col",
    // Animation
    "data-[state=open]:animate-in",
    "data-[state=closed]:animate-out",
    "data-[state=closed]:fade-out-0",
    "data-[state=open]:fade-in-0",
    "data-[state=closed]:zoom-out-95",
    "data-[state=open]:zoom-in-95",
    "data-[state=closed]:slide-out-to-left-1/2",
    "data-[state=closed]:slide-out-to-top-[48%]",
    "data-[state=open]:slide-in-from-left-1/2",
    "data-[state=open]:slide-in-from-top-[48%]",
    "duration-200",
  ],
  {
    variants: {
      size: {
        xs: "max-w-xs",
        sm: "max-w-sm",
        default: "max-w-lg",
        lg: "max-w-2xl",
        xl: "max-w-4xl",
        full: "max-w-[95vw] h-[90vh]",
      },
    },
    defaultVariants: {
      size: "default",
    },
  }
);

// ============================================
// MODAL ROOT COMPONENT
// ============================================

const Modal = DialogPrimitive.Root;

// ============================================
// MODAL TRIGGER COMPONENT
// ============================================

const ModalTrigger = DialogPrimitive.Trigger;

// ============================================
// MODAL PORTAL COMPONENT
// ============================================

const ModalPortal = DialogPrimitive.Portal;

// ============================================
// MODAL CLOSE COMPONENT
// ============================================

const ModalClose = DialogPrimitive.Close;

// ============================================
// MODAL OVERLAY COMPONENT
// ============================================

export interface ModalOverlayProps
  extends React.ComponentPropsWithoutRef<typeof DialogPrimitive.Overlay>,
    VariantProps<typeof modalOverlayVariants> {}

const ModalOverlay = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Overlay>,
  ModalOverlayProps
>(({ className, variant, ...props }, ref) => (
  <DialogPrimitive.Overlay
    ref={ref}
    className={cn(
      modalOverlayVariants({ variant }),
      "data-[state=open]:animate-in data-[state=closed]:animate-out",
      "data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
      className
    )}
    {...props}
  />
));
ModalOverlay.displayName = DialogPrimitive.Overlay.displayName;

// ============================================
// MODAL CONTENT COMPONENT
// ============================================

export interface ModalContentProps
  extends React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>,
    VariantProps<typeof modalContentVariants> {
  /**
   * Show close button in top right corner
   */
  showCloseButton?: boolean;

  /**
   * Overlay variant
   */
  overlayVariant?: VariantProps<typeof modalOverlayVariants>["variant"];

  /**
   * Prevent closing on overlay click
   */
  preventOverlayClose?: boolean;

  /**
   * Prevent closing on escape key
   */
  preventEscapeClose?: boolean;
}

const ModalContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Content>,
  ModalContentProps
>(
  (
    {
      className,
      children,
      size,
      showCloseButton = true,
      overlayVariant = "default",
      preventOverlayClose = false,
      preventEscapeClose = false,
      onPointerDownOutside,
      onEscapeKeyDown,
      ...props
    },
    ref
  ) => {
    const handlePointerDownOutside = (e: Event) => {
      if (preventOverlayClose) {
        e.preventDefault();
      }
      onPointerDownOutside?.(e as any);
    };

    const handleEscapeKeyDown = (e: KeyboardEvent) => {
      if (preventEscapeClose) {
        e.preventDefault();
      }
      onEscapeKeyDown?.(e);
    };

    return (
      <ModalPortal>
        <ModalOverlay variant={overlayVariant} />
        <DialogPrimitive.Content
          ref={ref}
          onPointerDownOutside={handlePointerDownOutside}
          onEscapeKeyDown={handleEscapeKeyDown}
          className={cn(modalContentVariants({ size }), className)}
          {...props}
        >
          {children}

          {/* Close button */}
          {showCloseButton && (
            <DialogPrimitive.Close
              className={cn(
                "absolute right-4 top-4",
                "rounded-sm opacity-70",
                "ring-offset-background",
                "transition-opacity",
                "hover:opacity-100",
                "focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
                "disabled:pointer-events-none",
                "data-[state=open]:bg-accent data-[state=open]:text-muted-foreground"
              )}
              aria-label="Close"
            >
              <X className="h-4 w-4" />
            </DialogPrimitive.Close>
          )}
        </DialogPrimitive.Content>
      </ModalPortal>
    );
  }
);
ModalContent.displayName = DialogPrimitive.Content.displayName;

// ============================================
// MODAL HEADER COMPONENT
// ============================================

export interface ModalHeaderProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Add border below header
   */
  bordered?: boolean;
}

const ModalHeader = React.forwardRef<HTMLDivElement, ModalHeaderProps>(
  ({ className, bordered = false, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        "flex flex-col space-y-1.5 p-6",
        bordered && "border-b border-border",
        className
      )}
      {...props}
    />
  )
);
ModalHeader.displayName = "ModalHeader";

// ============================================
// MODAL TITLE COMPONENT
// ============================================

const ModalTitle = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Title
    ref={ref}
    className={cn(
      "text-lg font-semibold leading-none tracking-tight",
      className
    )}
    {...props}
  />
));
ModalTitle.displayName = DialogPrimitive.Title.displayName;

// ============================================
// MODAL DESCRIPTION COMPONENT
// ============================================

const ModalDescription = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Description
    ref={ref}
    className={cn("text-sm text-muted-foreground", className)}
    {...props}
  />
));
ModalDescription.displayName = DialogPrimitive.Description.displayName;

// ============================================
// MODAL BODY COMPONENT
// ============================================

export interface ModalBodyProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Enable scrolling for long content
   */
  scrollable?: boolean;
}

const ModalBody = React.forwardRef<HTMLDivElement, ModalBodyProps>(
  ({ className, scrollable = true, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        "flex-1 p-6 pt-0",
        scrollable && "overflow-y-auto",
        className
      )}
      {...props}
    />
  )
);
ModalBody.displayName = "ModalBody";

// ============================================
// MODAL FOOTER COMPONENT
// ============================================

export interface ModalFooterProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Add border above footer
   */
  bordered?: boolean;

  /**
   * Alignment of footer content
   */
  align?: "start" | "center" | "end" | "between";
}

const ModalFooter = React.forwardRef<HTMLDivElement, ModalFooterProps>(
  ({ className, bordered = false, align = "end", ...props }, ref) => {
    const alignmentClasses = {
      start: "justify-start",
      center: "justify-center",
      end: "justify-end",
      between: "justify-between",
    };

    return (
      <div
        ref={ref}
        className={cn(
          "flex items-center gap-2 p-6 pt-0",
          bordered && "border-t border-border pt-4 mt-4",
          alignmentClasses[align],
          className
        )}
        {...props}
      />
    );
  }
);
ModalFooter.displayName = "ModalFooter";

// ============================================
// ALERT MODAL COMPONENT
// ============================================

export interface AlertModalProps {
  /**
   * Modal open state
   */
  open: boolean;

  /**
   * Callback when modal state changes
   */
  onOpenChange: (open: boolean) => void;

  /**
   * Alert type
   */
  type?: "info" | "success" | "warning" | "error";

  /**
   * Modal title
   */
  title: string;

  /**
   * Modal description/message
   */
  description: string;

  /**
   * Confirm button text
   */
  confirmText?: string;

  /**
   * Cancel button text
   */
  cancelText?: string;

  /**
   * Callback when confirm is clicked
   */
  onConfirm?: () => void;

  /**
   * Callback when cancel is clicked
   */
  onCancel?: () => void;

  /**
   * Show cancel button
   */
  showCancel?: boolean;

  /**
   * Loading state for confirm button
   */
  isLoading?: boolean;
}

/**
 * AlertModal Component
 *
 * Pre-configured modal for alerts, confirmations, and notifications.
 *
 * @example
 * <AlertModal
 *   open={isOpen}
 *   onOpenChange={setIsOpen}
 *   type="warning"
 *   title="Delete Item?"
 *   description="This action cannot be undone."
 *   confirmText="Delete"
 *   onConfirm={handleDelete}
 *   showCancel
 * />
 */
const AlertModal: React.FC<AlertModalProps> = ({
  open,
  onOpenChange,
  type = "info",
  title,
  description,
  confirmText = "OK",
  cancelText = "Cancel",
  onConfirm,
  onCancel,
  showCancel = false,
  isLoading = false,
}) => {
  const icons = {
    info: <Info className="h-6 w-6 text-blue-500" />,
    success: <CheckCircle className="h-6 w-6 text-green-500" />,
    warning: <AlertTriangle className="h-6 w-6 text-amber-500" />,
    error: <AlertCircle className="h-6 w-6 text-red-500" />,
  };

  const confirmVariants = {
    info: "default" as const,
    success: "success" as const,
    warning: "warning" as const,
    error: "destructive" as const,
  };

  const handleConfirm = () => {
    onConfirm?.();
    if (!isLoading) {
      onOpenChange(false);
    }
  };

  const handleCancel = () => {
    onCancel?.();
    onOpenChange(false);
  };

  return (
    <Modal open={open} onOpenChange={onOpenChange}>
      <ModalContent size="sm" showCloseButton={false}>
        <ModalHeader>
          <div className="flex items-center gap-3">
            {icons[type]}
            <ModalTitle>{title}</ModalTitle>
          </div>
          <ModalDescription className="pl-9">{description}</ModalDescription>
        </ModalHeader>
        <ModalFooter>
          {showCancel && (
            <Button variant="outline" onClick={handleCancel} disabled={isLoading}>
              {cancelText}
            </Button>
          )}
          <Button
            variant={confirmVariants[type]}
            onClick={handleConfirm}
            isLoading={isLoading}
          >
            {confirmText}
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};
AlertModal.displayName = "AlertModal";

// ============================================
// CONFIRM MODAL COMPONENT
// ============================================

export interface ConfirmModalProps {
  /**
   * Modal open state
   */
  open: boolean;

  /**
   * Callback when modal state changes
   */
  onOpenChange: (open: boolean) => void;

  /**
   * Modal title
   */
  title: string;

  /**
   * Modal description/message
   */
  description: string;

  /**
   * Confirm button text
   */
  confirmText?: string;

  /**
   * Cancel button text
   */
  cancelText?: string;

  /**
   * Callback when confirm is clicked
   */
  onConfirm: () => void | Promise<void>;

  /**
   * Destructive action (red confirm button)
   */
  destructive?: boolean;
}

/**
 * ConfirmModal Component
 *
 * Simple confirmation dialog with confirm/cancel actions.
 *
 * @example
 * <ConfirmModal
 *   open={isOpen}
 *   onOpenChange={setIsOpen}
 *   title="Delete Product?"
 *   description="This will permanently delete the product."
 *   onConfirm={handleDelete}
 *   destructive
 * />
 */
const ConfirmModal: React.FC<ConfirmModalProps> = ({
  open,
  onOpenChange,
  title,
  description,
  confirmText = "Confirm",
  cancelText = "Cancel",
  onConfirm,
  destructive = false,
}) => {
  const [isLoading, setIsLoading] = React.useState(false);

  const handleConfirm = async () => {
    setIsLoading(true);
    try {
      await onConfirm();
      onOpenChange(false);
    } catch (error) {
      console.error("Confirm action failed:", error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Modal open={open} onOpenChange={onOpenChange}>
      <ModalContent size="sm">
        <ModalHeader>
          <ModalTitle>{title}</ModalTitle>
          <ModalDescription>{description}</ModalDescription>
        </ModalHeader>
        <ModalFooter>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={isLoading}
          >
            {cancelText}
          </Button>
          <Button
            variant={destructive ? "destructive" : "default"}
            onClick={handleConfirm}
            isLoading={isLoading}
          >
            {confirmText}
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};
ConfirmModal.displayName = "ConfirmModal";

// ============================================
// DRAWER MODAL COMPONENT (Side Panel)
// ============================================

const drawerVariants = cva(
  [
    "fixed",
    "z-50",
    "bg-background",
    "shadow-lg",
    "border",
    "flex",
    "flex-col",
    "transition-transform",
    "duration-300",
    "ease-in-out",
  ],
  {
    variants: {
      side: {
        left: "inset-y-0 left-0 h-full border-r data-[state=open]:animate-slide-in-from-left data-[state=closed]:animate-slide-out-to-left",
        right: "inset-y-0 right-0 h-full border-l data-[state=open]:animate-slide-in-from-right data-[state=closed]:animate-slide-out-to-right",
        top: "inset-x-0 top-0 w-full border-b data-[state=open]:animate-slide-in-from-top data-[state=closed]:animate-slide-out-to-top",
        bottom: "inset-x-0 bottom-0 w-full border-t data-[state=open]:animate-slide-in-from-bottom data-[state=closed]:animate-slide-out-to-bottom",
      },
      size: {
        sm: "",
        default: "",
        lg: "",
        full: "",
      },
    },
    compoundVariants: [
      // Left/Right sizes
      { side: "left", size: "sm", className: "w-72" },
      { side: "left", size: "default", className: "w-96" },
      { side: "left", size: "lg", className: "w-[500px]" },
      { side: "left", size: "full", className: "w-screen" },
      { side: "right", size: "sm", className: "w-72" },
      { side: "right", size: "default", className: "w-96" },
      { side: "right", size: "lg", className: "w-[500px]" },
      { side: "right", size: "full", className: "w-screen" },
      // Top/Bottom sizes
      { side: "top", size: "sm", className: "h-48" },
      { side: "top", size: "default", className: "h-72" },
      { side: "top", size: "lg", className: "h-96" },
      { side: "top", size: "full", className: "h-screen" },
      { side: "bottom", size: "sm", className: "h-48" },
      { side: "bottom", size: "default", className: "h-72" },
      { side: "bottom", size: "lg", className: "h-96" },
      { side: "bottom", size: "full", className: "h-screen" },
    ],
    defaultVariants: {
      side: "right",
      size: "default",
    },
  }
);

export interface DrawerProps
  extends React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>,
    VariantProps<typeof drawerVariants> {
  /**
   * Show close button
   */
  showCloseButton?: boolean;
}

/**
 * Drawer Component
 *
 * Side panel modal that slides in from any edge.
 *
 * @example
 * <Modal open={open} onOpenChange={setOpen}>
 *   <Drawer side="right" size="lg">
 *     <ModalHeader>
 *       <ModalTitle>Settings</ModalTitle>
 *     </ModalHeader>
 *     <ModalBody>Content here</ModalBody>
 *   </Drawer>
 * </Modal>
 */
const Drawer = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Content>,
  DrawerProps
>(({ className, children, side, size, showCloseButton = true, ...props }, ref) => (
  <ModalPortal>
    <ModalOverlay />
    <DialogPrimitive.Content
      ref={ref}
      className={cn(drawerVariants({ side, size }), className)}
      {...props}
    >
      {children}

      {showCloseButton && (
        <DialogPrimitive.Close
          className={cn(
            "absolute right-4 top-4",
            "rounded-sm opacity-70",
            "ring-offset-background",
            "transition-opacity",
            "hover:opacity-100",
            "focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
          )}
          aria-label="Close"
        >
          <X className="h-4 w-4" />
        </DialogPrimitive.Close>
      )}
    </DialogPrimitive.Content>
  </ModalPortal>
));
Drawer.displayName = "Drawer";

// ============================================
// USE MODAL HOOK
// ============================================

/**
 * useModal Hook
 *
 * Convenient hook for managing modal state.
 *
 * @example
 * const { isOpen, open, close, toggle } = useModal();
 *
 * <Button onClick={open}>Open Modal</Button>
 * <Modal open={isOpen} onOpenChange={close}>...</Modal>
 */
export function useModal(initialState: boolean = false) {
  const [isOpen, setIsOpen] = React.useState(initialState);

  const open = React.useCallback(() => setIsOpen(true), []);
  const close = React.useCallback(() => setIsOpen(false), []);
  const toggle = React.useCallback(() => setIsOpen((prev) => !prev), []);

  return {
    isOpen,
    setIsOpen,
    open,
    close,
    toggle,
  };
}

// ============================================
// EXPORTS
// ============================================

export {
  Modal,
  ModalTrigger,
  ModalPortal,
  ModalClose,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalTitle,
  ModalDescription,
  ModalBody,
  ModalFooter,
  AlertModal,
  ConfirmModal,
  Drawer,
};

export default Modal;
