// Farm-to-Grocer MVP - NextAuth.js Configuration
// Path: lib/auth.ts
// Generated by RJBot Orchestrator

import { NextAuthOptions, getServerSession, Session } from "next-auth";
import { PrismaAdapter } from "@auth/prisma-adapter";
import { Adapter } from "next-auth/adapters";
import CredentialsProvider from "next-auth/providers/credentials";
import GoogleProvider from "next-auth/providers/google";
import EmailProvider from "next-auth/providers/email";
import { compare, hash } from "bcryptjs";
import { z } from "zod";

import prisma from "@/lib/prisma";
import { UserRole, AccountStatus } from "@prisma/client";

// ============================================
// TYPE EXTENSIONS
// ============================================

declare module "next-auth" {
  interface Session {
    user: {
      id: string;
      email: string;
      name: string;
      image?: string | null;
      role: UserRole;
      status: AccountStatus;
      farmerId?: string;
      grocerId?: string;
    };
  }

  interface User {
    id: string;
    email: string;
    name: string;
    image?: string | null;
    role: UserRole;
    status: AccountStatus;
  }
}

declare module "next-auth/jwt" {
  interface JWT {
    id: string;
    email: string;
    name: string;
    role: UserRole;
    status: AccountStatus;
    farmerId?: string;
    grocerId?: string;
  }
}

// ============================================
// VALIDATION SCHEMAS
// ============================================

export const loginSchema = z.object({
  email: z.string().email("Invalid email address"),
  password: z.string().min(8, "Password must be at least 8 characters"),
});

export const registerSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters"),
  email: z.string().email("Invalid email address"),
  password: z
    .string()
    .min(8, "Password must be at least 8 characters")
    .regex(
      /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/,
      "Password must contain uppercase, lowercase, and number"
    ),
  role: z.enum(["FARMER", "GROCER"]),
});

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Hash a password using bcrypt
 */
export async function hashPassword(password: string): Promise<string> {
  return hash(password, 12);
}

/**
 * Verify a password against a hash
 */
export async function verifyPassword(
  password: string,
  hashedPassword: string
): Promise<boolean> {
  return compare(password, hashedPassword);
}

/**
 * Get user with related profile data
 */
async function getUserWithProfile(userId: string) {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    include: {
      farmer: { select: { id: true } },
      grocer: { select: { id: true } },
    },
  });

  return user;
}

// ============================================
// NEXTAUTH CONFIGURATION
// ============================================

export const authOptions: NextAuthOptions = {
  // Prisma Adapter for database sessions
  adapter: PrismaAdapter(prisma) as Adapter,

  // Session configuration
  session: {
    strategy: "jwt",
    maxAge: 30 * 24 * 60 * 60, // 30 days
    updateAge: 24 * 60 * 60, // 24 hours
  },

  // JWT configuration
  jwt: {
    maxAge: 30 * 24 * 60 * 60, // 30 days
  },

  // Custom pages
  pages: {
    signIn: "/login",
    signOut: "/logout",
    error: "/auth/error",
    verifyRequest: "/auth/verify-request",
    newUser: "/onboarding",
  },

  // Authentication providers
  providers: [
    // ─────────────────────────────────────────
    // Credentials Provider (Email/Password)
    // ─────────────────────────────────────────
    CredentialsProvider({
      id: "credentials",
      name: "Email & Password",
      credentials: {
        email: {
          label: "Email",
          type: "email",
          placeholder: "you@example.com",
        },
        password: {
          label: "Password",
          type: "password",
        },
      },
      async authorize(credentials) {
        try {
          // Validate input
          const { email, password } = loginSchema.parse(credentials);

          // Find user
          const user = await prisma.user.findUnique({
            where: { email: email.toLowerCase() },
            include: {
              farmer: { select: { id: true } },
              grocer: { select: { id: true } },
            },
          });

          if (!user || !user.password) {
            throw new Error("Invalid email or password");
          }

          // Check account status
          if (user.status === "SUSPENDED") {
            throw new Error("Account suspended. Please contact support.");
          }

          // Verify password
          const isValid = await verifyPassword(password, user.password);

          if (!isValid) {
            throw new Error("Invalid email or password");
          }

          // Return user object
          return {
            id: user.id,
            email: user.email,
            name: user.name,
            image: user.image,
            role: user.role,
            status: user.status,
          };
        } catch (error) {
          if (error instanceof z.ZodError) {
            throw new Error("Invalid credentials format");
          }
          throw error;
        }
      },
    }),

    // ─────────────────────────────────────────
    // Google OAuth Provider
    // ─────────────────────────────────────────
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
      allowDangerousEmailAccountLinking: true,
      profile(profile) {
        return {
          id: profile.sub,
          name: profile.name,
          email: profile.email,
          image: profile.picture,
          role: "GROCER" as UserRole, // Default role for OAuth
          status: "ACTIVE" as AccountStatus,
        };
      },
    }),

    // ─────────────────────────────────────────
    // Magic Link Email Provider
    // ─────────────────────────────────────────
    EmailProvider({
      server: {
        host: process.env.EMAIL_SERVER_HOST,
        port: Number(process.env.EMAIL_SERVER_PORT),
        auth: {
          user: process.env.EMAIL_SERVER_USER,
          pass: process.env.EMAIL_SERVER_PASSWORD,
        },
      },
      from: process.env.EMAIL_FROM,
      maxAge: 10 * 60, // 10 minutes
    }),
  ],

  // Callbacks
  callbacks: {
    // ─────────────────────────────────────────
    // Sign In Callback
    // ─────────────────────────────────────────
    async signIn({ user, account, profile }) {
      // Allow credentials sign in
      if (account?.provider === "credentials") {
        return true;
      }

      // For OAuth providers, check if user exists
      if (account?.provider === "google") {
        const existingUser = await prisma.user.findUnique({
          where: { email: user.email! },
        });

        // If user doesn't exist, they'll be created by the adapter
        // If they exist but are suspended, deny access
        if (existingUser?.status === "SUSPENDED") {
          return "/auth/error?error=AccountSuspended";
        }

        return true;
      }

      return true;
    },

    // ─────────────────────────────────────────
    // JWT Callback
    // ─────────────────────────────────────────
    async jwt({ token, user, trigger, session }) {
      // Initial sign in
      if (user) {
        token.id = user.id;
        token.email = user.email;
        token.name = user.name;
        token.role = user.role;
        token.status = user.status;

        // Fetch profile IDs
        const userWithProfile = await getUserWithProfile(user.id);
        if (userWithProfile) {
          token.farmerId = userWithProfile.farmer?.id;
          token.grocerId = userWithProfile.grocer?.id;
        }
      }

      // Handle session update (e.g., after profile completion)
      if (trigger === "update" && session) {
        token.name = session.name ?? token.name;
        token.role = session.role ?? token.role;
        token.farmerId = session.farmerId ?? token.farmerId;
        token.grocerId = session.grocerId ?? token.grocerId;
      }

      // Refresh user data periodically
      if (token.id) {
        const currentUser = await prisma.user.findUnique({
          where: { id: token.id },
          select: { status: true, role: true },
        });

        if (currentUser) {
          token.status = currentUser.status;
          token.role = currentUser.role;
        }
      }

      return token;
    },

    // ─────────────────────────────────────────
    // Session Callback
    // ─────────────────────────────────────────
    async session({ session, token }): Promise<Session> {
      return {
        ...session,
        user: {
          id: token.id,
          email: token.email,
          name: token.name,
          image: session.user?.image,
          role: token.role,
          status: token.status,
          farmerId: token.farmerId,
          grocerId: token.grocerId,
        },
      };
    },

    // ─────────────────────────────────────────
    // Redirect Callback
    // ─────────────────────────────────────────
    async redirect({ url, baseUrl }) {
      // Allow relative URLs
      if (url.startsWith("/")) {
        return `${baseUrl}${url}`;
      }

      // Allow URLs on the same origin
      if (new URL(url).origin === baseUrl) {
        return url;
      }

      return baseUrl;
    },
  },

  // Events
  events: {
    async signIn({ user, isNewUser }) {
      if (isNewUser) {
        console.log(`🆕 New user registered: ${user.email}`);
        // TODO: Send welcome email
        // TODO: Create notification
      } else {
        console.log(`👋 User signed in: ${user.email}`);
      }
    },

    async signOut({ token }) {
      console.log(`👋 User signed out: ${token?.email}`);
    },

    async createUser({ user }) {
      console.log(`✅ User created: ${user.email}`);
    },

    async linkAccount({ user, account }) {
      console.log(`🔗 Account linked: ${user.email} - ${account.provider}`);
    },
  },

  // Debug mode in development
  debug: process.env.NODE_ENV === "development",

  // Secret for JWT encryption
  secret: process.env.NEXTAUTH_SECRET,
};

// ============================================
// AUTH HELPER FUNCTIONS
// ============================================

/**
 * Get the current session on the server
 * Use this in Server Components and API routes
 */
export async function getSession() {
  return getServerSession(authOptions);
}

/**
 * Get the current user from session
 * Returns null if not authenticated
 */
export async function getCurrentUser() {
  const session = await getSession();
  return session?.user ?? null;
}

/**
 * Require authentication
 * Throws error if not authenticated
 */
export async function requireAuth() {
  const user = await getCurrentUser();

  if (!user) {
    throw new Error("Unauthorized");
  }

  return user;
}

/**
 * Require specific role(s)
 * Throws error if user doesn't have required role
 */
export async function requireRole(...roles: UserRole[]) {
  const user = await requireAuth();

  if (!roles.includes(user.role)) {
    throw new Error("Forbidden: Insufficient permissions");
  }

  return user;
}

/**
 * Require farmer role
 */
export async function requireFarmer() {
  const user = await requireRole("FARMER");

  if (!user.farmerId) {
    throw new Error("Farmer profile not found");
  }

  return { ...user, farmerId: user.farmerId };
}

/**
 * Require grocer role
 */
export async function requireGrocer() {
  const user = await requireRole("GROCER");

  if (!user.grocerId) {
    throw new Error("Grocer profile not found");
  }

  return { ...user, grocerId: user.grocerId };
}

/**
 * Require admin role
 */
export async function requireAdmin() {
  return requireRole("ADMIN");
}

/**
 * Check if user has specific role
 */
export async function hasRole(...roles: UserRole[]): Promise<boolean> {
  const user = await getCurrentUser();
  return user ? roles.includes(user.role) : false;
}

/**
 * Check if user is authenticated
 */
export async function isAuthenticated(): Promise<boolean> {
  const user = await getCurrentUser();
  return !!user;
}

// ============================================
// REGISTRATION FUNCTION
// ============================================

/**
 * Register a new user
 * Used by the registration API route
 */
export async function registerUser(data: z.infer<typeof registerSchema>) {
  const { name, email, password, role } = registerSchema.parse(data);

  // Check if user exists
  const existingUser = await prisma.user.findUnique({
    where: { email: email.toLowerCase() },
  });

  if (existingUser) {
    throw new Error("User with this email already exists");
  }

  // Hash password
  const hashedPassword = await hashPassword(password);

  // Create user with transaction
  const user = await prisma.$transaction(async (tx) => {
    // Create user
    const newUser = await tx.user.create({
      data: {
        name,
        email: email.toLowerCase(),
        password: hashedPassword,
        role: role as UserRole,
        status: "PENDING",
      },
    });

    // Create role-specific profile placeholder
    if (role === "FARMER") {
      await tx.farmer.create({
        data: {
          userId: newUser.id,
          farmName: `${name}'s Farm`,
          address: "",
          city: "",
          state: "",
          zipCode: "",
        },
      });
    } else if (role === "GROCER") {
      await tx.grocer.create({
        data: {
          userId: newUser.id,
          businessName: `${name}'s Business`,
          businessType: "Grocery Store",
          address: "",
          city: "",
          state: "",
          zipCode: "",
        },
      });
    }

    // Create welcome notification
    await tx.notification.create({
      data: {
        userId: newUser.id,
        type: "SYSTEM",
        title: "Welcome to Farm to Grocer!",
        message: "Complete your profile to start connecting with local partners.",
        link: "/onboarding",
      },
    });

    return newUser;
  });

  return {
    id: user.id,
    email: user.email,
    name: user.name,
    role: user.role,
  };
}

// ============================================
// PASSWORD RESET FUNCTIONS
// ============================================

/**
 * Generate password reset token
 */
export async function generatePasswordResetToken(email: string) {
  const user = await prisma.user.findUnique({
    where: { email: email.toLowerCase() },
  });

  if (!user) {
    // Don't reveal if user exists
    return { success: true };
  }

  // Generate token
  const token = crypto.randomUUID();
  const expires = new Date(Date.now() + 60 * 60 * 1000); // 1 hour

  // Store token
  await prisma.verificationToken.create({
    data: {
      identifier: email.toLowerCase(),
      token,
      expires,
    },
  });

  // TODO: Send password reset email
  console.log(`Password reset token for ${email}: ${token}`);

  return { success: true };
}

/**
 * Reset password with token
 */
export async function resetPassword(token: string, newPassword: string) {
  // Find token
  const verificationToken = await prisma.verificationToken.findUnique({
    where: { token },
  });

  if (!verificationToken) {
    throw new Error("Invalid or expired token");
  }

  if (verificationToken.expires < new Date()) {
    await prisma.verificationToken.delete({ where: { token } });
    throw new Error("Token has expired");
  }

  // Hash new password
  const hashedPassword = await hashPassword(newPassword);

  // Update user password
  await prisma.user.update({
    where: { email: verificationToken.identifier },
    data: { password: hashedPassword },
  });

  // Delete token
  await prisma.verificationToken.delete({ where: { token } });

  return { success: true };
}

// ============================================
// EXPORTS
// ============================================

export default authOptions;
