// Farm-to-Grocer MVP - Utility Functions
// Path: lib/utils.ts
// Generated by RJBot Orchestrator
//
// This file contains commonly used utility functions including:
// - cn() for Tailwind class merging (shadcn/ui pattern)
// - Formatters (currency, date, numbers)
// - String utilities
// - Validation helpers
// - Async utilities

import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// ============================================
// CLASS NAME UTILITIES
// ============================================

/**
 * Combines clsx and tailwind-merge for optimal class name handling
 * 
 * - clsx: Conditionally constructs className strings
 * - twMerge: Efficiently merges Tailwind CSS classes without conflicts
 * 
 * @example
 * cn("px-4 py-2", isActive && "bg-primary", className)
 * cn("text-red-500", "text-blue-500") // => "text-blue-500" (no conflict)
 * cn({ "font-bold": isBold, "italic": isItalic })
 */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}

// ============================================
// CURRENCY FORMATTING
// ============================================

/**
 * Format a number as USD currency
 * 
 * @example
 * formatCurrency(1234.56) // => "$1,234.56"
 * formatCurrency(1000) // => "$1,000.00"
 */
export function formatCurrency(
  amount: number,
  options?: Intl.NumberFormatOptions
): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
    ...options,
  }).format(amount);
}

/**
 * Format currency with compact notation for large numbers
 * 
 * @example
 * formatCurrencyCompact(1500000) // => "$1.5M"
 * formatCurrencyCompact(2500) // => "$2.5K"
 */
export function formatCurrencyCompact(amount: number): string {
  if (amount >= 1000000) {
    return `$${(amount / 1000000).toFixed(1)}M`;
  }
  if (amount >= 1000) {
    return `$${(amount / 1000).toFixed(1)}K`;
  }
  return formatCurrency(amount);
}

/**
 * Parse a currency string to number
 * 
 * @example
 * parseCurrency("$1,234.56") // => 1234.56
 */
export function parseCurrency(value: string): number {
  return parseFloat(value.replace(/[^0-9.-]+/g, "")) || 0;
}

// ============================================
// DATE FORMATTING
// ============================================

/**
 * Format a date with various presets
 * 
 * @example
 * formatDate(new Date()) // => "Mar 8, 2026"
 * formatDate(new Date(), "long") // => "March 8, 2026"
 * formatDate(new Date(), "short") // => "3/8/26"
 */
export function formatDate(
  date: Date | string | number,
  format: "short" | "medium" | "long" | "full" = "medium"
): string {
  const d = new Date(date);

  if (isNaN(d.getTime())) {
    return "Invalid date";
  }

  const formats: Record<string, Intl.DateTimeFormatOptions> = {
    short: { month: "numeric", day: "numeric", year: "2-digit" },
    medium: { month: "short", day: "numeric", year: "numeric" },
    long: { month: "long", day: "numeric", year: "numeric" },
    full: { weekday: "long", month: "long", day: "numeric", year: "numeric" },
  };

  return new Intl.DateTimeFormat("en-US", formats[format]).format(d);
}

/**
 * Format a date with time
 * 
 * @example
 * formatDateTime(new Date()) // => "Mar 8, 2026, 2:30 PM"
 */
export function formatDateTime(
  date: Date | string | number,
  options?: Intl.DateTimeFormatOptions
): string {
  const d = new Date(date);

  if (isNaN(d.getTime())) {
    return "Invalid date";
  }

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
    ...options,
  }).format(d);
}

/**
 * Format a date as relative time (e.g., "2 hours ago")
 * 
 * @example
 * formatRelativeTime(new Date(Date.now() - 3600000)) // => "1 hour ago"
 * formatRelativeTime(new Date(Date.now() - 86400000)) // => "1 day ago"
 */
export function formatRelativeTime(date: Date | string | number): string {
  const d = new Date(date);

  if (isNaN(d.getTime())) {
    return "Invalid date";
  }

  const now = new Date();
  const diffInSeconds = Math.floor((now.getTime() - d.getTime()) / 1000);

  // Future dates
  if (diffInSeconds < 0) {
    return formatDate(d);
  }

  // Less than a minute
  if (diffInSeconds < 60) {
    return "Just now";
  }

  // Less than an hour
  if (diffInSeconds < 3600) {
    const minutes = Math.floor(diffInSeconds / 60);
    return `${minutes} minute${minutes > 1 ? "s" : ""} ago`;
  }

  // Less than a day
  if (diffInSeconds < 86400) {
    const hours = Math.floor(diffInSeconds / 3600);
    return `${hours} hour${hours > 1 ? "s" : ""} ago`;
  }

  // Less than a week
  if (diffInSeconds < 604800) {
    const days = Math.floor(diffInSeconds / 86400);
    return `${days} day${days > 1 ? "s" : ""} ago`;
  }

  // Less than a month
  if (diffInSeconds < 2592000) {
    const weeks = Math.floor(diffInSeconds / 604800);
    return `${weeks} week${weeks > 1 ? "s" : ""} ago`;
  }

  // Older than a month, show full date
  return formatDate(d);
}

/**
 * Format time only
 * 
 * @example
 * formatTime(new Date()) // => "2:30 PM"
 */
export function formatTime(date: Date | string | number): string {
  const d = new Date(date);

  if (isNaN(d.getTime())) {
    return "Invalid time";
  }

  return new Intl.DateTimeFormat("en-US", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  }).format(d);
}

/**
 * Check if a date is today
 */
export function isToday(date: Date | string | number): boolean {
  const d = new Date(date);
  const today = new Date();
  return (
    d.getDate() === today.getDate() &&
    d.getMonth() === today.getMonth() &&
    d.getFullYear() === today.getFullYear()
  );
}

/**
 * Check if a date is in the past
 */
export function isPast(date: Date | string | number): boolean {
  return new Date(date).getTime() < Date.now();
}

/**
 * Check if a date is in the future
 */
export function isFuture(date: Date | string | number): boolean {
  return new Date(date).getTime() > Date.now();
}

// ============================================
// NUMBER FORMATTING
// ============================================

/**
 * Format a number with locale-specific separators
 * 
 * @example
 * formatNumber(1234567) // => "1,234,567"
 */
export function formatNumber(
  value: number,
  options?: Intl.NumberFormatOptions
): string {
  return new Intl.NumberFormat("en-US", options).format(value);
}

/**
 * Format a number as a percentage
 * 
 * @example
 * formatPercent(0.1234) // => "12.34%"
 * formatPercent(0.5, 0) // => "50%"
 */
export function formatPercent(
  value: number,
  decimals: number = 2
): string {
  return new Intl.NumberFormat("en-US", {
    style: "percent",
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  }).format(value);
}

/**
 * Format a number with compact notation
 * 
 * @example
 * formatCompact(1500000) // => "1.5M"
 * formatCompact(2500) // => "2.5K"
 */
export function formatCompact(value: number): string {
  return new Intl.NumberFormat("en-US", {
    notation: "compact",
    maximumFractionDigits: 1,
  }).format(value);
}

/**
 * Clamp a number between min and max
 * 
 * @example
 * clamp(150, 0, 100) // => 100
 * clamp(-10, 0, 100) // => 0
 */
export function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

/**
 * Round a number to specified decimal places
 * 
 * @example
 * roundTo(3.14159, 2) // => 3.14
 */
export function roundTo(value: number, decimals: number = 2): number {
  const factor = Math.pow(10, decimals);
  return Math.round(value * factor) / factor;
}

// ============================================
// STRING UTILITIES
// ============================================

/**
 * Capitalize the first letter of a string
 * 
 * @example
 * capitalize("hello world") // => "Hello world"
 */
export function capitalize(str: string): string {
  if (!str) return "";
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Convert string to title case
 * 
 * @example
 * titleCase("hello world") // => "Hello World"
 */
export function titleCase(str: string): string {
  if (!str) return "";
  return str
    .toLowerCase()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/**
 * Convert string to slug format
 * 
 * @example
 * slugify("Hello World!") // => "hello-world"
 */
export function slugify(str: string): string {
  return str
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Truncate a string to a specified length
 * 
 * @example
 * truncate("Hello World", 8) // => "Hello..."
 */
export function truncate(str: string, length: number, suffix: string = "..."): string {
  if (!str || str.length <= length) return str;
  return str.slice(0, length - suffix.length).trim() + suffix;
}

/**
 * Generate initials from a name
 * 
 * @example
 * getInitials("John Doe") // => "JD"
 * getInitials("John") // => "J"
 */
export function getInitials(name: string, maxLength: number = 2): string {
  if (!name) return "";
  return name
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase())
    .slice(0, maxLength)
    .join("");
}

/**
 * Pluralize a word based on count
 * 
 * @example
 * pluralize(1, "item") // => "1 item"
 * pluralize(5, "item") // => "5 items"
 * pluralize(0, "item", "items", "no items") // => "no items"
 */
export function pluralize(
  count: number,
  singular: string,
  plural?: string,
  zero?: string
): string {
  if (count === 0 && zero) return zero;
  if (count === 1) return `${count} ${singular}`;
  return `${count} ${plural || singular + "s"}`;
}

/**
 * Strip HTML tags from a string
 * 
 * @example
 * stripHtml("<p>Hello <b>World</b></p>") // => "Hello World"
 */
export function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, "");
}

// ============================================
// VALIDATION UTILITIES
// ============================================

/**
 * Check if a value is empty (null, undefined, empty string, empty array, empty object)
 */
export function isEmpty(value: unknown): boolean {
  if (value === null || value === undefined) return true;
  if (typeof value === "string") return value.trim().length === 0;
  if (Array.isArray(value)) return value.length === 0;
  if (typeof value === "object") return Object.keys(value).length === 0;
  return false;
}

/**
 * Check if a string is a valid email
 */
export function isValidEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

/**
 * Check if a string is a valid phone number (US format)
 */
export function isValidPhone(phone: string): boolean {
  const phoneRegex = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/;
  return phoneRegex.test(phone);
}

/**
 * Check if a string is a valid URL
 */
export function isValidUrl(url: string): boolean {
  try {
    new URL(url);
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if a string is a valid ZIP code (US format)
 */
export function isValidZipCode(zip: string): boolean {
  const zipRegex = /^\d{5}(-\d{4})?$/;
  return zipRegex.test(zip);
}

// ============================================
// PHONE FORMATTING
// ============================================

/**
 * Format a phone number to (XXX) XXX-XXXX format
 * 
 * @example
 * formatPhone("1234567890") // => "(123) 456-7890"
 */
export function formatPhone(phone: string): string {
  const cleaned = phone.replace(/\D/g, "");
  const match = cleaned.match(/^(\d{3})(\d{3})(\d{4})$/);
  if (match) {
    return `(${match[1]}) ${match[2]}-${match[3]}`;
  }
  return phone;
}

// ============================================
// ARRAY UTILITIES
// ============================================

/**
 * Remove duplicates from an array
 * 
 * @example
 * unique([1, 2, 2, 3, 3, 3]) // => [1, 2, 3]
 */
export function unique<T>(arr: T[]): T[] {
  return [...new Set(arr)];
}

/**
 * Group an array by a key
 * 
 * @example
 * groupBy([{type: 'a', val: 1}, {type: 'b', val: 2}, {type: 'a', val: 3}], 'type')
 * // => { a: [{type: 'a', val: 1}, {type: 'a', val: 3}], b: [{type: 'b', val: 2}] }
 */
export function groupBy<T extends Record<string, any>>(
  arr: T[],
  key: keyof T
): Record<string, T[]> {
  return arr.reduce((acc, item) => {
    const groupKey = String(item[key]);
    if (!acc[groupKey]) {
      acc[groupKey] = [];
    }
    acc[groupKey].push(item);
    return acc;
  }, {} as Record<string, T[]>);
}

/**
 * Chunk an array into smaller arrays
 * 
 * @example
 * chunk([1, 2, 3, 4, 5], 2) // => [[1, 2], [3, 4], [5]]
 */
export function chunk<T>(arr: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let i = 0; i < arr.length; i += size) {
    chunks.push(arr.slice(i, i + size));
  }
  return chunks;
}

/**
 * Shuffle an array (Fisher-Yates algorithm)
 */
export function shuffle<T>(arr: T[]): T[] {
  const result = [...arr];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j]!, result[i]!];
  }
  return result;
}

// ============================================
// OBJECT UTILITIES
// ============================================

/**
 * Deep clone an object
 */
export function deepClone<T>(obj: T): T {
  return JSON.parse(JSON.stringify(obj));
}

/**
 * Pick specific keys from an object
 * 
 * @example
 * pick({ a: 1, b: 2, c: 3 }, ['a', 'c']) // => { a: 1, c: 3 }
 */
export function pick<T extends object, K extends keyof T>(
  obj: T,
  keys: K[]
): Pick<T, K> {
  return keys.reduce((acc, key) => {
    if (key in obj) {
      acc[key] = obj[key];
    }
    return acc;
  }, {} as Pick<T, K>);
}

/**
 * Omit specific keys from an object
 * 
 * @example
 * omit({ a: 1, b: 2, c: 3 }, ['b']) // => { a: 1, c: 3 }
 */
export function omit<T extends object, K extends keyof T>(
  obj: T,
  keys: K[]
): Omit<T, K> {
  const result = { ...obj };
  keys.forEach((key) => delete result[key]);
  return result;
}

// ============================================
// ASYNC UTILITIES
// ============================================

/**
 * Sleep for a specified duration
 * 
 * @example
 * await sleep(1000) // Wait 1 second
 */
export function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Debounce a function
 */
export function debounce<T extends (...args: any[]) => any>(
  fn: T,
  delay: number
): (...args: Parameters<T>) => void {
  let timeoutId: NodeJS.Timeout;
  return (...args: Parameters<T>) => {
    clearTimeout(timeoutId);
    timeoutId = setTimeout(() => fn(...args), delay);
  };
}

/**
 * Throttle a function
 */
export function throttle<T extends (...args: any[]) => any>(
  fn: T,
  limit: number
): (...args: Parameters<T>) => void {
  let inThrottle = false;
  return (...args: Parameters<T>) => {
    if (!inThrottle) {
      fn(...args);
      inThrottle = true;
      setTimeout(() => (inThrottle = false), limit);
    }
  };
}

/**
 * Retry a function with exponential backoff
 */
export async function retry<T>(
  fn: () => Promise<T>,
  options: {
    maxAttempts?: number;
    delay?: number;
    backoffFactor?: number;
  } = {}
): Promise<T> {
  const { maxAttempts = 3, delay = 1000, backoffFactor = 2 } = options;
  let lastError: Error;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error as Error;
      if (attempt < maxAttempts) {
        await sleep(delay * Math.pow(backoffFactor, attempt - 1));
      }
    }
  }

  throw lastError!;
}

// ============================================
// URL UTILITIES
// ============================================

/**
 * Build a URL with query parameters
 * 
 * @example
 * buildUrl("/api/products", { page: 1, limit: 10 })
 * // => "/api/products?page=1&limit=10"
 */
export function buildUrl(
  base: string,
  params?: Record<string, string | number | boolean | undefined | null>
): string {
  if (!params) return base;

  const searchParams = new URLSearchParams();
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== null && value !== "") {
      searchParams.append(key, String(value));
    }
  });

  const queryString = searchParams.toString();
  return queryString ? `${base}?${queryString}` : base;
}

/**
 * Parse query parameters from a URL
 */
export function parseQueryParams(url: string): Record<string, string> {
  const params: Record<string, string> = {};
  const searchParams = new URL(url, "http://dummy.com").searchParams;
  searchParams.forEach((value, key) => {
    params[key] = value;
  });
  return params;
}

// ============================================
// ID GENERATION
// ============================================

/**
 * Generate a random ID
 * 
 * @example
 * generateId() // => "x7k9m2p4"
 * generateId(16) // => "x7k9m2p4q1w3e5r8"
 */
export function generateId(length: number = 8): string {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  let result = "";
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// ============================================
// FILE UTILITIES
// ============================================

/**
 * Format file size to human readable format
 * 
 * @example
 * formatFileSize(1024) // => "1 KB"
 * formatFileSize(1048576) // => "1 MB"
 */
export function formatFileSize(bytes: number): string {
  if (bytes === 0) return "0 Bytes";

  const k = 1024;
  const sizes = ["Bytes", "KB", "MB", "GB", "TB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));

  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
}

/**
 * Get file extension from filename
 * 
 * @example
 * getFileExtension("document.pdf") // => "pdf"
 */
export function getFileExtension(filename: string): string {
  return filename.slice(((filename.lastIndexOf(".") - 1) >>> 0) + 2);
}

// ============================================
// ENVIRONMENT UTILITIES
// ============================================

/**
 * Check if running on server
 */
export const isServer = typeof window === "undefined";

/**
 * Check if running on client
 */
export const isClient = typeof window !== "undefined";

/**
 * Check if in development mode
 */
export const isDev = process.env.NODE_ENV === "development";

/**
 * Check if in production mode
 */
export const isProd = process.env.NODE_ENV === "production";

// ============================================
// EXPORTS
// ============================================

export default {
  cn,
  formatCurrency,
  formatCurrencyCompact,
  parseCurrency,
  formatDate,
  formatDateTime,
  formatRelativeTime,
  formatTime,
  isToday,
  isPast,
  isFuture,
  formatNumber,
  formatPercent,
  formatCompact,
  clamp,
  roundTo,
  capitalize,
  titleCase,
  slugify,
  truncate,
  getInitials,
  pluralize,
  stripHtml,
  isEmpty,
  isValidEmail,
  isValidPhone,
  isValidUrl,
  isValidZipCode,
  formatPhone,
  unique,
  groupBy,
  chunk,
  shuffle,
  deepClone,
  pick,
  omit,
  sleep,
  debounce,
  throttle,
  retry,
  buildUrl,
  parseQueryParams,
  generateId,
  formatFileSize,
  getFileExtension,
  isServer,
  isClient,
  isDev,
  isProd,
};
