// Farm-to-Grocer MVP - Login Page
// Path: app/(auth)/login/page.tsx
// Generated by RJBot Orchestrator
//
// A comprehensive login page with:
// - Email/password credentials login
// - Google OAuth integration
// - Magic link email option
// - Form validation with Zod
// - Server Actions for authentication
// - Loading states and error handling
// - Responsive design

import { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { LoginForm } from "./login-form";
import { Leaf } from "lucide-react";

// ============================================
// METADATA
// ============================================

export const metadata: Metadata = {
  title: "Sign In",
  description: "Sign in to your Farm to Grocer account to manage your orders and connect with local partners.",
};

// ============================================
// LOGIN PAGE COMPONENT
// ============================================

interface LoginPageProps {
  searchParams: {
    callbackUrl?: string;
    error?: string;
  };
}

export default async function LoginPage({ searchParams }: LoginPageProps) {
  // Check if user is already logged in
  const session = await getServerSession(authOptions);

  if (session) {
    // Redirect to appropriate dashboard based on role
    const redirectUrl =
      session.user.role === "FARMER"
        ? "/farmer"
        : session.user.role === "GROCER"
        ? "/grocer"
        : "/";
    redirect(redirectUrl);
  }

  const callbackUrl = searchParams.callbackUrl || "/";
  const error = searchParams.error;

  // Map NextAuth error codes to user-friendly messages
  const errorMessages: Record<string, string> = {
    CredentialsSignin: "Invalid email or password. Please try again.",
    OAuthSignin: "Error connecting to the authentication provider.",
    OAuthCallback: "Error during authentication callback.",
    OAuthCreateAccount: "Could not create account with this provider.",
    EmailCreateAccount: "Could not create account with this email.",
    Callback: "Authentication callback error.",
    OAuthAccountNotLinked: "This email is already associated with another account.",
    EmailSignin: "Error sending the verification email.",
    SessionRequired: "Please sign in to access this page.",
    Default: "An unexpected error occurred. Please try again.",
  };

  const errorMessage = error ? errorMessages[error] || errorMessages.Default : null;

  return (
    <div className="min-h-screen flex">
      {/* Left Side - Branding/Image (hidden on mobile) */}
      <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-farm-600 via-farm-700 to-farm-800 relative overflow-hidden">
        {/* Background Pattern */}
        <div className="absolute inset-0 opacity-10">
          <svg className="w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none">
            <defs>
              <pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse">
                <path d="M 10 0 L 0 0 0 10" fill="none" stroke="white" strokeWidth="0.5" />
              </pattern>
            </defs>
            <rect width="100" height="100" fill="url(#grid)" />
          </svg>
        </div>

        {/* Content */}
        <div className="relative z-10 flex flex-col justify-center px-12 text-white">
          {/* Logo */}
          <div className="flex items-center gap-3 mb-8">
            <div className="p-3 bg-white/10 rounded-xl backdrop-blur-sm">
              <Leaf className="h-10 w-10" />
            </div>
            <span className="text-3xl font-bold">Farm to Grocer</span>
          </div>

          {/* Tagline */}
          <h1 className="text-4xl font-bold leading-tight mb-4">
            Connect with Local Farmers.
            <br />
            <span className="text-farm-200">Grow Your Business.</span>
          </h1>

          <p className="text-lg text-farm-100 max-w-md mb-8">
            Join thousands of farmers and grocers building sustainable food systems together.
          </p>

          {/* Stats */}
          <div className="grid grid-cols-3 gap-6 max-w-md">
            <div>
              <p className="text-3xl font-bold">500+</p>
              <p className="text-sm text-farm-200">Local Farmers</p>
            </div>
            <div>
              <p className="text-3xl font-bold">1,200+</p>
              <p className="text-sm text-farm-200">Grocers</p>
            </div>
            <div>
              <p className="text-3xl font-bold">$2M+</p>
              <p className="text-sm text-farm-200">Monthly Sales</p>
            </div>
          </div>

          {/* Testimonial */}
          <div className="mt-12 p-6 bg-white/10 rounded-xl backdrop-blur-sm max-w-md">
            <p className="text-farm-100 italic mb-4">
              "Farm to Grocer has transformed how we source produce. Direct connections with local farmers mean fresher products and better margins."
            </p>
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-full bg-farm-500 flex items-center justify-center font-bold">
                JM
              </div>
              <div>
                <p className="font-medium">John Martinez</p>
                <p className="text-sm text-farm-200">Fresh Market Grocery</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Right Side - Login Form */}
      <div className="flex-1 flex flex-col justify-center px-6 py-12 lg:px-12">
        <div className="mx-auto w-full max-w-md">
          {/* Mobile Logo */}
          <div className="lg:hidden flex items-center justify-center gap-2 mb-8">
            <Leaf className="h-8 w-8 text-primary" />
            <span className="text-2xl font-bold text-primary">Farm to Grocer</span>
          </div>

          {/* Header */}
          <div className="text-center lg:text-left mb-8">
            <h2 className="text-2xl font-bold tracking-tight">
              Welcome back
            </h2>
            <p className="text-muted-foreground mt-2">
              Sign in to your account to continue
            </p>
          </div>

          {/* Error Message */}
          {errorMessage && (
            <div className="mb-6 p-4 rounded-lg bg-destructive/10 border border-destructive/20 text-destructive text-sm">
              <p className="font-medium">Authentication Error</p>
              <p>{errorMessage}</p>
            </div>
          )}

          {/* Login Form Component */}
          <LoginForm callbackUrl={callbackUrl} />

          {/* Sign Up Link */}
          <p className="mt-8 text-center text-sm text-muted-foreground">
            Don't have an account?{" "}
            <Link
              href="/register"
              className="font-medium text-primary hover:underline"
            >
              Create an account
            </Link>
          </p>

          {/* Terms */}
          <p className="mt-4 text-center text-xs text-muted-foreground">
            By signing in, you agree to our{" "}
            <Link href="/terms" className="underline hover:text-foreground">
              Terms of Service
            </Link>{" "}
            and{" "}
            <Link href="/privacy" className="underline hover:text-foreground">
              Privacy Policy
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
