// Farm-to-Grocer MVP - Registration Page
// Path: app/(auth)/register/page.tsx
// Generated by RJBot Orchestrator
//
// A comprehensive registration page with:
// - Multi-step form (Role selection → Account details → Business info)
// - React Hook Form + Zod validation
// - Server Actions for secure registration
// - Password strength indicator
// - Google OAuth option
// - Responsive split-screen design

import { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { RegisterForm } from "./register-form";
import { Leaf, Truck, Store, CheckCircle } from "lucide-react";

// ============================================
// METADATA
// ============================================

export const metadata: Metadata = {
  title: "Create Account",
  description:
    "Join Farm to Grocer - Connect with local farmers and grocers to build sustainable food systems.",
};

// ============================================
// REGISTRATION PAGE COMPONENT
// ============================================

interface RegisterPageProps {
  searchParams: {
    role?: "farmer" | "grocer";
    error?: string;
    step?: string;
  };
}

export default async function RegisterPage({ searchParams }: RegisterPageProps) {
  // Check if user is already logged in
  const session = await getServerSession(authOptions);

  if (session) {
    // Redirect to appropriate dashboard based on role
    const redirectUrl =
      session.user.role === "FARMER"
        ? "/farmer"
        : session.user.role === "GROCER"
        ? "/grocer"
        : "/";
    redirect(redirectUrl);
  }

  const preselectedRole = searchParams.role;
  const error = searchParams.error;

  // Map error codes to user-friendly messages
  const errorMessages: Record<string, string> = {
    EmailExists: "An account with this email already exists. Please sign in instead.",
    InvalidData: "Please check your information and try again.",
    ServerError: "Something went wrong. Please try again later.",
    PasswordMismatch: "Passwords do not match.",
    WeakPassword: "Password does not meet security requirements.",
    Default: "An unexpected error occurred. Please try again.",
  };

  const errorMessage = error ? errorMessages[error] || errorMessages.Default : null;

  return (
    <div className="min-h-screen flex">
      {/* Left Side - Branding/Benefits (hidden on mobile) */}
      <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-farm-600 via-farm-700 to-farm-800 relative overflow-hidden">
        {/* Background Pattern */}
        <div className="absolute inset-0 opacity-10">
          <svg className="w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none">
            <defs>
              <pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse">
                <path d="M 10 0 L 0 0 0 10" fill="none" stroke="white" strokeWidth="0.5" />
              </pattern>
            </defs>
            <rect width="100" height="100" fill="url(#grid)" />
          </svg>
        </div>

        {/* Content */}
        <div className="relative z-10 flex flex-col justify-center px-12 text-white">
          {/* Logo */}
          <div className="flex items-center gap-3 mb-8">
            <div className="p-3 bg-white/10 rounded-xl backdrop-blur-sm">
              <Leaf className="h-10 w-10" />
            </div>
            <span className="text-3xl font-bold">Farm to Grocer</span>
          </div>

          {/* Tagline */}
          <h1 className="text-4xl font-bold leading-tight mb-4">
            Start Your Journey
            <br />
            <span className="text-farm-200">With Local Partners</span>
          </h1>

          <p className="text-lg text-farm-100 max-w-md mb-10">
            Whether you're a farmer looking to expand your market or a grocer seeking fresh local produce, we've got you covered.
          </p>

          {/* Benefits */}
          <div className="space-y-6 max-w-md">
            <h3 className="text-sm font-semibold uppercase tracking-wider text-farm-200">
              Why Join Farm to Grocer?
            </h3>

            {/* Farmer Benefits */}
            <div className="p-4 bg-white/10 rounded-xl backdrop-blur-sm">
              <div className="flex items-center gap-3 mb-3">
                <div className="p-2 bg-farm-500 rounded-lg">
                  <Truck className="h-5 w-5" />
                </div>
                <h4 className="font-semibold">For Farmers</h4>
              </div>
              <ul className="space-y-2 text-sm text-farm-100">
                <li className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-farm-300" />
                  Direct access to local grocers
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-farm-300" />
                  Fair pricing, no middlemen
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-farm-300" />
                  Easy inventory management
                </li>
              </ul>
            </div>

            {/* Grocer Benefits */}
            <div className="p-4 bg-white/10 rounded-xl backdrop-blur-sm">
              <div className="flex items-center gap-3 mb-3">
                <div className="p-2 bg-farm-500 rounded-lg">
                  <Store className="h-5 w-5" />
                </div>
                <h4 className="font-semibold">For Grocers</h4>
              </div>
              <ul className="space-y-2 text-sm text-farm-100">
                <li className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-farm-300" />
                  Fresh, locally-sourced produce
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-farm-300" />
                  Competitive wholesale prices
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-farm-300" />
                  Reliable delivery scheduling
                </li>
              </ul>
            </div>
          </div>

          {/* Trust Badges */}
          <div className="mt-10 flex items-center gap-6 text-sm text-farm-200">
            <div className="flex items-center gap-2">
              <CheckCircle className="h-4 w-4" />
              <span>Free to join</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle className="h-4 w-4" />
              <span>No hidden fees</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle className="h-4 w-4" />
              <span>Cancel anytime</span>
            </div>
          </div>
        </div>
      </div>

      {/* Right Side - Registration Form */}
      <div className="flex-1 flex flex-col justify-center px-6 py-12 lg:px-12 overflow-y-auto">
        <div className="mx-auto w-full max-w-md">
          {/* Mobile Logo */}
          <div className="lg:hidden flex items-center justify-center gap-2 mb-8">
            <Leaf className="h-8 w-8 text-primary" />
            <span className="text-2xl font-bold text-primary">Farm to Grocer</span>
          </div>

          {/* Header */}
          <div className="text-center lg:text-left mb-8">
            <h2 className="text-2xl font-bold tracking-tight">
              Create your account
            </h2>
            <p className="text-muted-foreground mt-2">
              Get started in just a few minutes
            </p>
          </div>

          {/* Error Message */}
          {errorMessage && (
            <div className="mb-6 p-4 rounded-lg bg-destructive/10 border border-destructive/20 text-destructive text-sm">
              <p className="font-medium">Registration Error</p>
              <p>{errorMessage}</p>
            </div>
          )}

          {/* Registration Form Component */}
          <RegisterForm preselectedRole={preselectedRole} />

          {/* Sign In Link */}
          <p className="mt-8 text-center text-sm text-muted-foreground">
            Already have an account?{" "}
            <Link
              href="/login"
              className="font-medium text-primary hover:underline"
            >
              Sign in
            </Link>
          </p>

          {/* Terms */}
          <p className="mt-4 text-center text-xs text-muted-foreground">
            By creating an account, you agree to our{" "}
            <Link href="/terms" className="underline hover:text-foreground">
              Terms of Service
            </Link>{" "}
            and{" "}
            <Link href="/privacy" className="underline hover:text-foreground">
              Privacy Policy
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
