// Farm-to-Grocer MVP - Farmer Products Management Page
// Path: app/(dashboard)/farmer/products/page.tsx
// Generated by RJBot Orchestrator
//
// A comprehensive product management page with:
// - Product listing with grid/list view toggle
// - Search, filter, and sort functionality
// - Bulk actions (delete, update status)
// - Add/Edit product modal
// - Pagination
// - Loading and empty states

import { redirect } from "next/navigation";
import Link from "next/link";
import {
  Plus,
  Search,
  Grid3X3,
  List,
  MoreHorizontal,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Package,
  ArrowUpDown,
  ChevronLeft,
  ChevronRight,
  Leaf,
  AlertCircle,
  CheckCircle,
  Download,
  Upload,
} from "lucide-react";

import { requireFarmer } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { formatCurrency, formatDate } from "@/lib/utils";
import {
  ProductCategory,
  ProductStatus,
  ProductCategoryLabels,
  ProductStatusLabels,
} from "@/types";

// Components
import { Button } from "@/components/ui/Button";
import { Card, CardContent } from "@/components/ui/Card";

// ============================================
// METADATA
// ============================================

export const metadata = {
  title: "My Products",
  description: "Manage your farm products, inventory, and pricing.",
};

// ============================================
// TYPES
// ============================================

interface SearchParams {
  search?: string;
  category?: ProductCategory | "all";
  status?: ProductStatus | "all";
  sort?: string;
  order?: "asc" | "desc";
  page?: string;
  view?: "grid" | "list";
}

// ============================================
// DATA FETCHING
// ============================================

async function getProducts(
  farmerId: string,
  searchParams: SearchParams
) {
  const {
    search = "",
    category = "all",
    status = "all",
    sort = "createdAt",
    order = "desc",
    page = "1",
  } = searchParams;

  const pageSize = 12;
  const currentPage = parseInt(page, 10) || 1;
  const skip = (currentPage - 1) * pageSize;

  // Build where clause
  const where: any = {
    farmerId,
  };

  if (search) {
    where.OR = [
      { name: { contains: search, mode: "insensitive" } },
      { description: { contains: search, mode: "insensitive" } },
      { tags: { has: search } },
    ];
  }

  if (category && category !== "all") {
    where.category = category;
  }

  if (status && status !== "all") {
    where.status = status;
  }

  // Build orderBy
  const orderBy: any = {};
  const validSortFields = ["name", "pricePerUnit", "availableQty", "createdAt", "updatedAt"];
  if (validSortFields.includes(sort)) {
    orderBy[sort] = order;
  } else {
    orderBy.createdAt = "desc";
  }

  // Execute queries in parallel
  const [products, totalCount, stats] = await Promise.all([
    prisma.product.findMany({
      where,
      orderBy,
      skip,
      take: pageSize,
      include: {
        _count: {
          select: { orderItems: true },
        },
      },
    }),
    prisma.product.count({ where }),
    prisma.product.groupBy({
      by: ["status"],
      where: { farmerId },
      _count: true,
    }),
  ]);

  const totalPages = Math.ceil(totalCount / pageSize);

  // Calculate stats
  const statusCounts = {
    all: await prisma.product.count({ where: { farmerId } }),
    ACTIVE: 0,
    DRAFT: 0,
    OUT_OF_STOCK: 0,
    DISCONTINUED: 0,
  };

  stats.forEach((s) => {
    statusCounts[s.status as keyof typeof statusCounts] = s._count;
  });

  return {
    products,
    pagination: {
      currentPage,
      totalPages,
      totalCount,
      pageSize,
      hasNext: currentPage < totalPages,
      hasPrev: currentPage > 1,
    },
    stats: statusCounts,
  };
}

// ============================================
// PRODUCT TABLE ROW COMPONENT
// ============================================

interface ProductRowProps {
  product: any;
}

function ProductRow({ product }: ProductRowProps) {
  const primaryImage = product.images?.[0] || "/images/placeholder-product.jpg";

  return (
    <tr className="border-b hover:bg-muted/50 transition-colors">
      {/* Checkbox */}
      <td className="px-4 py-3">
        <input
          type="checkbox"
          name="productIds"
          value={product.id}
          className="rounded border-input"
        />
      </td>

      {/* Product */}
      <td className="px-4 py-3">
        <div className="flex items-center gap-3">
          <div className="h-12 w-12 rounded-lg overflow-hidden bg-muted flex-shrink-0">
            <img
              src={primaryImage}
              alt={product.name}
              className="h-full w-full object-cover"
            />
          </div>
          <div className="min-w-0">
            <Link
              href={`/farmer/products/${product.id}`}
              className="font-medium hover:text-primary transition-colors line-clamp-1"
            >
              {product.name}
            </Link>
            <p className="text-sm text-muted-foreground line-clamp-1">
              {ProductCategoryLabels[product.category as ProductCategory]}
              {product.isOrganic && (
                <span className="ml-2 inline-flex items-center text-green-600">
                  <Leaf className="h-3 w-3 mr-0.5" />
                  Organic
                </span>
              )}
            </p>
          </div>
        </div>
      </td>

      {/* Status */}
      <td className="px-4 py-3">
        <StatusBadge status={product.status} />
      </td>

      {/* Price */}
      <td className="px-4 py-3">
        <span className="font-medium">{formatCurrency(product.pricePerUnit)}</span>
        <span className="text-sm text-muted-foreground">/{product.unit.toLowerCase()}</span>
      </td>

      {/* Stock */}
      <td className="px-4 py-3">
        <div className="flex items-center gap-2">
          <span
            className={
              product.availableQty < 10
                ? "text-amber-600 font-medium"
                : product.availableQty === 0
                  ? "text-destructive font-medium"
                  : ""
            }
          >
            {product.availableQty}
          </span>
          {product.availableQty < 10 && product.availableQty > 0 && (
            <AlertCircle className="h-4 w-4 text-amber-500" />
          )}
        </div>
      </td>

      {/* Orders */}
      <td className="px-4 py-3 text-center">
        <span className="text-sm">{product._count.orderItems}</span>
      </td>

      {/* Updated */}
      <td className="px-4 py-3">
        <span className="text-sm text-muted-foreground">
          {formatDate(product.updatedAt, "short")}
        </span>
      </td>

      {/* Actions */}
      <td className="px-4 py-3">
        <div className="flex items-center gap-1">
          <Button variant="ghost" size="icon-sm" asChild>
            <Link href={`/farmer/products/${product.id}/edit`}>
              <Edit className="h-4 w-4" />
            </Link>
          </Button>
          <ProductActionsMenu product={product} />
        </div>
      </td>
    </tr>
  );
}

// ============================================
// STATUS BADGE COMPONENT
// ============================================

function StatusBadge({ status }: { status: ProductStatus }) {
  const config: Record<ProductStatus, { className: string; icon: React.ReactNode }> = {
    ACTIVE: {
      className: "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400",
      icon: <CheckCircle className="h-3 w-3" />,
    },
    DRAFT: {
      className: "bg-gray-100 text-gray-800 dark:bg-gray-900/30 dark:text-gray-400",
      icon: <Edit className="h-3 w-3" />,
    },
    OUT_OF_STOCK: {
      className: "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400",
      icon: <AlertCircle className="h-3 w-3" />,
    },
    DISCONTINUED: {
      className: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400",
      icon: <EyeOff className="h-3 w-3" />,
    },
  };

  const { className, icon } = config[status];

  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium ${className}`}
    >
      {icon}
      {ProductStatusLabels[status]}
    </span>
  );
}

// ============================================
// PRODUCT ACTIONS MENU
// ============================================

function ProductActionsMenu({ product }: { product: any }) {
  return (
    <div className="relative group">
      <Button variant="ghost" size="icon-sm">
        <MoreHorizontal className="h-4 w-4" />
      </Button>

      {/* Dropdown - shown on hover/focus for simplicity */}
      <div className="absolute right-0 top-full mt-1 w-48 rounded-md border bg-popover shadow-lg z-20 py-1 hidden group-hover:block group-focus-within:block">
        <Link
          href={`/farmer/products/${product.id}`}
          className="flex items-center gap-2 px-3 py-2 text-sm hover:bg-accent transition-colors"
        >
          <Eye className="h-4 w-4" />
          View Details
        </Link>
        <Link
          href={`/farmer/products/${product.id}/edit`}
          className="flex items-center gap-2 px-3 py-2 text-sm hover:bg-accent transition-colors"
        >
          <Edit className="h-4 w-4" />
          Edit Product
        </Link>
        <button
          className="flex items-center gap-2 w-full px-3 py-2 text-sm hover:bg-accent transition-colors text-left"
        >
          {product.status === "ACTIVE" ? (
            <>
              <EyeOff className="h-4 w-4" />
              Deactivate
            </>
          ) : (
            <>
              <Eye className="h-4 w-4" />
              Activate
            </>
          )}
        </button>
        <div className="border-t my-1" />
        <button
          className="flex items-center gap-2 w-full px-3 py-2 text-sm hover:bg-accent transition-colors text-left text-destructive"
        >
          <Trash2 className="h-4 w-4" />
          Delete Product
        </button>
      </div>
    </div>
  );
}

// ============================================
// FILTERS COMPONENT
// ============================================

interface FiltersProps {
  searchParams: SearchParams;
  stats: Record<string, number>;
}

function Filters({ searchParams, stats }: FiltersProps) {
  const { search = "", category = "all", status = "all", view = "grid" } = searchParams;

  return (
    <div className="space-y-4">
      {/* Status Tabs */}
      <div className="flex items-center gap-1 p-1 bg-muted rounded-lg w-fit">
        {[
          { value: "all", label: "All", count: stats.all },
          { value: "ACTIVE", label: "Active", count: stats.ACTIVE },
          { value: "DRAFT", label: "Draft", count: stats.DRAFT },
          { value: "OUT_OF_STOCK", label: "Out of Stock", count: stats.OUT_OF_STOCK },
        ].map((tab) => (
          <Link
            key={tab.value}
            href={`/farmer/products?${new URLSearchParams({
              ...searchParams,
              status: tab.value,
              page: "1",
            } as any).toString()}`}
            className={`px-3 py-1.5 rounded-md text-sm font-medium transition-colors ${status === tab.value
              ? "bg-background shadow-sm text-foreground"
              : "text-muted-foreground hover:text-foreground"
              }`}
          >
            {tab.label}
            <span className="ml-1.5 text-xs text-muted-foreground">({tab.count})</span>
          </Link>
        ))}
      </div>

      {/* Search and Filters Row */}
      <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">
        <div className="flex flex-1 gap-3 w-full sm:w-auto">
          {/* Search */}
          <form className="relative flex-1 max-w-sm">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <input
              type="search"
              name="search"
              defaultValue={search}
              placeholder="Search products..."
              className="w-full pl-10 pr-4 py-2 rounded-md border border-input bg-background text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </form>

          {/* Category Filter */}
          <select
            name="category"
            defaultValue={category}
            className="px-3 py-2 rounded-md border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring"
          >
            <option value="all">All Categories</option>
            {Object.entries(ProductCategoryLabels).map(([value, label]) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </select>
        </div>

        {/* View Toggle & Actions */}
        <div className="flex items-center gap-2">
          {/* View Toggle */}
          <div className="flex items-center border border-input rounded-md">
            <Link
              href={`/farmer/products?${new URLSearchParams({
                ...searchParams,
                view: "grid",
              } as any).toString()}`}
              className={`p-2 ${view === "grid" ? "bg-accent text-foreground" : "text-muted-foreground"
                }`}
            >
              <Grid3X3 className="h-4 w-4" />
            </Link>
            <Link
              href={`/farmer/products?${new URLSearchParams({
                ...searchParams,
                view: "list",
              } as any).toString()}`}
              className={`p-2 ${view === "list" ? "bg-accent text-foreground" : "text-muted-foreground"
                }`}
            >
              <List className="h-4 w-4" />
            </Link>
          </div>

          {/* Export */}
          <Button variant="outline" size="sm">
            <Download className="h-4 w-4 mr-2" />
            Export
          </Button>

          {/* Import */}
          <Button variant="outline" size="sm">
            <Upload className="h-4 w-4 mr-2" />
            Import
          </Button>
        </div>
      </div>
    </div>
  );
}

// ============================================
// PAGINATION COMPONENT
// ============================================

interface PaginationProps {
  pagination: {
    currentPage: number;
    totalPages: number;
    totalCount: number;
    hasNext: boolean;
    hasPrev: boolean;
  };
  searchParams: SearchParams;
}

function Pagination({ pagination, searchParams }: PaginationProps) {
  const { currentPage, totalPages, totalCount, hasNext, hasPrev } = pagination;

  const createPageUrl = (page: number) => {
    const params = new URLSearchParams(searchParams as any);
    params.set("page", page.toString());
    return `/farmer/products?${params.toString()}`;
  };

  return (
    <div className="flex items-center justify-between">
      <p className="text-sm text-muted-foreground">
        Showing page {currentPage} of {totalPages} ({totalCount} products)
      </p>

      <div className="flex items-center gap-1">
        <Button variant="outline" size="sm" disabled={!hasPrev} asChild={hasPrev}>
          {hasPrev ? (
            <Link href={createPageUrl(currentPage - 1)}>
              <ChevronLeft className="h-4 w-4 mr-1" />
              Previous
            </Link>
          ) : (
            <>
              <ChevronLeft className="h-4 w-4 mr-1" />
              Previous
            </>
          )}
        </Button>

        {/* Page Numbers */}
        <div className="hidden sm:flex items-center gap-1">
          {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
            let pageNum: number;
            if (totalPages <= 5) {
              pageNum = i + 1;
            } else if (currentPage <= 3) {
              pageNum = i + 1;
            } else if (currentPage >= totalPages - 2) {
              pageNum = totalPages - 4 + i;
            } else {
              pageNum = currentPage - 2 + i;
            }

            return (
              <Link
                key={pageNum}
                href={createPageUrl(pageNum)}
                className={`px-3 py-1 rounded-md text-sm ${pageNum === currentPage
                  ? "bg-primary text-primary-foreground"
                  : "hover:bg-accent"
                  }`}
              >
                {pageNum}
              </Link>
            );
          })}
        </div>

        <Button variant="outline" size="sm" disabled={!hasNext} asChild={hasNext}>
          {hasNext ? (
            <Link href={createPageUrl(currentPage + 1)}>
              Next
              <ChevronRight className="h-4 w-4 ml-1" />
            </Link>
          ) : (
            <>
              Next
              <ChevronRight className="h-4 w-4 ml-1" />
            </>
          )}
        </Button>
      </div>
    </div>
  );
}



// ============================================
// EMPTY STATE
// ============================================

function EmptyState({ hasFilters }: { hasFilters: boolean }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <div className="h-16 w-16 rounded-full bg-muted flex items-center justify-center mb-4">
        <Package className="h-8 w-8 text-muted-foreground" />
      </div>
      <h3 className="text-lg font-semibold mb-2">
        {hasFilters ? "No products found" : "No products yet"}
      </h3>
      <p className="text-muted-foreground max-w-sm mb-6">
        {hasFilters
          ? "Try adjusting your search or filters to find what you're looking for."
          : "Start by adding your first product to showcase to grocers."}
      </p>
      {!hasFilters && (
        <Button asChild>
          <Link href="/farmer/products/new">
            <Plus className="h-4 w-4 mr-2" />
            Add Your First Product
          </Link>
        </Button>
      )}
    </div>
  );
}

// ============================================
// MAIN PAGE COMPONENT
// ============================================

export default async function FarmerProductsPage({
  searchParams,
}: {
  searchParams: SearchParams;
}) {
  // Authenticate farmer
  let farmer;
  try {
    farmer = await requireFarmer();
  } catch (error) {
    redirect("/login?callbackUrl=/farmer/products");
  }

  // Fetch products
  const { products, pagination, stats } = await getProducts(
    farmer.farmerId,
    searchParams
  );

  const view = searchParams.view || "grid";
  const hasFilters = !!(searchParams.search || searchParams.category !== "all" || searchParams.status !== "all");

  return (
    <div className="flex-1 space-y-6 p-6 md:p-8">
      {/* Header */}
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">My Products</h1>
          <p className="text-muted-foreground">
            Manage your product catalog, inventory, and pricing.
          </p>
        </div>
        <Button asChild>
          <Link href="/farmer/products/new">
            <Plus className="h-4 w-4 mr-2" />
            Add Product
          </Link>
        </Button>
      </div>

      {/* Filters */}
      <Filters searchParams={searchParams} stats={stats} />

      {/* Products */}
      {products.length === 0 ? (
        <EmptyState hasFilters={hasFilters} />
      ) : view === "list" ? (
        /* List View */
        <div className="rounded-lg border bg-card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b bg-muted/50">
                  <th className="w-12 px-4 py-3">
                    <input type="checkbox" className="rounded border-input" />
                  </th>
                  <th className="px-4 py-3 text-left">
                    <button className="flex items-center gap-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground">
                      Product
                      <ArrowUpDown className="h-3 w-3" />
                    </button>
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    Status
                  </th>
                  <th className="px-4 py-3 text-left">
                    <button className="flex items-center gap-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground">
                      Price
                      <ArrowUpDown className="h-3 w-3" />
                    </button>
                  </th>
                  <th className="px-4 py-3 text-left">
                    <button className="flex items-center gap-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground">
                      Stock
                      <ArrowUpDown className="h-3 w-3" />
                    </button>
                  </th>
                  <th className="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    Orders
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    Updated
                  </th>
                  <th className="w-20 px-4 py-3" />
                </tr>
              </thead>
              <tbody>
                {products.map((product) => (
                  <ProductRow
                    key={product.id}
                    product={product}
                  />
                ))}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        /* Grid View */
        <div className="grid gap-4 md:gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {products.map((product) => (
            <Card key={product.id} className="group relative overflow-hidden">
              {/* Product Image */}
              <div className="relative aspect-square overflow-hidden bg-muted">
                <img
                  src={product.images?.[0] || "/images/placeholder-product.jpg"}
                  alt={product.name}
                  className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
                />

                {/* Status Badge */}
                <div className="absolute top-2 left-2">
                  <StatusBadge status={product.status} />
                </div>

                {/* Organic Badge */}
                {product.isOrganic && (
                  <div className="absolute top-2 right-2">
                    <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                      <Leaf className="h-3 w-3" />
                      Organic
                    </span>
                  </div>
                )}

                {/* Quick Actions */}
                <div className="absolute bottom-2 right-2 flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                  <Button size="icon-sm" variant="secondary" asChild>
                    <Link href={`/farmer/products/${product.id}/edit`}>
                      <Edit className="h-4 w-4" />
                    </Link>
                  </Button>
                  <Button size="icon-sm" variant="secondary" asChild>
                    <Link href={`/farmer/products/${product.id}`}>
                      <Eye className="h-4 w-4" />
                    </Link>
                  </Button>
                </div>
              </div>

              {/* Product Info */}
              <CardContent className="p-4">
                <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">
                  {ProductCategoryLabels[product.category as ProductCategory]}
                </p>
                <Link href={`/farmer/products/${product.id}`}>
                  <h3 className="font-semibold line-clamp-1 hover:text-primary transition-colors">
                    {product.name}
                  </h3>
                </Link>

                <div className="flex items-center justify-between mt-3">
                  <div>
                    <span className="text-lg font-bold text-primary">
                      {formatCurrency(product.pricePerUnit)}
                    </span>
                    <span className="text-sm text-muted-foreground">
                      /{product.unit.toLowerCase()}
                    </span>
                  </div>
                  <div className="text-right">
                    <p
                      className={`text-sm font-medium ${product.availableQty < 10
                        ? "text-amber-600"
                        : product.availableQty === 0
                          ? "text-destructive"
                          : "text-muted-foreground"
                        }`}
                    >
                      {product.availableQty} in stock
                    </p>
                  </div>
                </div>

                <div className="flex items-center justify-between mt-3 pt-3 border-t text-sm text-muted-foreground">
                  <span>{product._count.orderItems} orders</span>
                  <span>Updated {formatDate(product.updatedAt, "short")}</span>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Pagination */}
      {products.length > 0 && (
        <Pagination pagination={pagination} searchParams={searchParams} />
      )}
    </div>
  );
}
