// Farm-to-Grocer MVP - Dashboard Shell Component
// Path: app/(dashboard)/dashboard-shell.tsx
// Generated by RJBot Orchestrator
//
// A comprehensive dashboard shell with:
// - Collapsible sidebar navigation
// - Role-based menu items (Farmer/Grocer/Admin)
// - Top header with search, notifications, user menu
// - Mobile-responsive with slide-out drawer
// - Breadcrumb navigation
// - Keyboard shortcuts
// - Persistent sidebar state

"use client";

import * as React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { signOut } from "next-auth/react";
import {
  LayoutDashboard,
  Package,
  ShoppingCart,
  Users,
  Settings,
  HelpCircle,
  LogOut,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Bell,
  Search,
  Sun,
  Moon,
  Leaf,
  Store,
  TrendingUp,
  Truck,
  CreditCard,
  MessageSquare,
  FileText,
  BarChart3,
  Heart,
  MapPin,
  Calendar,
  Shield,
  User,
} from "lucide-react";
import { useTheme } from "next-themes";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/Button";

// ============================================
// TYPES & INTERFACES
// ============================================

interface SessionUser {
  id: string;
  name?: string | null;
  email?: string | null;
  image?: string | null;
  role: "FARMER" | "GROCER" | "ADMIN";
  farmerId?: string;
  grocerId?: string;
}

interface NavItem {
  title: string;
  href: string;
  icon: React.ReactNode;
  badge?: number;
  children?: NavItem[];
}

interface DashboardShellProps {
  children: React.ReactNode;
  user: SessionUser;
}

// ============================================
// NAVIGATION CONFIGURATION
// ============================================

const farmerNavItems: NavItem[] = [
  {
    title: "Dashboard",
    href: "/farmer",
    icon: <LayoutDashboard className="h-5 w-5" />,
  },
  {
    title: "Products",
    href: "/farmer/products",
    icon: <Package className="h-5 w-5" />,
    children: [
      { title: "All Products", href: "/farmer/products", icon: <Package className="h-4 w-4" /> },
      { title: "Add New", href: "/farmer/products/new", icon: <Package className="h-4 w-4" /> },
      { title: "Categories", href: "/farmer/products/categories", icon: <Package className="h-4 w-4" /> },
    ],
  },
  {
    title: "Orders",
    href: "/farmer/orders",
    icon: <ShoppingCart className="h-5 w-5" />,
  },
  {
    title: "Customers",
    href: "/farmer/customers",
    icon: <Users className="h-5 w-5" />,
  },
  {
    title: "Analytics",
    href: "/farmer/analytics",
    icon: <BarChart3 className="h-5 w-5" />,
  },
  {
    title: "Payments",
    href: "/farmer/payments",
    icon: <CreditCard className="h-5 w-5" />,
  },
  {
    title: "Deliveries",
    href: "/farmer/deliveries",
    icon: <Truck className="h-5 w-5" />,
  },
];

const grocerNavItems: NavItem[] = [
  {
    title: "Dashboard",
    href: "/grocer",
    icon: <LayoutDashboard className="h-5 w-5" />,
  },
  {
    title: "Browse Products",
    href: "/grocer/browse",
    icon: <Search className="h-5 w-5" />,
  },
  {
    title: "Orders",
    href: "/grocer/orders",
    icon: <ShoppingCart className="h-5 w-5" />,
  },
  {
    title: "Favorites",
    href: "/grocer/favorites",
    icon: <Heart className="h-5 w-5" />,
  },
  {
    title: "Suppliers",
    href: "/grocer/suppliers",
    icon: <Leaf className="h-5 w-5" />,
  },
  {
    title: "Spending",
    href: "/grocer/spending",
    icon: <TrendingUp className="h-5 w-5" />,
  },
  {
    title: "Deliveries",
    href: "/grocer/deliveries",
    icon: <Truck className="h-5 w-5" />,
  },
];

const adminNavItems: NavItem[] = [
  {
    title: "Dashboard",
    href: "/admin",
    icon: <LayoutDashboard className="h-5 w-5" />,
  },
  {
    title: "Users",
    href: "/admin/users",
    icon: <Users className="h-5 w-5" />,
  },
  {
    title: "Farmers",
    href: "/admin/farmers",
    icon: <Leaf className="h-5 w-5" />,
  },
  {
    title: "Grocers",
    href: "/admin/grocers",
    icon: <Store className="h-5 w-5" />,
  },
  {
    title: "Orders",
    href: "/admin/orders",
    icon: <ShoppingCart className="h-5 w-5" />,
  },
  {
    title: "Reports",
    href: "/admin/reports",
    icon: <FileText className="h-5 w-5" />,
  },
  {
    title: "Settings",
    href: "/admin/settings",
    icon: <Settings className="h-5 w-5" />,
  },
];

const bottomNavItems: NavItem[] = [
  {
    title: "Settings",
    href: "/settings",
    icon: <Settings className="h-5 w-5" />,
  },
  {
    title: "Help & Support",
    href: "/help",
    icon: <HelpCircle className="h-5 w-5" />,
  },
];

// ============================================
// DASHBOARD SHELL COMPONENT
// ============================================

export function DashboardShell({ children, user }: DashboardShellProps) {
  const pathname = usePathname();
  const { theme, setTheme } = useTheme();
  const [sidebarOpen, setSidebarOpen] = React.useState(true);
  const [mobileMenuOpen, setMobileMenuOpen] = React.useState(false);
  const [expandedItems, setExpandedItems] = React.useState<string[]>([]);
  const [searchQuery, setSearchQuery] = React.useState("");
  const [notificationsOpen, setNotificationsOpen] = React.useState(false);
  const [userMenuOpen, setUserMenuOpen] = React.useState(false);

  const userMenuRef = React.useRef<HTMLDivElement>(null);
  const notificationsRef = React.useRef<HTMLDivElement>(null);

  // Get navigation items based on user role
  const navItems = React.useMemo(() => {
    switch (user.role) {
      case "FARMER":
        return farmerNavItems;
      case "GROCER":
        return grocerNavItems;
      case "ADMIN":
        return adminNavItems;
      default:
        return [];
    }
  }, [user.role]);

  // Load sidebar state from localStorage
  React.useEffect(() => {
    const savedState = localStorage.getItem("sidebar-open");
    if (savedState !== null) {
      setSidebarOpen(JSON.parse(savedState));
    }
  }, []);

  // Save sidebar state to localStorage
  React.useEffect(() => {
    localStorage.setItem("sidebar-open", JSON.stringify(sidebarOpen));
  }, [sidebarOpen]);

  // Close mobile menu on route change
  React.useEffect(() => {
    setMobileMenuOpen(false);
  }, [pathname]);

  // Close dropdowns when clicking outside
  React.useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (userMenuRef.current && !userMenuRef.current.contains(event.target as Node)) {
        setUserMenuOpen(false);
      }
      if (notificationsRef.current && !notificationsRef.current.contains(event.target as Node)) {
        setNotificationsOpen(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  // Keyboard shortcuts
  React.useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      // Toggle sidebar with Cmd/Ctrl + B
      if ((event.metaKey || event.ctrlKey) && event.key === "b") {
        event.preventDefault();
        setSidebarOpen((prev) => !prev);
      }
      // Focus search with Cmd/Ctrl + K
      if ((event.metaKey || event.ctrlKey) && event.key === "k") {
        event.preventDefault();
        document.getElementById("dashboard-search")?.focus();
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, []);

  // Toggle expanded menu item
  const toggleExpanded = (title: string) => {
    setExpandedItems((prev) =>
      prev.includes(title) ? prev.filter((item) => item !== title) : [...prev, title]
    );
  };

  // Check if link is active
  const isActiveLink = (href: string) => {
    if (href === `/${user.role.toLowerCase()}`) {
      return pathname === href;
    }
    return pathname.startsWith(href);
  };

  // Handle sign out
  const handleSignOut = async () => {
    await signOut({ callbackUrl: "/" });
  };

  // Get role display info
  const getRoleInfo = () => {
    switch (user.role) {
      case "FARMER":
        return { label: "Farmer", icon: <Leaf className="h-3 w-3" />, color: "bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-300" };
      case "GROCER":
        return { label: "Grocer", icon: <Store className="h-3 w-3" />, color: "bg-blue-100 text-blue-800 dark:bg-blue-900/50 dark:text-blue-300" };
      case "ADMIN":
        return { label: "Admin", icon: <Shield className="h-3 w-3" />, color: "bg-purple-100 text-purple-800 dark:bg-purple-900/50 dark:text-purple-300" };
      default:
        return { label: "User", icon: <User className="h-3 w-3" />, color: "bg-gray-100 text-gray-800" };
    }
  };

  const roleInfo = getRoleInfo();

  return (
    <div className="min-h-screen bg-muted/30">
      {/* ════════════════════════════════════════════════════════════
          SIDEBAR (Desktop)
      ════════════════════════════════════════════════════════════ */}
      <aside
        className={cn(
          "fixed left-0 top-0 z-40 h-screen bg-card border-r border-border transition-all duration-300 ease-in-out",
          "hidden lg:flex lg:flex-col",
          sidebarOpen ? "w-64" : "w-20"
        )}
      >
        {/* Sidebar Header */}
        <div className="flex h-16 items-center justify-between px-4 border-b border-border">
          <Link
            href={`/${user.role.toLowerCase()}`}
            className={cn(
              "flex items-center gap-2 font-bold text-primary transition-opacity",
              !sidebarOpen && "justify-center"
            )}
          >
            <Leaf className="h-7 w-7 flex-shrink-0" />
            {sidebarOpen && <span className="text-lg">Farm to Grocer</span>}
          </Link>
        </div>

        {/* Navigation */}
        <nav className="flex-1 overflow-y-auto py-4 px-3">
          <ul className="space-y-1">
            {navItems.map((item) => (
              <li key={item.title}>
                {item.children ? (
                  // Expandable menu item
                  <div>
                    <button
                      onClick={() => toggleExpanded(item.title)}
                      className={cn(
                        "flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors",
                        "hover:bg-accent hover:text-accent-foreground",
                        isActiveLink(item.href) && "bg-primary/10 text-primary",
                        !sidebarOpen && "justify-center"
                      )}
                    >
                      {item.icon}
                      {sidebarOpen && (
                        <>
                          <span className="flex-1 text-left">{item.title}</span>
                          <ChevronDown
                            className={cn(
                              "h-4 w-4 transition-transform",
                              expandedItems.includes(item.title) && "rotate-180"
                            )}
                          />
                        </>
                      )}
                    </button>
                    {sidebarOpen && expandedItems.includes(item.title) && (
                      <ul className="mt-1 ml-4 space-y-1 border-l border-border pl-4">
                        {item.children.map((child) => (
                          <li key={child.href}>
                            <Link
                              href={child.href}
                              className={cn(
                                "flex items-center gap-2 rounded-lg px-3 py-2 text-sm transition-colors",
                                "hover:bg-accent hover:text-accent-foreground",
                                isActiveLink(child.href) && "bg-primary/10 text-primary font-medium"
                              )}
                            >
                              {child.title}
                            </Link>
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                ) : (
                  // Regular menu item
                  <Link
                    href={item.href}
                    className={cn(
                      "flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors",
                      "hover:bg-accent hover:text-accent-foreground",
                      isActiveLink(item.href) && "bg-primary/10 text-primary",
                      !sidebarOpen && "justify-center"
                    )}
                    title={!sidebarOpen ? item.title : undefined}
                  >
                    {item.icon}
                    {sidebarOpen && <span>{item.title}</span>}
                    {item.badge && sidebarOpen && (
                      <span className="ml-auto rounded-full bg-primary px-2 py-0.5 text-xs text-primary-foreground">
                        {item.badge}
                      </span>
                    )}
                  </Link>
                )}
              </li>
            ))}
          </ul>

          {/* Divider */}
          <div className="my-4 border-t border-border" />

          {/* Bottom Navigation */}
          <ul className="space-y-1">
            {bottomNavItems.map((item) => (
              <li key={item.title}>
                <Link
                  href={item.href}
                  className={cn(
                    "flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors",
                    "hover:bg-accent hover:text-accent-foreground text-muted-foreground",
                    isActiveLink(item.href) && "bg-primary/10 text-primary",
                    !sidebarOpen && "justify-center"
                  )}
                  title={!sidebarOpen ? item.title : undefined}
                >
                  {item.icon}
                  {sidebarOpen && <span>{item.title}</span>}
                </Link>
              </li>
            ))}
          </ul>
        </nav>

        {/* Sidebar Footer - Collapse Toggle */}
        <div className="border-t border-border p-3">
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className={cn(
              "flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors",
              "hover:bg-accent hover:text-accent-foreground text-muted-foreground",
              !sidebarOpen && "justify-center"
            )}
          >
            {sidebarOpen ? (
              <>
                <ChevronLeft className="h-5 w-5" />
                <span>Collapse</span>
              </>
            ) : (
              <ChevronRight className="h-5 w-5" />
            )}
          </button>
        </div>
      </aside>

      {/* ════════════════════════════════════════════════════════════
          MOBILE SIDEBAR OVERLAY
      ════════════════════════════════════════════════════════════ */}
      {mobileMenuOpen && (
        <div
          className="fixed inset-0 z-40 bg-black/50 backdrop-blur-sm lg:hidden"
          onClick={() => setMobileMenuOpen(false)}
        />
      )}

      {/* ════════════════════════════════════════════════════════════
          MOBILE SIDEBAR DRAWER
      ════════════════════════════════════════════════════════════ */}
      <aside
        className={cn(
          "fixed left-0 top-0 z-50 h-screen w-72 bg-card border-r border-border transition-transform duration-300 ease-in-out lg:hidden",
          mobileMenuOpen ? "translate-x-0" : "-translate-x-full"
        )}
      >
        {/* Mobile Sidebar Header */}
        <div className="flex h-16 items-center justify-between px-4 border-b border-border">
          <Link href={`/${user.role.toLowerCase()}`} className="flex items-center gap-2 font-bold text-primary">
            <Leaf className="h-7 w-7" />
            <span className="text-lg">Farm to Grocer</span>
          </Link>
          <button
            onClick={() => setMobileMenuOpen(false)}
            className="rounded-md p-2 hover:bg-accent"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Mobile Navigation */}
        <nav className="flex-1 overflow-y-auto py-4 px-3">
          <ul className="space-y-1">
            {navItems.map((item) => (
              <li key={item.title}>
                <Link
                  href={item.href}
                  onClick={() => setMobileMenuOpen(false)}
                  className={cn(
                    "flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-medium transition-colors",
                    "hover:bg-accent hover:text-accent-foreground",
                    isActiveLink(item.href) && "bg-primary/10 text-primary"
                  )}
                >
                  {item.icon}
                  <span>{item.title}</span>
                  {item.badge && (
                    <span className="ml-auto rounded-full bg-primary px-2 py-0.5 text-xs text-primary-foreground">
                      {item.badge}
                    </span>
                  )}
                </Link>
              </li>
            ))}
          </ul>

          <div className="my-4 border-t border-border" />

          <ul className="space-y-1">
            {bottomNavItems.map((item) => (
              <li key={item.title}>
                <Link
                  href={item.href}
                  onClick={() => setMobileMenuOpen(false)}
                  className={cn(
                    "flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-medium transition-colors",
                    "hover:bg-accent hover:text-accent-foreground text-muted-foreground"
                  )}
                >
                  {item.icon}
                  <span>{item.title}</span>
                </Link>
              </li>
            ))}
          </ul>
        </nav>

        {/* Mobile User Info */}
        <div className="border-t border-border p-4">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
              {user.image ? (
                <img src={user.image} alt={user.name || ""} className="h-10 w-10 rounded-full object-cover" />
              ) : (
                <User className="h-5 w-5 text-primary" />
              )}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium truncate">{user.name}</p>
              <p className="text-xs text-muted-foreground truncate">{user.email}</p>
            </div>
          </div>
          <button
            onClick={handleSignOut}
            className="mt-3 flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium text-destructive hover:bg-destructive/10 transition-colors"
          >
            <LogOut className="h-4 w-4" />
            Sign Out
          </button>
        </div>
      </aside>

      {/* ════════════════════════════════════════════════════════════
          MAIN CONTENT AREA
      ════════════════════════════════════════════════════════════ */}
      <div
        className={cn(
          "min-h-screen transition-all duration-300 ease-in-out",
          sidebarOpen ? "lg:ml-64" : "lg:ml-20"
        )}
      >
        {/* ════════════════════════════════════════════════════════════
            TOP HEADER
        ════════════════════════════════════════════════════════════ */}
        <header className="sticky top-0 z-30 flex h-16 items-center gap-4 border-b border-border bg-card/95 backdrop-blur-sm px-4 lg:px-6">
          {/* Mobile Menu Button */}
          <button
            onClick={() => setMobileMenuOpen(true)}
            className="rounded-md p-2 hover:bg-accent lg:hidden"
          >
            <Menu className="h-5 w-5" />
          </button>

          {/* Search Bar */}
          <div className="flex-1 max-w-md">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <input
                id="dashboard-search"
                type="search"
                placeholder="Search... (⌘K)"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className={cn(
                  "w-full rounded-lg border border-input bg-background pl-10 pr-4 py-2 text-sm",
                  "placeholder:text-muted-foreground",
                  "focus:outline-none focus:ring-2 focus:ring-ring"
                )}
              />
            </div>
          </div>

          {/* Right Side Actions */}
          <div className="flex items-center gap-2">
            {/* Theme Toggle */}
            <button
              onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
              className="rounded-md p-2 hover:bg-accent transition-colors"
              aria-label="Toggle theme"
            >
              {theme === "dark" ? (
                <Sun className="h-5 w-5" />
              ) : (
                <Moon className="h-5 w-5" />
              )}
            </button>

            {/* Notifications */}
            <div className="relative" ref={notificationsRef}>
              <button
                onClick={() => setNotificationsOpen(!notificationsOpen)}
                className="relative rounded-md p-2 hover:bg-accent transition-colors"
                aria-label="Notifications"
              >
                <Bell className="h-5 w-5" />
                <span className="absolute top-1 right-1 h-2 w-2 rounded-full bg-destructive" />
              </button>

              {/* Notifications Dropdown */}
              {notificationsOpen && (
                <div className="absolute right-0 top-full mt-2 w-80 rounded-lg border border-border bg-card shadow-lg">
                  <div className="flex items-center justify-between p-4 border-b border-border">
                    <h3 className="font-semibold">Notifications</h3>
                    <button className="text-xs text-primary hover:underline">Mark all read</button>
                  </div>
                  <div className="max-h-80 overflow-y-auto">
                    {/* Sample notifications */}
                    <div className="p-4 hover:bg-accent/50 cursor-pointer border-b border-border">
                      <p className="text-sm font-medium">New order received</p>
                      <p className="text-xs text-muted-foreground mt-1">Order #1234 from Fresh Market</p>
                      <p className="text-xs text-muted-foreground mt-1">2 minutes ago</p>
                    </div>
                    <div className="p-4 hover:bg-accent/50 cursor-pointer">
                      <p className="text-sm font-medium">Payment confirmed</p>
                      <p className="text-xs text-muted-foreground mt-1">$245.00 deposited to your account</p>
                      <p className="text-xs text-muted-foreground mt-1">1 hour ago</p>
                    </div>
                  </div>
                  <div className="p-3 border-t border-border">
                    <Link
                      href="/notifications"
                      className="block text-center text-sm text-primary hover:underline"
                    >
                      View all notifications
                    </Link>
                  </div>
                </div>
              )}
            </div>

            {/* User Menu */}
            <div className="relative" ref={userMenuRef}>
              <button
                onClick={() => setUserMenuOpen(!userMenuOpen)}
                className="flex items-center gap-2 rounded-lg px-2 py-1.5 hover:bg-accent transition-colors"
              >
                <div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center">
                  {user.image ? (
                    <img src={user.image} alt={user.name || ""} className="h-8 w-8 rounded-full object-cover" />
                  ) : (
                    <User className="h-4 w-4 text-primary" />
                  )}
                </div>
                <div className="hidden md:block text-left">
                  <p className="text-sm font-medium truncate max-w-[120px]">{user.name}</p>
                  <span className={cn("inline-flex items-center gap-1 text-xs px-1.5 py-0.5 rounded-full", roleInfo.color)}>
                    {roleInfo.icon}
                    {roleInfo.label}
                  </span>
                </div>
                <ChevronDown className="h-4 w-4 text-muted-foreground hidden md:block" />
              </button>

              {/* User Dropdown */}
              {userMenuOpen && (
                <div className="absolute right-0 top-full mt-2 w-56 rounded-lg border border-border bg-card shadow-lg py-1">
                  <div className="px-4 py-3 border-b border-border">
                    <p className="text-sm font-medium truncate">{user.name}</p>
                    <p className="text-xs text-muted-foreground truncate">{user.email}</p>
                  </div>
                  <Link
                    href="/profile"
                    className="flex items-center gap-2 px-4 py-2 text-sm hover:bg-accent transition-colors"
                    onClick={() => setUserMenuOpen(false)}
                  >
                    <User className="h-4 w-4" />
                    Profile
                  </Link>
                  <Link
                    href="/settings"
                    className="flex items-center gap-2 px-4 py-2 text-sm hover:bg-accent transition-colors"
                    onClick={() => setUserMenuOpen(false)}
                  >
                    <Settings className="h-4 w-4" />
                    Settings
                  </Link>
                  <Link
                    href="/help"
                    className="flex items-center gap-2 px-4 py-2 text-sm hover:bg-accent transition-colors"
                    onClick={() => setUserMenuOpen(false)}
                  >
                    <HelpCircle className="h-4 w-4" />
                    Help & Support
                  </Link>
                  <div className="border-t border-border my-1" />
                  <button
                    onClick={handleSignOut}
                    className="flex w-full items-center gap-2 px-4 py-2 text-sm text-destructive hover:bg-destructive/10 transition-colors"
                  >
                    <LogOut className="h-4 w-4" />
                    Sign Out
                  </button>
                </div>
              )}
            </div>
          </div>
        </header>

        {/* ════════════════════════════════════════════════════════════
            PAGE CONTENT
        ════════════════════════════════════════════════════════════ */}
        <main className="flex-1">{children}</main>
      </div>
    </div>
  );
}

// ============================================
// EXPORTS
// ============================================

export default DashboardShell;
