// Farm-to-Grocer MVP - Orders API Route Handler
// Path: app/api/orders/route.ts
// Generated by RJBot Orchestrator
//
// RESTful API for order management
// GET: List orders (authenticated - role-based filtering)
// POST: Create order (grocers only)

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { nanoid } from "nanoid";
import prisma, {
  getPaginationParams,
  buildPaginationMeta,
  isPrismaError,
  getPrismaErrorMessage,
  withTransaction,
} from "@/lib/prisma";
import { getSession, requireGrocer } from "@/lib/auth";
import {
  OrderStatus,
  PaymentStatus,
  DeliveryMethod,
  NotificationType,
  type ApiResponse,
  type PaginatedResponse,
  type OrderWithDetails,
} from "@/types";

// ============================================
// VALIDATION SCHEMAS
// ============================================

/**
 * Schema for order item
 */
const orderItemSchema = z.object({
  productId: z.string().cuid("Invalid product ID"),
  quantity: z
    .number()
    .int("Quantity must be a whole number")
    .positive("Quantity must be at least 1"),
});

/**
 * Schema for creating a new order
 */
const createOrderSchema = z.object({
  farmerId: z.string().cuid("Invalid farmer ID"),
  items: z
    .array(orderItemSchema)
    .min(1, "Order must contain at least one item")
    .max(50, "Order cannot contain more than 50 items"),
  deliveryMethod: z.nativeEnum(DeliveryMethod, {
    errorMap: () => ({ message: "Invalid delivery method" }),
  }),
  deliveryAddress: z
    .string()
    .max(500, "Delivery address must be less than 500 characters")
    .optional()
    .nullable(),
  deliveryDate: z
    .string()
    .datetime()
    .optional()
    .nullable()
    .transform((val) => (val ? new Date(val) : null)),
  notes: z
    .string()
    .max(1000, "Notes must be less than 1000 characters")
    .optional()
    .nullable(),
});

/**
 * Schema for search/filter query params
 */
const searchParamsSchema = z.object({
  status: z.nativeEnum(OrderStatus).optional(),
  paymentStatus: z.nativeEnum(PaymentStatus).optional(),
  farmerId: z.string().cuid().optional(),
  grocerId: z.string().cuid().optional(),
  startDate: z
    .string()
    .datetime()
    .optional()
    .transform((val) => (val ? new Date(val) : undefined)),
  endDate: z
    .string()
    .datetime()
    .optional()
    .transform((val) => (val ? new Date(val) : undefined)),
  minTotal: z.coerce.number().nonnegative().optional(),
  maxTotal: z.coerce.number().positive().optional(),
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
  sortBy: z.enum(["createdAt", "total", "status"]).default("createdAt"),
  sortOrder: z.enum(["asc", "desc"]).default("desc"),
});

// ============================================
// CONSTANTS
// ============================================

const TAX_RATE = 0.0825; // 8.25% tax rate
const DELIVERY_FEE = 15.0; // Flat delivery fee

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Generate unique order number
 * Format: FTG-YYYYMMDD-XXXXX
 */
function generateOrderNumber(): string {
  const date = new Date();
  const dateStr = date.toISOString().slice(0, 10).replace(/-/g, "");
  const uniqueId = nanoid(6).toUpperCase();
  return `FTG-${dateStr}-${uniqueId}`;
}

/**
 * Build Prisma where clause from search params
 */
function buildWhereClause(
  params: z.infer<typeof searchParamsSchema>,
  userRole: "FARMER" | "GROCER" | "ADMIN",
  userId: { farmerId?: string; grocerId?: string }
) {
  const where: any = {};

  // Role-based filtering
  if (userRole === "FARMER" && userId.farmerId) {
    where.farmerId = userId.farmerId;
  } else if (userRole === "GROCER" && userId.grocerId) {
    where.grocerId = userId.grocerId;
  }
  // ADMIN can see all orders

  // Status filter
  if (params.status) {
    where.status = params.status;
  }

  // Payment status filter
  if (params.paymentStatus) {
    where.paymentStatus = params.paymentStatus;
  }

  // Specific farmer/grocer filter (for admins)
  if (params.farmerId && userRole === "ADMIN") {
    where.farmerId = params.farmerId;
  }
  if (params.grocerId && userRole === "ADMIN") {
    where.grocerId = params.grocerId;
  }

  // Date range filter
  if (params.startDate || params.endDate) {
    where.createdAt = {};
    if (params.startDate) {
      where.createdAt.gte = params.startDate;
    }
    if (params.endDate) {
      where.createdAt.lte = params.endDate;
    }
  }

  // Total range filter
  if (params.minTotal !== undefined || params.maxTotal !== undefined) {
    where.total = {};
    if (params.minTotal !== undefined) {
      where.total.gte = params.minTotal;
    }
    if (params.maxTotal !== undefined) {
      where.total.lte = params.maxTotal;
    }
  }

  return where;
}

/**
 * Create standardized API response
 */
function createResponse<T>(
  data: T,
  status: number = 200
): NextResponse<ApiResponse<T>> {
  return NextResponse.json(
    {
      success: true,
      data,
    },
    { status }
  );
}

/**
 * Create error response
 */
function createErrorResponse(
  message: string,
  code: string,
  status: number = 400,
  details?: Record<string, string[]>
): NextResponse<ApiResponse<never>> {
  return NextResponse.json(
    {
      success: false,
      error: {
        code,
        message,
        details,
      },
    },
    { status }
  );
}

// ============================================
// GET /api/orders
// List orders (authenticated, role-based)
// ============================================

export async function GET(
  request: NextRequest
): Promise<NextResponse<PaginatedResponse<OrderWithDetails>>> {
  try {
    // Authenticate user
    const session = await getSession();

    if (!session?.user) {
      return createErrorResponse(
        "Authentication required",
        "UNAUTHORIZED",
        401
      ) as any;
    }

    const { user } = session;

    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const params = Object.fromEntries(searchParams.entries());

    // Validate params
    const validationResult = searchParamsSchema.safeParse(params);

    if (!validationResult.success) {
      return createErrorResponse(
        "Invalid query parameters",
        "VALIDATION_ERROR",
        400,
        validationResult.error.flatten().fieldErrors as Record<string, string[]>
      ) as any;
    }

    const validatedParams = validationResult.data;

    // Build query with role-based filtering
    const where = buildWhereClause(validatedParams, user.role, {
      farmerId: user.farmerId,
      grocerId: user.grocerId,
    });

    const { skip, take } = getPaginationParams(
      validatedParams.page,
      validatedParams.limit
    );

    // Execute queries in parallel
    const [orders, total] = await Promise.all([
      prisma.order.findMany({
        where,
        skip,
        take,
        orderBy: {
          [validatedParams.sortBy]: validatedParams.sortOrder,
        },
        include: {
          items: true,
          farmer: {
            include: {
              user: {
                select: {
                  name: true,
                  email: true,
                  phone: true,
                },
              },
            },
          },
          grocer: {
            include: {
              user: {
                select: {
                  name: true,
                  email: true,
                  phone: true,
                },
              },
            },
          },
        },
      }),
      prisma.order.count({ where }),
    ]);

    // Build pagination metadata
    const meta = buildPaginationMeta(
      total,
      validatedParams.page,
      validatedParams.limit
    );

    return NextResponse.json({
      success: true,
      data: orders as OrderWithDetails[],
      meta,
    });
  } catch (error) {
    console.error("GET /api/orders error:", error);

    if (isPrismaError(error)) {
      return createErrorResponse(
        getPrismaErrorMessage(error),
        "DATABASE_ERROR",
        500
      ) as any;
    }

    return createErrorResponse(
      "An unexpected error occurred",
      "INTERNAL_ERROR",
      500
    ) as any;
  }
}

// ============================================
// POST /api/orders
// Create a new order (grocers only)
// ============================================

export async function POST(
  request: NextRequest
): Promise<NextResponse<ApiResponse<OrderWithDetails>>> {
  try {
    // Authenticate and authorize
    let grocer;
    try {
      grocer = await requireGrocer();
    } catch (error) {
      return createErrorResponse(
        "You must be logged in as a grocer to place orders",
        "UNAUTHORIZED",
        401
      );
    }

    // Parse request body
    let body;
    try {
      body = await request.json();
    } catch (error) {
      return createErrorResponse(
        "Invalid JSON in request body",
        "INVALID_INPUT",
        400
      );
    }

    // Validate input
    const validationResult = createOrderSchema.safeParse(body);

    if (!validationResult.success) {
      return createErrorResponse(
        "Validation failed",
        "VALIDATION_ERROR",
        400,
        validationResult.error.flatten().fieldErrors as Record<string, string[]>
      );
    }

    const data = validationResult.data;

    // Validate delivery address for delivery orders
    if (data.deliveryMethod === DeliveryMethod.DELIVERY && !data.deliveryAddress) {
      return createErrorResponse(
        "Delivery address is required for delivery orders",
        "VALIDATION_ERROR",
        400
      );
    }

    // Create order within a transaction
    const order = await withTransaction(async (tx) => {
      // 1. Verify farmer exists and is active
      const farmer = await tx.farmer.findUnique({
        where: { id: data.farmerId },
        include: {
          user: {
            select: { status: true },
          },
        },
      });

      if (!farmer) {
        throw new Error("FARMER_NOT_FOUND");
      }

      if (farmer.user.status !== "ACTIVE") {
        throw new Error("FARMER_NOT_ACTIVE");
      }

      // 2. Fetch and validate all products
      const productIds = data.items.map((item) => item.productId);
      const products = await tx.product.findMany({
        where: {
          id: { in: productIds },
          farmerId: data.farmerId,
          status: "ACTIVE",
        },
      });

      // Check all products exist and belong to the farmer
      if (products.length !== productIds.length) {
        const foundIds = products.map((p) => p.id);
        const missingIds = productIds.filter((id) => !foundIds.includes(id));
        throw new Error(`PRODUCTS_NOT_FOUND:${missingIds.join(",")}`);
      }

      // 3. Validate quantities and calculate totals
      const orderItems: {
        productId: string;
        productName: string;
        quantity: number;
        pricePerUnit: number;
        total: number;
      }[] = [];

      let subtotal = 0;

      for (const item of data.items) {
        const product = products.find((p) => p.id === item.productId)!;

        // Check minimum order quantity
        if (item.quantity < product.minOrderQty) {
          throw new Error(
            `MIN_QTY_NOT_MET:${product.name}:${product.minOrderQty}`
          );
        }

        // Check maximum order quantity
        if (product.maxOrderQty && item.quantity > product.maxOrderQty) {
          throw new Error(
            `MAX_QTY_EXCEEDED:${product.name}:${product.maxOrderQty}`
          );
        }

        // Check available quantity
        if (item.quantity > product.availableQty) {
          throw new Error(
            `INSUFFICIENT_STOCK:${product.name}:${product.availableQty}`
          );
        }

        const itemTotal = product.pricePerUnit * item.quantity;
        subtotal += itemTotal;

        orderItems.push({
          productId: product.id,
          productName: product.name,
          quantity: item.quantity,
          pricePerUnit: product.pricePerUnit,
          total: itemTotal,
        });
      }

      // 4. Calculate order totals
      const tax = Math.round(subtotal * TAX_RATE * 100) / 100;
      const deliveryFee =
        data.deliveryMethod === DeliveryMethod.DELIVERY ? DELIVERY_FEE : 0;
      const total = Math.round((subtotal + tax + deliveryFee) * 100) / 100;

      // 5. Create the order
      const newOrder = await tx.order.create({
        data: {
          orderNumber: generateOrderNumber(),
          farmerId: data.farmerId,
          grocerId: grocer.grocerId,
          status: OrderStatus.PENDING,
          paymentStatus: PaymentStatus.PENDING,
          deliveryMethod: data.deliveryMethod,
          subtotal,
          tax,
          deliveryFee,
          total,
          notes: data.notes,
          deliveryAddress: data.deliveryAddress,
          deliveryDate: data.deliveryDate,
          items: {
            create: orderItems,
          },
        },
        include: {
          items: true,
          farmer: {
            include: {
              user: {
                select: {
                  id: true,
                  name: true,
                  email: true,
                  phone: true,
                },
              },
            },
          },
          grocer: {
            include: {
              user: {
                select: {
                  name: true,
                  email: true,
                  phone: true,
                },
              },
            },
          },
        },
      });

      // 6. Update product inventory
      for (const item of data.items) {
        await tx.product.update({
          where: { id: item.productId },
          data: {
            availableQty: {
              decrement: item.quantity,
            },
          },
        });
      }

      // 7. Update grocer's total orders
      await tx.grocer.update({
        where: { id: grocer.grocerId },
        data: {
          totalOrders: {
            increment: 1,
          },
        },
      });

      // 8. Create notification for farmer
      await tx.notification.create({
        data: {
          userId: newOrder.farmer.user.id,
          type: NotificationType.ORDER_PLACED,
          title: "New Order Received!",
          message: `You have a new order #${newOrder.orderNumber} for $${total.toFixed(2)}`,
          link: `/farmer/orders/${newOrder.id}`,
        },
      });

      return newOrder;
    });

    // Log order creation
    console.log(
      `✅ Order created: ${order.orderNumber} by grocer ${grocer.grocerId}`
    );

    return createResponse(order as OrderWithDetails, 201);
  } catch (error) {
    console.error("POST /api/orders error:", error);

    // Handle custom business logic errors
    if (error instanceof Error) {
      const message = error.message;

      if (message === "FARMER_NOT_FOUND") {
        return createErrorResponse("Farmer not found", "NOT_FOUND", 404);
      }

      if (message === "FARMER_NOT_ACTIVE") {
        return createErrorResponse(
          "This farmer is not currently accepting orders",
          "FORBIDDEN",
          403
        );
      }

      if (message.startsWith("PRODUCTS_NOT_FOUND:")) {
        const missingIds = message.split(":")[1];
        return createErrorResponse(
          `Some products are not available: ${missingIds}`,
          "NOT_FOUND",
          404
        );
      }

      if (message.startsWith("MIN_QTY_NOT_MET:")) {
        const [, productName, minQty] = message.split(":");
        return createErrorResponse(
          `Minimum order quantity for "${productName}" is ${minQty}`,
          "VALIDATION_ERROR",
          400
        );
      }

      if (message.startsWith("MAX_QTY_EXCEEDED:")) {
        const [, productName, maxQty] = message.split(":");
        return createErrorResponse(
          `Maximum order quantity for "${productName}" is ${maxQty}`,
          "VALIDATION_ERROR",
          400
        );
      }

      if (message.startsWith("INSUFFICIENT_STOCK:")) {
        const [, productName, available] = message.split(":");
        return createErrorResponse(
          `Insufficient stock for "${productName}". Only ${available} available.`,
          "VALIDATION_ERROR",
          400
        );
      }
    }

    if (isPrismaError(error)) {
      return createErrorResponse(
        getPrismaErrorMessage(error),
        "DATABASE_ERROR",
        500
      );
    }

    return createErrorResponse(
      "An unexpected error occurred",
      "INTERNAL_ERROR",
      500
    );
  }
}

// ============================================
// OPTIONS /api/orders
// CORS preflight handler
// ============================================

export async function OPTIONS(_request: NextRequest) {
  return new NextResponse(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
      "Access-Control-Max-Age": "86400",
    },
  });
}

// ============================================
// ROUTE SEGMENT CONFIG
// ============================================

// Enable dynamic rendering
export const dynamic = "force-dynamic";

// Disable caching for this route
export const revalidate = 0;

// Set maximum duration for serverless function
export const maxDuration = 60; // Longer timeout for transactions
